동기화 메모장 [STEP 4] 차차, 예거
yagom-academy/ios-cloud-notes pull request #103
Opened 2022-02-25 08:25 UTC by ChaminLee

안녕하세요 코리! @corykim0829 
Step 4 구현하여 PR 보내드립니다! 

검색 중에 삭제/수정에 관련한 에러들을 완전히 고치지는 못했지만, 
현재까지 구현한 내용에 대해서라도 코리의 피드백을 받아보고자 합니다! 🥲

3주간 꼼꼼하게 피드백주셔서 감사합니다! 🙏  

---

# 🔥 고민했던 점 

### 1️⃣ 검색 결과를 선택한 후 다시 리스트로 돌아갈 때 

검색을 한 이후 검색 결과에서 메모를 선택하고 다시 메인 메모 리스트로 돌아갔을 때 select가 유지되지 않거나, 다른 메모가 선택되어있는 문제가 있었습니다. 

UISearchController가 dismiss 될 때 가장 마지막으로 선택된 indexPath 및 선택된 메모에 대한 정보를 가지고 있기에 이를 기준으로 하여 memoDetail, memoTableView가 가지는 indexPath를 업데이트 해주었습니다. 

이를 `UISearchControllerDelegate`의 `func willDismissSearchController(_ searchController: UISearchController)` 메서드를 통해 적합한 시점에 전달해주도록 구현했습니다.

<img src="https://i.imgur.com/RzAQNla.gif" width=50%>

### 2️⃣ 검색 조건

제목만을 가지고 검색하는 것보다는 내용까지 검색 대상에 포함시키는 것이 더 다양한 검색 결과를 보여줄 수 있을 것이라 생각했습니다.

이에 `NSPredicate`를 활용하여 원하는 조건을 request에 넣어주고자 했습니다. 제목 혹은 내용에 검색된 키워드가 포함되어 있으면 검색 결과로 반환시켜주고자 했기에 아래와 같이 구현했습니다.

```swift
func search(for keyword: String) -> [Memo] {
    let request = Memo.fetchRequest()
    var predicates = [NSPredicate]()
    predicates.append(NSPredicate(format: "title CONTAINS[cd] %@", keyword))
    predicates.append(NSPredicate(format: "body CONTAINS[cd] %@", keyword))
    request.predicate = NSCompoundPredicate(orPredicateWithSubpredicates: predicates)
    let searchedMemos = try? context.fetch(request)

    return searchedMemos ?? []
}
```

### 3️⃣ 지역화

지역화를 지원하기 위해 우선 다양한 국가에서 사용하는 언어인 영어를 base 언어로 설정해주었습니다. 이외에도 한국어, 일본어를 지원하여 사용자가 작성한 메모를 제외한 모든 텍스트가 지역화 되도록 구현했습니다!

`Localizable.strings` 파일을 생성하여 key, value 매칭하는 방식으로 구현했습니다

|🇰🇷|🇺🇸|🇯🇵|
|:---:|:---:|:---:|
|![](https://i.imgur.com/7m5wUjV.png)|![](https://i.imgur.com/TV11qna.png)|![](https://i.imgur.com/R6GKzs1.png)|

### 4️⃣ 접근성 

기존에 다른 UI요소들은 다이나믹 텍스트 지원이 되었으나 `UITextView`는 크기가 변경되지 않는 이슈가 있었습니다. 

이에 명시적으로 `adjustsFontForContentSizeCategory` 프로퍼티 값을 true로 주어 정상작동하도록 해주었습니다. 

<img src="https://i.imgur.com/cwkBB5V.gif" width=50%>

<br>

# 🙋🏻‍♂️ 질문하고 싶은 부분 

### 1️⃣ UISearchController 와 UITableView 간의 indexPath 변화를 어떻게 극복해야 할까요?

- UISearchController 구현 시, 이니셜라이저로 `searchResultsController` 를 넣어줘야 하는데요.
저희는 새로운 UITableViewController 를 만들어서 할당해줬습니다.
- 이때, 검색 기능을 사용하면 테이블뷰의 `indexPath`가 아예 달라지더라구요. 😅 
그래서 검색이 켜진 상태에서 메모를 선택하고 수정/삭제하면, 선택한 메모가 수정/삭제되는 게 아니라, 기존 리스트(검색 이전)의 indexPath 에 해당하는 메모가 수정/삭제되는 현상이 생겼습니다.
- ✋🏻 질문 : 만약 프로젝트 초반부터 `검색 기능`까지 고려했었다면, indexPath 가 아닌 `id` 값을 기준으로 메모들을 추적하는 게 나았을까요?
아니면 indexPath 만으로도 충분히 메모들을 추적할 수 있는데, 저희가 방법을 잘 모르는 걸까요? 😢 

![image](https://user-images.githubusercontent.com/71127966/155677080-7a710fd5-401a-4849-a455-c94e6d2d05e2.png)

2022-02-25 13:41 UTC, corykim0829 requested changes
마지막 스텝까지 정말 수고 많으셨습니다!!

로컬라이징, 접근성도 너무 잘 구현하셨어요 👍

검색 결과 선택 후 다시 리스트로 돌아가는 부분은 가끔 selection이 유지가 안되더라구요! 이 부분은 시간이 되면 한번 확인해보세요!

차차, 예거 꽃길만 걸으세요 🌸

---

### 1️⃣ UISearchController 와 UITableView 간의 indexPath 변화를 어떻게 극복해야 할까요?

수정/삭제할 때에는 indexPath로 가져온 값을 실제 데이터에서 id를 기준으로 수정/삭제 처리를 해야할 것 같아요! 제가 이전 피드백에서 indexPath로만 구현하라고 오해의 소지가 있게 말한 것 같네요 🥲
indexPath로는 적절한 추적이 어려워보입니다! id를 사용해서 개선해보면 좋을 것 같아요!

2022-02-25 13:41 UTC, corykim0829 commented on CloudNotes/CloudNotes/Controller/MemoTableViewController.swift
> +        self.navigationItem.hidesSearchBarWhenScrolling = false
self 지정이 꼭 필요한 곳에서만 쓰는게 좋습니다! 참고하세요 :)

2022-02-25 13:41 UTC, corykim0829 commented on CloudNotes/CloudNotes/View/MemoTableViewCell.swift
> +    static let body = "추가 텍스트 없음".localized
로컬라이징 구현 깔끔합니다 👍

2022-02-25 13:41 UTC, corykim0829 commented on CloudNotes/CloudNotes/Controller/MemoTableViewController.swift
> +        guard let selectedId = memoSearchResultTableViewController.selectedMemoId,
프로퍼티에서 축약형은 모두 대문자로 쓰거나 소문자로 시작하면 모두 소문자로 쓰는게 가독성이 더 좋고 의미전달에 잘 됩니다!
selectedID라고 하면 좋을 것 같아요 ㅎ

2022-02-25 13:41 UTC, corykim0829 commented on CloudNotes/CloudNotes/Controller/MemoSearchResultTableViewController.swift
> +        tableView.register(cellWithClass: MemoTableViewCell.self)
이 부분도 함수로 따로 분리하면 더 깔끔할 것 같아요!

2022-02-26 09:24 UTC, Jager-yoo commented on CloudNotes/CloudNotes/Controller/MemoTableViewController.swift
> +        self.navigationItem.hidesSearchBarWhenScrolling = false
명시적으로 `self`를 사용할 필요가 없는 곳에서는 생략해주도록 리팩토링했습니다! 😄 
혹시 self 표현을 꼭 필요한 곳에서만 해야 하는 이유는 어떤 것인지 알려주실 수 있을까요??
코드가 더 짧아지고, self 명시가 필요한 곳과 확실히 `구분`되기 때문일까요? ㅎㅎ

2022-02-26 09:52 UTC, Jager-yoo commented on CloudNotes/CloudNotes/Controller/MemoSearchResultTableViewController.swift
> +        tableView.register(cellWithClass: MemoTableViewCell.self)
넵! tableView 에 Cell 타입을 register 하는 코드를 별도의 메서드로 분리했습니다! 😄 

```swift
private func registerTableViewCell() {
    tableView.register(cellWithClass: MemoTableViewCell.self)
}
```

2022-02-26 09:53 UTC, Jager-yoo commented on CloudNotes/CloudNotes/Controller/MemoTableViewController.swift
> +        guard let selectedId = memoSearchResultTableViewController.selectedMemoId,
[스타일쉐어 Swift Style Guide](https://github.com/StyleShare/swift-style-guide#%EC%95%BD%EC%96%B4) 에서 확인한 적이 있는 내용인데, 누락한 것 같습니다! 😅 
체크해주셔서 감사합니다! 수정했습니다. 👍🏻 

<img width="597" alt="image" src="https://user-images.githubusercontent.com/71127966/155838640-3e6b3680-9ed3-414e-8f44-2ac689ab3fea.png">

2022-03-24 13:51 UTC, closed without merging