Step 2 라자냐와 소대 8모둠 코어데이터 DB 구현
yagom-academy/ios-cloud-notes pull request #12
Opened 2021-02-28 12:20 UTC by zdodev

안녕하세요. @AppleCEO 
Step 2 리뷰 부탁드립니다!

- 기존 샘플 데이터는 삭제했습니다.
- 메모장 CRUD를 코어 데이터를 사용하여 구현하였습니다.
- 따로 가이드가 없어서 CRUD 시 UI 구성을 따로 만들어보았습니다.

궁금한 점
- CRUD 시 각 뷰 컨트롤러끼리 통신하는 방법에 대해서 현재 구현방식에 대한 도미닉의 생각이 궁금합니다! 🤗

2021-03-02 02:09 UTC, AppleCEO requested changes
라자냐 & 소대 고생하셨습니다.
몇가지 코멘트 남겨놨습니다.
또한 화면이 뒤로가기가 안되는 버그가 있어서 이 부분 확인 부탁드릴께요~
![Mar-02-2021 10-34-07](https://user-images.githubusercontent.com/47517256/109585969-c3a1fe00-7b47-11eb-9ead-f7f415719221.gif)

2021-03-02 02:09 UTC, AppleCEO commented on CloudNotes/CloudNotes/ViewControllers/MemoDetailViewController.swift
> +              title.isNotEmpty else {
저는 이렇게 두 줄로 입력하는 것보다 한 줄로 입력하는게 더 좋은 방법 같은데 어떻게 생각하시나요?

2021-03-02 02:09 UTC, AppleCEO commented on CloudNotes/CloudNotes/ViewControllers/MemoDetailViewController.swift
> +    }
이렇게 작은 단위로 메소드를 나누는 것은 아주 좋은 습관입니다 🥇

2021-03-02 02:09 UTC, AppleCEO commented on CloudNotes/CloudNotes/Extension/DateExtension.swift
> +}
이렇게 Date 객체에 extension 으로 메소드를 추가하는 것과 별도의 객체에 같은 기능의 메소드를 추가하는 것은 어떤 차이가 있을까요?

2021-03-02 02:09 UTC, AppleCEO commented on CloudNotes/CloudNotes/ViewControllers/MemoDetailViewController.swift
>  }
delegate 패턴을 활용해보셨군요. 👍 
고급스럽네요!

2021-03-04 07:24 UTC, zdodev commented on CloudNotes/CloudNotes/Extension/DateExtension.swift
> +}
Date 객체에 extension으로 만들 경우 현재 프로젝트에서는 하나의 포맷으로만 변경해서 사용하기 떄문에 별 문제가 없지만, 다른 포맷이 추가될 경우에도 extension으로 구현하게 된다면 모든 Date 객체가 여러 개의 포맷으로 변환될 소지가 있어서 따라서 추후에 에러를 방지하기 위해 객체를 생성하고 메서드로 구현하는 식으로 변경 해보았습니다.

2021-03-04 07:34 UTC, AppleCEO commented
고생하셨습니다~ 다음 단계도 화이팅!

2021-03-04 07:34 UTC, merged