[Step1] Steven
yagom-academy/ios-cloud-notes pull request #23
Opened 2021-06-02 12:36 UTC by stevenkim18

@seizze 하이디!! 오랜만이에요!!

첫번째 PR을 보내요!😀

# 구현한 부분

## 아이폰
![iphone](https://user-images.githubusercontent.com/35272802/120480543-2080af00-c3ea-11eb-9175-1234bcbb4fbf.gif)
## 아이패드
![ipad](https://user-images.githubusercontent.com/35272802/120480574-26769000-c3ea-11eb-864d-4ba7d0236a5a.gif)
## 구현하지 못한 부분

- 아이패드에서 앱을 시작할 때 첫번째 메모의 글이 TextView.text에 나타나는 것
- 키보드가 올라올 때 TextView 커서를 가리는 문제

# 고민을 한 부분

### 아이패드에서 TableView Cell을 클릭 할 때 TextView 화면을 구현하는 부분에서...

위에 아이패드 gif이미지에서 볼 수 있듯이 아이패드화면에서 셀을 클릭 하면 오른쪽에 클릭한 메모의 내용들이 띄우는 것을 어떻게 구현할지 고민을 했습니다. 다음 2가지 방법을 생각했습니다.

1. 그냥 TextView는 가만히 있고 `TextView.text` 에 문자열을 셀을 클릭 할 때 마다 바꾼다.
2. Cell을 클릭 할 때 마다 기존에 있던 ViewController를 삭제하고 새로운 ViewController를 만들어 준다.

저는 1번으로 구현을 했습니다.

그런데 이후에 CoreData를 사용해서 저장을 해야되는데 어떻게 구현을 하는게 나중에 처리하기에 용이 할지에 대해서 조언을 구해요!

# 조언을 얻고 싶은 부분

### 코드로 UI를 구현하실 때 함수를 어떻게 나누는지, 또 어디까지 extension으로 옮겨야 할지 조언 부탁해요!

### TableViewCell을 자동적으로 높이를 주고 싶은데 어떻게 하면 될까요?

[https://arcjeen.tistory.com/15](https://arcjeen.tistory.com/15)

[https://baked-corn.tistory.com/124](https://baked-corn.tistory.com/124)

위의 링크들을 보면서 

- `tableView.rowHeight`
- `tableView.estimatedRowHeight`

들을 조정해 봤는데... 잘 안돼서 일단 상수 값으로 넣어줬습니다..

### 그외 이상한 부분이 있거나 현업에서 잘 사용하지 않는 부분들이 있다면 가감없이 지적해주세요!

2021-06-04 02:09 UTC, seizze requested changes
안녕하세요 스티븐~ 수고많으셨습니다.

> 아이패드에서 TableView Cell을 클릭 할 때 TextView 화면을 구현하는 부분에서...

아직은 1, 2와 CoreData와의 연관성을 찾지 못하겠네요~ ㅎㅎ
그런 고민이 들 땐 다른 곳에선 스플릿뷰를 어떤 방식으로 구현했는지 찾아보는 게 좋습니다. [UISplitViewController Tutorial: Getting Started](https://www.raywenderlich.com/4613809-uisplitviewcontroller-tutorial-getting-started) 여기선 새로 생성하는 방식은 이용하지 않은 것 같아요~ 그래서 지금과 같이 두는게 좋을 것 같습니다.
다음 스텝 진행할 때 저도 이 부분 염두에 두고 볼게요. ☺️

> 코드로 UI를 구현하실 때 함수를 어떻게 나누는지, 또 어디까지 extension으로 옮겨야 할지 조언 부탁해요!

이건 팀에서 정하거나, 아니면 취향의 문제 같네요~ 지금처럼 Delegate나 DataSource를 구현할 때 분리하는 방법도 괜찮습니다. 여기서 코드가 더 많아진다면, 관련된 기능들끼리 모으기도 합니다.

> TableViewCell을 자동적으로 높이를 주고 싶은데 어떻게 하면 될까요?

[Working with Self-Sizing Table View Cells](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/AutolayoutPG/WorkingwithSelf-SizingTableViewCells.html) 여기 나와있는 내용들이 모두 만족되어야 하는데, 뭔가를 하나 빼먹어서 그럴 것 같아요. rowHeight, estimatedRowHeight 말고도 테이블뷰 셀의 높이가 결정될 수 있도록 지정해 주어야 합니다. 
참고로 레이블이 늘어날 수 있도록 numberOfLines도 설정해 주셔야 할 것 같아요~!

<img width="300" alt="image" src="https://user-images.githubusercontent.com/49332230/120735254-3c3ca000-c525-11eb-85c1-fde347404589.png">

구현하지 못한 부분 중에

> 키보드가 올라올 때 TextView 커서를 가리는 문제

이건 이번 수정하시면서 한번 시도해 보셔도 좋을 것 같아요 ㅎㅎ 힌트는 키보드 관련 Notification과 스크롤뷰 Content Inset입니다. 진짜 쓰이는 실용 앱은 이런 디테일을 모두 챙겨야 하는데, 이런 기능들을 몇개 구현해보면 나중에 도움이 많이 되더라고요 ㅎㅎ

2021-06-04 02:09 UTC, seizze commented on CloudNotes/CloudNotes/Cell/ListTableViewCell.swift
> +            bodyLabel.bottomAnchor.constraint(equalTo: self.bottomAnchor, constant: -5)
음.. 제약을 어떤건 cell에 걸고 어떤건 contentView에 거신 이유가 있나요? 🤔

2021-06-04 02:09 UTC, seizze commented on CloudNotes/CloudNotes/Cell/ListTableViewCell.swift
> +            bodyLabel.bottomAnchor.constraint(equalTo: self.bottomAnchor, constant: -5)
dateLabel과 bodyLabel이 모두 bottomAnchor에 걸려있는데, dateLabel과 bodyLabel의 높이가 지금은 동일하지만 나중에 달라지면 constraints가 깨질 수도 있지 않을까요? 저는 항상 변경에 대비해 유연하게 구현하는 편이 더 좋다고 생각합니다. ☺️

2021-06-04 02:09 UTC, seizze commented on CloudNotes/CloudNotes/ViewController/ListTableViewController.swift
> +            textViewController.textView.isEditable = true
메모의 제목과 본문을 어떻게 표시할지는 TextViewController의 역할인 것 같아요~ Memo 자체를 넘겨서 이런 로직은 TextViewController가 수행하게 만드는건 어떨까요?

2021-06-04 02:09 UTC, seizze commented on CloudNotes/CloudNotes/ViewController/TextViewController.swift
> +        ])
<img width="418" alt="image" src="https://user-images.githubusercontent.com/49332230/120734152-62614080-c523-11eb-84ea-0c957604dcc9.png">

safeAreaLayoutGuide.bottomAnchor에 맞추니 아래 회색 부분이..! view.bottom에 맞추는게 좋지 않을까요? ㅎㅎ

2021-06-04 02:09 UTC, seizze commented on CloudNotes/CloudNotes/Model/Memo.swift
> +    }
작성일자는 사용자의 지역 포맷에 맞게 표현되어야 한다는 요구사항이 있는데, 이렇게 하면 항상 같은 포맷으로 나옵니다~! dateStyle을 사용해보면 어떨까요?

2021-06-04 07:13 UTC, stevenkim18 commented on CloudNotes/CloudNotes/Cell/ListTableViewCell.swift
> +            bodyLabel.bottomAnchor.constraint(equalTo: self.bottomAnchor, constant: -5)
음.. 사실 `contentView`의 존재를 모르고 있다가 악세서리뷰랑 겹치게 보여서 오른쪽만 제약을 주었는데...
모든 부분을 `contentView`로 제약을 주는 것으로 수정했습니다!

2021-06-04 07:25 UTC, stevenkim18 commented on CloudNotes/CloudNotes/Cell/ListTableViewCell.swift
> +            bodyLabel.bottomAnchor.constraint(equalTo: self.bottomAnchor, constant: -5)
음... 그러면 날짜 라벨의 bottom과 바디 라벨의 bottom을 같게 주는 방법은 괜찮을까요?

2021-06-04 08:29 UTC, stevenkim18 commented on CloudNotes/CloudNotes/ViewController/ListTableViewController.swift
> +            textViewController.textView.isEditable = true
```swift
textViewController.textView.text = memoList[indexPath.row].title + "\n\n"      
textViewController.textView.text.append(memoList[indexPath.row].body)
```
를 텍스트뷰컨 안에
```swift
func changedTextBySelectedCell(with memo: Memo)
```
함수로 구현해주었습니다!

2021-06-04 08:29 UTC, stevenkim18 commented on CloudNotes/CloudNotes/ViewController/TextViewController.swift
> +        ])
앗 네 이부분도 하이디의 의견을 수용했어요 ㅎㅎ 감사합니다!

2021-06-04 10:03 UTC, seizze commented on CloudNotes/CloudNotes/Cell/ListTableViewCell.swift
> +            bodyLabel.bottomAnchor.constraint(equalTo: self.bottomAnchor, constant: -5)
오 좋은것 같아요 😎

2021-06-04 14:53 UTC, stevenkim18 commented on CloudNotes/CloudNotes/Model/Memo.swift
> +    }
```swift
dateFormat.locale = Locale(identifier: "en_us")
dateFormat.dateStyle = .medium
```
이렇게 identifier에 수동으로 넣어주면 방식으로 구현하면 될것 같은데... 이걸 자동으로 하는 것은 어떻게 하면 될까요?
뭐 GPS로 현재 나의 나리 위치를 파악하거나 시스템 언어 설정에 따라서 자동으로 언어를 인지해서 그 나라의 날짜 포맷으로 바뀌나요?

2021-06-06 06:52 UTC, seizze commented on CloudNotes/CloudNotes/Model/Memo.swift
> +    }
```swift
formatter.locale = Locale.current
```
이렇게 하면 됩니다 ☺️

2021-06-07 05:49 UTC, stevenkim18 commented on CloudNotes/CloudNotes/Model/Memo.swift
> +    }
아... 감사합니다!! 하이디!

2021-06-08 08:13 UTC, stevenkim18 commented
@seizze 
하이디!! 답변 해주신것을 토대로 수정을 해보았습니다

### TextView 키보드가 가리지 않게 하는 처리

월요일 활동학습이 responder chain 이있는데 구글에 검색해 보니 최상단에 하이디 블로그가 떠서 잘 봤습니다. ㅎㅎ 그런데 다른 글을 보니 키보드 처리 관련 글이 있어서 그것을 보고 공부를 했어요

모르는 부분들이 많아서 오늘 TIL 에 정리 했습니다. [TIL 링크](https://www.notion.so/Steven-TIL-210608-b415ba19da074f06aa4fb2b349cd5007)

정리해주신 옛날의 하이디에게 감사합니다!!

---

### 테이블 뷰 셀을 안에 뷰에 맞게 조정하기

이것도 하이디 주신 오토레이아웃 공식을 문서를 보고 해결했습니다.

다만 하다가 `dateLabel` 이 안나오는 문제점이 생겼는데.. 

```swift
let dateLabel: UILabel = {
        let label = UILabel()
        label.translatesAutoresizingMaskIntoConstraints = false
        label.setContentCompressionResistancePriority(.required, for: .horizontal)
        label.setContentHuggingPriority(.required, for: .horizontal)
        label.font = UIFont.preferredFont(forTextStyle: .body)
        return label
    }()
```

- 동료들의 도움으로 CRCH를 설정해주니 해결 되었습니다.

---

> 참고로 레이블이 늘어날 수 있도록 numberOfLines도 설정해 주셔야 할 것 같아요~!

그리고 이부분은 저는 발생하지는 않아서 따로 설정해주지는 않았지만 염두는 해둘게요!

어제 wwdc를 보느라 늦게 남겼습니다.. 수정된 코드 확인 부탁할게요!!

크리티컬한것이 없으면 다음 스탭에서 코어데이터를 배우면서 나머지 기능을 구현하고 싶은데 괜찮을까요? ㅎㅎ

2021-06-09 02:33 UTC, seizze approved these changes
수고 많으셨습니다 스티븐 🙌
그런데 남겨주신 TIL 링크는 권한이 없어서 볼수가 없네요 ㅜㅜ

> CRCH

👍👍 CompressionResistancePriority, ContentHuggingPriority는 현업에서도 자주 사용됩니다.

넵 그러면 머지하겠습니다~

2021-06-09 02:33 UTC, seizze commented on CloudNotes/CloudNotes/ViewController/TextViewController.swift
> +extension TextViewController {
💯💯

2021-06-09 02:33 UTC, merged