Step1 lasagna & sodae 리스트 및 메모영역 화면 UI 구현
yagom-academy/ios-cloud-notes pull request #3
Opened 2021-02-18 09:33 UTC by zdodev

@AppleCEO 안녕하세요 도미닉 리뷰 부탁드립니다!

구현 내용
- 리스트 형태 및 메모 형태 UI 구현
- 리스트 UI는 테이블뷰를 사용하여 구현하였습니다.
- 메모 형태 UI는 테이블뷰와 텍스트뷰를 사용하여 구현하였습니다.
- compact, regular 사이즈에 대응하도록 구현하였습니다.

2021-02-18 12:46 UTC, AppleCEO requested changes
라자냐와 소대 고생하셨습니다.
몇가지 코멘트 남겨놨습니다.
확인해보시고 개선해보세요.

2021-02-18 12:46 UTC, AppleCEO commented on CloudNotes/CloudNotes/AppDelegate.swift
>      func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
사용하지 않는 코드를 지우는 것은 아주 좋은 습관입니다 💯

2021-02-18 12:46 UTC, AppleCEO commented on CloudNotes/CloudNotes/Extension/ViewControllerExtension.swift
> +    }
뷰컨트롤러에 extension 으로 추가하는 것보다 에러를 표시하는 것을 담당하는 객체를 생성하는 것은 어떨까요?

2021-02-18 12:46 UTC, AppleCEO commented on CloudNotes/CloudNotes/Main/MainViewController.swift
> +        setupTable()
setupTableView 라는 메소드명이 더 좋을 것 같네요 ㅎㅎ

2021-02-18 12:46 UTC, AppleCEO commented on CloudNotes/CloudNotes/Main/MainViewController.swift
> +        setupConstraints()
setup으로 시작하는 메소드들이 많은데 이 메소드들을 하나의 메소드에 모아보는 것은 어떨까요?

2021-02-18 12:46 UTC, AppleCEO commented on CloudNotes/CloudNotes/Main/MainViewControllerTableExtension.swift
> +extension MainViewController: UITableViewDelegate {
tableViewDelegate 와 tableViewDatasource 를 다른 익스텐션에서 구성하는 것은 아주 좋습니다.
익숙해질 때까지 이렇게 나눠서 사용하면 이해하는데 도움이 많이 될 것 같네요.

2021-02-18 12:46 UTC, AppleCEO commented on CloudNotes/CloudNotes/Main/MainViewControllerTableExtension.swift
> +        }
guard let 구문이 깔끔하네요 👍

2021-02-18 12:46 UTC, AppleCEO commented on CloudNotes/CloudNotes/Main/MemoTable/MemoTableHeader.swift
> +        self.addSubview(memoTitleLable)
저는 보통 addSubview를 한군데서 모아서 합니다. memoTitleLable 와 addButton 의 addSubview를 하나의 메소드에서 호출하면 나중에 뷰가 추가될 때 착각할 일이 적을 것 같습니다.
예를 들어 memoDescriptionLabel 이라는 뷰를 추가할 일이 생겼을 때 addSubview를 해주는 것을 잊어먹고 바로 오토레이아웃을 작성할 수도 있을 것 같아서요. 참고해주세요.

2021-02-18 12:46 UTC, AppleCEO commented on CloudNotes/CloudNotes/Main/MemoTable/MemoTableViewCell.swift
> +    }
이 코드를 prepareForReuse 함수 안에 넣지 않고 따로 함수로 빼낸 이유가 있을까요?

2021-02-18 12:46 UTC, AppleCEO commented on CloudNotes/CloudNotes/Main/MemoTable/MemoTableViewCell.swift
> +    }
UI를 보여준다라는 메소드명은 불명확한 것 같네요.
어떻게 개선해 볼 수 있을까요?

2021-02-18 12:46 UTC, AppleCEO commented on CloudNotes/CloudNotes/Main/MainViewController.swift
> +        }
아이패드에서 나뉘어보이기 위한 뷰컨트롤러를 애플에서 제공합니다.
그것을 활용해보도록 바꿔보세요.

2021-02-19 08:09 UTC, wonhee009 commented on CloudNotes/CloudNotes/Extension/ViewControllerExtension.swift
> +    }
@AppleCEO 
extension으로 showError()를 구현했던 이유는 범용성을 생각해서 extension으로 구현했는데 도미닉 말대로 객체로 생성하면 갖는 이점이나 extension으로 구현했을때의 단점이 있을까요?

2021-02-19 08:19 UTC, wonhee009 commented on CloudNotes/CloudNotes/Main/MemoTable/MemoTableViewCell.swift
> +    }
현재 프로젝트에서는 tableView cell이 그려지기 전 사전 작업이 필요없는 프로젝트이지만 이후에 prepareForReuse에서 다른 기능이 추가될 경우 기능별로 나눠야한다고 생각해 미리 함수들을 잘게 쪼개는 과정을 거쳤습니다.

2021-02-19 09:16 UTC, wonhee009 commented
@AppleCEO 

SplitViewController로 화면을 재구성했습니다.
재구성하면서 네이밍을 좀 더 명확하게 변경했습니다.

리뷰 부탁드립니다.🙇‍♂️

2021-02-19 11:00 UTC, AppleCEO commented on CloudNotes/CloudNotes/Extension/ViewControllerExtension.swift
> +    }
뷰컨트롤러와 조금 다른 일을 한다고 해서 extension으로 뽑아놓으셨다고 생각합니다.
이렇게 다른 역할을 하는 객체를 생성하면 그 객체에 static method로 선언해서 원할 때 바로 가져다 쓸 수 있어서 좋다고 생각합니다.
extension으로 구현하면 showError가 필요하지 않는 뷰컨트롤러에도 showError 메소드가 추가되어서 비효율적이고 혼돈을 줄 수 있다고 생각합니다.

2021-02-19 11:02 UTC, merged

2021-02-19 11:02 UTC, AppleCEO commented
고생하셨습니다~

2021-02-23 12:52 UTC, zdodev commented on CloudNotes/CloudNotes.xcodeproj/project.pbxproj
> +		28F0B7E225DF965100916219 /* MemoListTableViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = 28F0B7E125DF965100916219 /* MemoListTableViewController.swift */; };
ㅇㅇ