[STEP1] SooJi
yagom-academy/ios-cloud-notes pull request #34
Opened 2021-06-08 12:19 UTC by SoKoooool

🌮 @wonhee009 🌮
안녕하세요❗️ 라자냐👐
라자냐가 없어서 `타코🌮`로 대체합니다😜
개인프로젝트라서 천천히 하려다가 점점 게을러져버렸네요..
아직 버그 투성이고, 해결방법을 찾지 못했지만 라자냐에게 조언을 얻어서 수정하려고 합니다.
`Delegate Pattern`을 공부하는중이라 `STEP1`에서 적용시키지 못하였습니다.
</br>

### 구현내용
메모목록 리스트와 메모 수정/등록 화면은 커스텀으로 만들었고,
스플릿뷰는 커스텀할 내용이 없다고 생각하여 바로 인스턴스로 만들어 사용하였습니다.
</br>

메모 등록/수정 화면에서 나타나는 텍스트뷰의 내용은
프로젝트에 제공되는 메모 샘플 데이터의 내용이 `title`과 `body`가 따로 나누어져 있어서
다른 방법을 찾지 못하여 멀티라인스트링을 사용하여 구현하였습니다
</br>

앱을 구동하면 첫화면이 비어있는 메모 등록/수정 화면이 나오는데
어떻게 접근해야할지 감이 오질않습니다 도와주세요..
</br>

메모목록에서 셀을 선택해서 다음화면으로 넘어갈때
텍스트뷰의 스크롤이 최상단에 고정되어 있지 않아서 
`contentOffset`을 사용하여 해결하려 했지만 적용이 되지않아 실패하였습니다.
</br>

또, 메모목록에서 셀을 선택하였을때 `Size Class`에 따라 화면전환의 방식을 바꾸려고 해보았는데 
- 최초 실행시 세로모드일때: `push` 정상작동
- 이후 가로모드 -> 세로모드 변경시: `push` 정상작동
- 최소 실행시 가로모드일때: `show` 정상작동
- 이후 세로모드 -> 가로모드 변경시: `show` 작동안함
이런 문제가 생겼는데`traitCollectionDidChange`를 사용하면 해결이 될까요 ???

2021-06-09 11:22 UTC, wonhee009 requested changes
SooJi 스텝1 수고하셨어요!
역할을 나누려고 노력한 모습이 보여서 코드 파악하는데 쉬었습니다!👏
코멘트 남겨놨으니 확인 부탁드려요🙏
모르시는 부분이나 궁금한 부분 있다면 연락 주세요!

<img width="620" alt="image" src="https://user-images.githubusercontent.com/30456206/121345205-88417780-c95f-11eb-9bc1-c25abec79450.png">

현재 프로젝트 빌드하면 메모 detail 부터 뜨는데 이 부분 확인 부탁드립니다!

2021-06-09 11:22 UTC, wonhee009 commented on CloudNotes/CloudNotes/MemoData.swift
> +    let lastModified: Int
`Int`로 date를 정의해줬네요!
[공식 문서](https://developer.apple.com/documentation/foundation/timeinterval) 한 번 확인하면 좋을거 같아요!

2021-06-09 11:22 UTC, wonhee009 commented on CloudNotes/CloudNotes/MemoFormViewController.swift
> +        MemoTextView.backgroundColor = .systemGray
현재 `textView`에 배경색을 지정해주고 있는데 기획 스펙인가요?🤔

2021-06-09 11:22 UTC, wonhee009 commented on CloudNotes/CloudNotes/MemoFormViewController.swift
> +class MemoFormViewController: UIViewController {
`MemoFormViewController`라는 이름의 ViewController네요!
메모의 디테일을 보여주는 ViewController로 보여지는데요.
이름을 좀 더 개선할 수 있을까요?

2021-06-09 11:22 UTC, wonhee009 commented on CloudNotes/CloudNotes/MemoListCell.swift
> +    let preview = UILabel()
`title`, `date`, `preview`라는 이름으로는 직관적으로 알기 힘든거 같아요!😢

2021-06-09 11:22 UTC, wonhee009 commented on CloudNotes/CloudNotes/MemoListCell.swift
> +        self.addSubview(cellStackView)
`setLabelConstraints()`는 UILabel의 제약을 설정해주는 메서드네요!
```swift
self.addSubview(cellStackView)
```
위의 코드는 여기에 있는게 맞을까요?🤔

2021-06-09 11:22 UTC, wonhee009 commented on CloudNotes/CloudNotes/MemoListCell.swift
> +        setLabelConstraints()
이 함수 호출부도 `init()`에서 해줘도 될거 같아요☺️

2021-06-09 11:22 UTC, wonhee009 commented on CloudNotes/CloudNotes/MemoListViewController.swift
> +        cell.preview.text = memoData.body
cell content를 여기서 채워주고 있네요!
이 부분을 cell에게 역할을 분담해주는건 어떨까요?

2021-06-09 11:22 UTC, wonhee009 commented on CloudNotes/CloudNotes/MemoListViewController.swift
> +        }
`delegate` 패턴으로 개선해볼 수 있을까요?🙌

2021-06-14 07:05 UTC, SoKoooool commented on CloudNotes/CloudNotes/MemoData.swift
> +    let lastModified: Int
감사합니다.. 샘플 데이터만 확인해보고 TimeInterval을 생각 못하고 있었네요

2021-06-14 09:14 UTC, SoKoooool commented on CloudNotes/CloudNotes/MemoFormViewController.swift
> +        MemoTextView.backgroundColor = .systemGray
기능설명서에 아이폰인 경우에는 배경색이 지정되어 있는데 아이패드의 경우에는 없는걸로 나옵니다.
조건문을 추가하여 배경색이 다르게 지정되도록 하였습니다

2021-06-14 09:17 UTC, SoKoooool commented on CloudNotes/CloudNotes/MemoFormViewController.swift
> +class MemoFormViewController: UIViewController {
처음에 메모등록 화면이라고 생각하여 `MemoFormViewController`라고 네이밍을 하였는데
`MemoDetailViewController`라는 이름이 더 맞는거 같네요

2021-06-14 09:23 UTC, SoKoooool commented on CloudNotes/CloudNotes/MemoListCell.swift
> +        self.addSubview(cellStackView)
`MemoListCell`이 초기화될때 서브뷰를 추가하도록 `init()` 메서드로 이동하였습니다

2021-06-14 09:26 UTC, SoKoooool commented on CloudNotes/CloudNotes/MemoListCell.swift
> +        setLabelConstraints()
까먹고 있었던거 같습니다.. `init()`메서드로 이동하였습니다

2021-06-14 10:20 UTC, SoKoooool commented on CloudNotes/CloudNotes/MemoListCell.swift
> +    let preview = UILabel()
`cellTitle`, `cellDate`, `cellBody`로 수정하였습니다

2021-06-14 11:56 UTC, SoKoooool commented on CloudNotes/CloudNotes/MemoListViewController.swift
> +        cell.preview.text = memoData.body
조언해주신대로 `bindCellContent`라는 메서드를 만들어 `cellForRowAt`의 역할을 분리시켰습니다!
감사합니다 `라자냐👍`

2021-06-15 09:40 UTC, SoKoooool commented on CloudNotes/CloudNotes/MemoListViewController.swift
> +        }
조언해주신것과 다른 캠퍼들의 도움으로 델리게이트 패턴으로 데이터를 전달하여 수정했습니다!

2021-06-15 10:11 UTC, SoKoooool commented
@wonhee009
`🌮라자냐🌮`
🎤코멘트 주신 내용 열심히 수정해보았습니다
중간 중간 질문에 친절하게 답변해주셔서 감사합니다🙇🏻‍♂️
디테일한 답변 내용이.. 크으..👍👍

Delegate Pattern을 공부하느라 시간이 오래걸렸습니다
프로젝트에 적용시키려니 또 이해가 안가고 어렵네요..
제대로 수정한게 맞는지 다시 확인 부탁드립니다!

2021-06-16 05:28 UTC, wonhee009 requested changes
<img width="683" alt="image" src="https://user-images.githubusercontent.com/30456206/122161789-4e1b2d00-cead-11eb-81af-ad3fb7fc84bf.png">

- 가로 모드일때 MemoDetail의 textView에는 배경색이 없는게 스펙인거 같아요...! 이 부분 확인해주세요🙏

- 가로 모드일때 MemoDetail의 textView의 텍스트 오른쪽이 잘리고 있어요! 이 부분도 같이 확인해주세요!

2021-06-16 05:28 UTC, wonhee009 commented on CloudNotes/CloudNotes/MemoData.swift
> +    let lastModified: Double
`Double`로 변환하셨네요!👏
[TimeInterval](https://developer.apple.com/documentation/foundation/timeinterval)을 살펴보면
```swift
typealias TimeInterval = Double
```
로 구성되어 있네요!

여기서 `typelias`는 무엇이고, 왜 `TimeInterval`과 `Double` 둘다 사용할 수 있는지 한 번 생각해보면 좋을거 같아요☺️

2021-06-16 05:28 UTC, wonhee009 commented on CloudNotes/CloudNotes/MemoDetailViewController.swift
> +    }
이 함수는 사용하지 않는 함수인가요?🤔

2021-06-16 05:28 UTC, wonhee009 commented on CloudNotes/CloudNotes/MemoListCell.swift
> +    let cellBody = UILabel()
명확한 네이밍을 위해서 `cell-`로 이름을 바꾸셨군요!
```suggestion
    let titleLabel = UILabel()
    let dateLabel = UILabel()
    let bodyLabel = UILabel()
```

이런 네이밍은 어떠세요?

2021-06-16 05:28 UTC, wonhee009 commented on CloudNotes/CloudNotes/MemoListViewController.swift
> +            print("parsing failed")
이 구문은 에셋의 데이터를 파싱하는데 실패하면 실행되겠네요!
이런 에러를 사용자도 알 수 있게 개선해볼 수 있을까요?

2021-08-06 09:15 UTC, closed without merging