Step 1 : 리스트 및 메모영역 화면 UI구현 (오동나무, 그린)
yagom-academy/ios-cloud-notes pull request #4
Opened 2021-02-18 10:53 UTC by GREENOVER

@Limwin94 
안녕하세요 린👋🏻😃
날씨가 부쩍 추워졌는데 건강 항상 잘챙기세요😷
Step1 리스트 및 메모영역 화면 UI 구현을 완료하여 고민하고 있는 포인트들과 함께 PR 보냅니다!!
리뷰 부탁드립니다🙏🏻

[구현한 점]
-. 역할별로 파일을 폴더화했습니다.
-. 스토리보드를 사용하지않고 코드로만 프로젝트 진행하였습니다.
-. 스플릿뷰를 활용하여 사이즈클래스에 대응하도록 구현하였습니다.

[고민한 점]
1)
[UITextView, dataDetectorTypes & isEditable]
-. dataDetectorTypes로 URL, 전화번호, 등등을 자동으로 탐지해주기 위해서는 isEditable을  false로 설정해주어야 했습니다. 이때 편집 기능도 추가해주기 위해서는 textViewDidTapped 되었을때 isEditable을 true로  바꾸어줘야 했습니다. 이때 단순히 isEditable을  true로 바꾸어주니 커서가 항상 맨  마지막에 찍히고, 텍스트 내부 지점에는 찍히지 않았습니다. 

결과적으로 

```swift
    @objc func textViewDidTapped(_ recognizer: UITapGestureRecognizer) {
        if "UIDataDetectorTypes을 터치했을때" == nil {
            return
        } else if let textView = recognizer.view as? UITextView {
            var location = recognizer.location(in: textView)
            location.x -= textView.textContainerInset.left
            location.y -= textView.textContainerInset.top
            
            placeCursor(textView, location)
            makeTextViewEditable()
        }
    }
```

이렇게 dateDetectorTypes를  터치했을때는 기본적으로 구현된 방식으로 (URL이면 사파리를 열고, 전화번호면 메세지를  열고..) 동작하고, 다른 곳을 터치했을때에는 터치 지점에서 편집이 가능하도록 코드를 작성하고  싶었는데, 이렇게  동작하기 위해서는 "dataDetectorTypes를 터치했을때”에 어떤 코드를 작성해줘야하는지 잘 모르겠습니다..!  혹은  이 방법 외에 더 좋은 방법이 있을까요?
( + 테스트를 하기위해서 body를 구성하는 코드에 전화번호 형태의 String을 추가해두었습니다. )

2) 
-. 처음 스플릿뷰에 리스트테이블뷰와 컨텐츠뷰컨트롤러를 모두 설정하여 뷰가 로드될 수 있게 구현하였는데 처음 뷰가 로드된 화면이 리스트테이블뷰가 아닌 아래 화면과 같이 나왔습니다. 스플릿뷰에서 뷰컨트롤러 배열의 마지막 요소 화면을 첫 화면으로 띄워주는것 같았습니다.

![스크린샷 2021-02-18 오후 7 50 42](https://user-images.githubusercontent.com/73867548/108346371-a8b7bb80-7222-11eb-8bc8-5049831582d8.jpg)

그래서 결과적으로 컨텐츠뷰컨트롤러 설정을 제거하고 뷰의 백그라운드컬러를 화이트로 주게 되었습니다.
두 컨트롤러를 모두 설정하여 해당 문제를 해결할 수 있는 방법이 궁금합니다.

감사합니다 린!👍🏻

2021-02-20 11:23 UTC, Limwin94 requested changes
안녕하세요 오동나무, 그린! 리뷰가 늦어졌습니다. 기다려주셔서 감사해요🙏

코드가 가독성이 좋게 잘 구성되어 있어 읽고 따라가기 편했습니다. 👍🏻 👍🏻 
남겨주신 고민한 점에 대해서는 잘 읽어 보았습니다. 

저도 잘 사용해보지 않은 view라 생각하는데 시간이 오래걸렸던것 같습니다. 고민하셨던 것에 대한 답변 1은 코멘트로 달아 드렸습니다.

현재 compact size에서 한번이라도 cell을 선택한 경우 오동나무, 그린이 말씀하신대로 화면 전환시 textview로 들어오게 되는데 tableview에서 compact -> regular -> compact로 변경할 경우 다시 tableview로 돌아오도록 하게 되는건 어떻게 생각하시나요?

나머지 코멘트들도 확인해주시면 감사하겠습니다 :)
위에도 말씀드렸다시피 코드가 잘 짜여져 있어 남겨주신점 이외에 코멘트 할 부분이 별로 없었습니다.

화이팅입니다. 😁

2021-02-20 11:23 UTC, Limwin94 commented on CloudNotes/CloudNotes/Extension/Date + toStringWithDot.swift
> +    func toStringWithDot() -> String {
Extension을 한 파일에 놓고, 해당 메소드가 어떠한 동작을 하는지 `///` 같은 문서화 주석을 활용해보는것도 한가지의 방법이 될 수 있습니다. :)
좋은 extension입니다. 👍🏻

2021-02-20 11:23 UTC, Limwin94 commented on CloudNotes/CloudNotes/Model/Memo.swift
> +    var lastModifiedDate: String {
Date가 아니라 String으로 나타내려고 하면 어떤 네이밍이 좋을까요?

2021-02-20 11:23 UTC, Limwin94 commented on CloudNotes/CloudNotes/Supporting Files/SceneDelegate.swift
>      func sceneDidDisconnect(_ scene: UIScene) {
쓰지 않는 메소드는 삭제 해주셔도 될것 같습니다 :)

2021-02-20 11:23 UTC, Limwin94 commented on CloudNotes/CloudNotes/View/MemoContentsViewController.swift
> +    @objc func textViewDidTapped(_ recognizer: UITapGestureRecognizer) {
**고민한 점 1**에 대한 답변입니다.
delegate 중에 `shouldInteractWith`를 활용할 수 있는 방법이 있을까요?

2021-02-20 11:23 UTC, Limwin94 commented on CloudNotes/CloudNotes/View/Cell/MemoListTableViewCell.swift
> +        return label
비슷한 옵션을 가진 `UILabel`일 경우 하나의 메소드에서 만들어 내보는건 어떨까요?

2021-02-20 11:23 UTC, Limwin94 commented on CloudNotes/CloudNotes/ViewController/MemoSplitViewController.swift
> +        switch memoListTableViewController.firstSelection {
한줄로 줄일 수 있을것 같습니다 👍🏻

2021-02-20 11:23 UTC, Limwin94 commented on CloudNotes/CloudNotesTests/CloudNotesTests.swift
> +        // 실패할 테스트
실패하는 케이스에 대한 테스트를 만들어 보는 것도 좋을 것 같습니다.

2021-02-22 01:49 UTC, odong-Tree commented on CloudNotes/CloudNotes/Supporting Files/SceneDelegate.swift
>      func sceneDidDisconnect(_ scene: UIScene) {
SceneDelegate와 AppDelegate에 사용하지  않는 메서드들도 초기에 자동으로 함께 생성되고 있습니다. 이때 생성된 메서드 중에 사용하지 않는 메서드를 삭제하면 코드가 정리되는 측면 외에 성능상의 이점이 있는지 궁금합니다!

그리고 Lin은 매번 프로젝트 시작시 이러한 코드를 모두 삭제하고 진행하시는 편이신가요?

2021-02-22 09:32 UTC, odong-Tree commented
@Limwin94 

step1 코드 수정

> 1. 현재 compact size에서 한번이라도 cell을 선택한 경우 오동나무, 그린이 말씀하신대로 화면 전환시 textview로 들어오게 되는데 tableview에서 compact -> regular -> compact로 변경할 경우 다시 tableview로 돌아오도록 하게 되는건 어떻게 생각하시나요?

저희가 놓친 부분이더군요!  navigationBar의 BackButton에 코드를 추가하여 셀이 선택되었는지에 대한 Bool 값을 제어해주고 싶었으나 코드가 잘 동작하지 않아서.. StackOverFlow에서 다른  방법을 찾게 되었습니다. 
결과적으로 메모장 화면에서 viewDisAppear 할때 Notification으로 isCellSelected: Bool 값을 제어해주는 방향으로 수정해보았습니다.


> 2. 고민한 점 1에 대한 답변입니다. delegate 중에 shouldInteractWith를 활용할 수 있는 방법이 있을까요?

shouldInteractWith는 저희가 원하는 기능을 수행해주지는 않더군요 ㅜ 
대신 저희가 기존에 썼던 코드를 다듬어서 기능을 구현해보았습니다. 스크린을 터치했을 때  그 위치를 CGPoint 로 알아내어 다음 동작을 구분하는 조건문을 작성했습니다.


> 3. 비슷한 옵션을 가진 UILabel일 경우 하나의 메소드에서 만들어 내보는건 어떨까요?

좋은 의견 감사합니다! 해당 뷰에서 자주 사용되는 기본적인 UILabel을 만드는 메서드를 따로 빼내어 구현해보았습니다. color는 black을 default 값으로 주었습니다.

> 4. 그 외

그 외에  접근 제한자 및 코드의 네이밍 등 리뷰 내용을 바탕으로 코드를 명확하고 간결하게 수정해보았습니다.

2021-02-23 09:24 UTC, Limwin94 commented on CloudNotes/CloudNotes/Supporting Files/SceneDelegate.swift
>      func sceneDidDisconnect(_ scene: UIScene) {
개인적으로 성능상의 이점은 따로 없는것으로 알고 있습니다.
넵 저도 사용하지 않는 부분은 삭제하고 진행하려고 노력하고 있습니다. 개발중에 사용한 주석도 다 걷어내려고 하고 있어요 :)

2021-02-23 14:40 UTC, Limwin94 reviewed
오동나무, 그린 고생하셨습니다. 

코멘트 남겨보았는데요, 한번 확인해주시고 언제든 DM 남겨주시면 바로 확인하겠습니다. :)

2021-02-23 14:40 UTC, Limwin94 commented on CloudNotes/CloudNotes/Extension/Date + toStringWithDot.swift
> +    /// Returns string converted from data with user's current locale.
피드백을 반영해주셨네요. 감사합니다!

2021-02-23 14:40 UTC, Limwin94 commented on CloudNotes/CloudNotes/Extension/Date + toStringWithDot.swift
> +    /// Returns string converted from data with user's current locale.
@delmaSong 이 Xcode 마크업에 대해 자세하게 정리한 내용이 있어서 읽어보시면 도움이 되실것 같습니다 :)
[문서화 정리 링크](https://github.com/TheSwiftists/effective-swift/pull/97/files)

2021-02-23 14:40 UTC, Limwin94 commented on CloudNotes/CloudNotes/Model/Memo.swift
> +    var lastModifiedDateString: String {
👍🏻  프로퍼티명이 더욱 명확해진것 같습니다.

2021-02-23 14:40 UTC, Limwin94 commented on CloudNotes/CloudNotes/View/MemoContentsViewController.swift
> +        if glyphIndex < textView.textStorage.length,
`glyphIndex`에 대한 유효성 검사 없이 지나칠수도 있었는데 꼼꼼하게 해주셨네요 👍🏻

2021-02-23 14:40 UTC, Limwin94 commented on CloudNotes/CloudNotes/View/MemoContentsViewController.swift
> +        memoTextView.becomeFirstResponder()
만약 수정 후 키보드를 내리고 싶다면 어느 시점에서 resign 해야할까요?

2021-02-23 14:40 UTC, Limwin94 commented on CloudNotes/CloudNotes/View/MemoListTableViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(changeIsCellSelected), name: NSNotification.Name("ShowTableView"), object: nil)
`isCellSelected` 값을 관리하기 위해서 사용하셨군요 💯 

상태값이 여러곳에서 쓰여지는 경우 `UserDefault`에 값을 저장해서 사용하는 방법도 선택할 수 있을것 같습니다 :)

2021-02-23 14:40 UTC, Limwin94 commented on CloudNotes/CloudNotes/View/Cell/MemoListTableViewCell.swift
> +        ])
다시 봐도 깔끔하게 나누셨네요 ✨

2021-02-24 02:46 UTC, odong-Tree commented
@Limwin94 

# 코드 수정 방향

### 1. SplitViewController
- SplitViewController에서 viewDidAppear 코드가 불필요하다고 판단하여 삭제했습니다.  
- 텍스트뷰에도 네비게이션 바를 나타내기 위해 MemoContentsVC를 NavigationVC로 바꾸어 SplitViewController에 추가해주었습니다.


### 2. 키보드 완료 버튼
- textview 편집 시작 시, 키보드의 완료 버튼을 네비게이션 바에 추가되도록 구현하였습니다. 
- 기존의 기획서에서 네비게이션 바에 '더보기' 버튼이  추가되는 방향으로 수정되어서 rightBarButtonItems 로 함께 다루어 주었습니다. 

<br>
<br>

그리고 언급해주신 UserDefault 에 대해서는 step2에서 함께  고민해보고 싶어요!
step1 merge 요청합니다 :)

2021-02-24 14:36 UTC, Limwin94 approved these changes
오동나무, 그린 고생하셨습니다 :) 다음 스텝에서 뵈요!

2021-02-24 14:36 UTC, merged