동기화 메모장 [STEP 1] Luyan
yagom-academy/ios-cloud-notes pull request #47
Opened 2021-09-03 10:42 UTC by KimWanki

린생! 안녕하세요! @jungseungyeo 

늦은 시간 PR 죄송합니다! 
한 주 잘 마무리 하셨나요??
이번 주도 고생 많으셨습니다. :)
최대한 구현해보려고 했는데 아직 해결하지 못한 이슈도 많고, 잔버그도 많은 것 같습니다.ㅎㅎ;; (땀이 나네요)
부족한 부분이 많습니다. 🪡🪡🪡 따끔한 맛 코드 리뷰 부탁드립니다.
로직 상에 문제가 없더라도 더 좋은 방향이 있다고 생각되시면 꼭 말씀해주세요!

### 실행 화면

![cloud_실행화면1](https://user-images.githubusercontent.com/57824307/131990540-a00c459d-a6af-47b8-9240-67cef088568d.gif)

![cloud_실행화면](https://user-images.githubusercontent.com/57824307/131990906-a48f5845-3b28-482e-97b7-ae64faffd635.gif)

###

--- 
####  SwiftLint 를 적용해 코드 스타일을 일관되도록 유지하였습니다. 
-> 하지만 프로그래밍 시 스타일로 인한 경고를 많이 보진 못했던 것 같네요!

이번 프로젝트를 진행하면서, SplitView를 처음 다뤄보고 있는데, 제대로 구현하고 있지 못한 것 같다는 생각도 들고, 확신을 가지고 코딩을 하고 있는게 맞는지 스스로 의구심이 조금 들었습니다. 좀더 문서도 톺아보고, 여러 적용도 해봐야겠다는 생각이 듭니다.

수요일에 레이아웃과 관련된 피드백을 주시고, 와! 했던게 엊그제 같은데 엊그제 맞네요ㅋㅋ 덕분에 VC가 좀더 로직에 집중할 수 있도록 코드를 작성할 수 있었다고 생각합니다. 해서 상속을 활용한 View와 ViewController 방식을 같이 사용해봤습니다. (린생 깃헙에 있는 Nexters 코드 레이아웃도 조금 훔쳐봤습니다ㅋㅋ)

먼저 제공 받은 데이터는 하단과 같이 asset의 형태로 제공되었습니다.

![image](https://user-images.githubusercontent.com/57824307/131989786-af36904f-6eaa-440e-a4e2-cbf0d44600ae.png)

하지만 Contents 내의 정보는 실제 정보를 표기하는데 필요없다는 판단이 들어 sample.json 파일만 프로젝트에 사용하였습니다.
sample.json파일에 매칭되는 해당 json 파일에 매칭되도록 model 디렉토리 내에 Memo 타입을 선언하였습니다.

cell에 대한 정보를 입력할 때는, View 안에서 DateFormatter을 통한 변환로직이 이뤄지지 않도록 하기 위해 MemoPresentModel 타입을 선언해 configure(with presentModel: MemoPresentModel)을 활용하였습니다.

- Model 

```swift
struct Memo: Decodable {
    let title: String
    let body: String
    let lastDate: Double

    enum CodingKeys: String, CodingKey {
        case title
        case body
        case lastDate = "last_modified"
    }
}
```

- Present Model

```swift
struct MemoPresentModel {
    let title: String
    let body: String
    let date: String
}
```

### 해결하지 못한 Issue, 1

![image](https://user-images.githubusercontent.com/57824307/131992930-7c5edef3-693c-43f5-9b29-bea48f0ab051.png)

detailView의 내용을 수정할 경우, 키보드 밑으로 내려갈 경우, 현재 **글 내에서 커서가 제대로 보이지 않는 에러**가 있습니다 키보드 위로 스크롤을 제한하는 방법을 사용해야할 것 같은데.. 그 부분에 대해서 제대로 적용하지 못했습니다.

### 해결하지 못한 Issue, 2

추가로 코드로 오토레이아웃을 잘 적용했다고 생각하는데, TextView에서 keyboard가 올라오는 경우 오토레이아웃에 대한 경고가 발생하네요. 관련된 내용을 찾아보다가 애플 포럼을 좀 보게 됐는데, 관련해서 작동에는 문제 없다... 이런 의견도 있는 것 같은데 애플이 에러가 없는데, 경고를 내줄리 없다고 생각해서요. 사실 위에 말씀드린 내용이랑 같은 맥락의 문제가 아닐까 싶습니다. 에러 내용과 봤던 포럼 내용 하단에 첨부하였습니다!

```
 "<NSAutoresizingMaskLayoutConstraint:0x600003aae120 h=--& v=--& _UIButtonBarButton:0x7f7fc063aaa0.height == 0   (active)>",
```

https://developer.apple.com/forums/thread/667441

![image](https://user-images.githubusercontent.com/57824307/131992983-f4185261-4ffc-4950-9c7d-0c605514dd77.png)

#### 사용자에 의해 수정된 내용이 json 파일로부터 가져온 memoList: [Memo]에 적용되야 하는데, 이부분을 delegate 패턴을 활용해서 사용했습니다. DetailView에서 textViewDelegate를 채택해서, textViewDidEndEditing 시점에 해당 작업이 이뤄지도록 구현해 보았습니다.

아, 그리고 **뷰 간 데이터 전달에도 델리게이트 패턴**을 활용하였습니다. 

 `Memoriable` 프로토콜을 선언하고, delegate 패턴을 활용해 수정 내용이 이전 뷰에 반영되도록 로직을 구성하였습니다.
하지만 지금 구현에서는 수정한 위치의 인덱스를 함께 전달하고 있는데, 해당 부분에 대해 인덱스 없이 메서드를 구현하는 있으면 좋겠다는 생각이 드네요. 가능한 부분이라면 조언을 주시면 감사하겠습니다.

이외에도 잔버그들이 정말 많다고 생각합니다. 
( 아이폰 세로 모드에서 기본값으로... detail View가 먼저 보입니다. ,
완벽히 이해하고 짠 느낌이 아니에요)

혼자 고민하다가 PR이 너무 늦어질 것 같다는 생각에.. 이렇게 금요일 밤에 문 두드려봅니다.

아주 조금이라도 제가 찾아보고 고민해볼만한 부분이라면 콕 찝어주세요!!

2021-09-04 15:41 UTC, jungseungyeo requested changes
해결하지 못한 Issue, 1

>  키보드를 하기 위해서는 키보드의 보여지는 순간과 안보여지는 순간의 이벤트를 받아 BottomContraint를 변경해주면 됩니다 :) scrollView를 활용하여 스크롤도 가능하게 하면 더욱 좋을거 같아요!

해결하지 못한 Issue, 2

https://www.wtfautolayout.com/  사이트를 활요해보면 좋을거 같아요! 어디서 레이아웃이 깨지고 있는지도 확인해보고 수정해주세요 :) 

해당 부분에 대해 인덱스 없이 메서드를 구현하는 있으면 좋겠다는 생각이 드네요. 가능한 부분이라면 조언을 주시면 감사하겠습니다.

> 인덱스를 접근하는거는 나쁘지 않지만 전달하는 방법이 나쁜거 같아요. 참조타입을 활용하면 가능하지 않을까요?

전박전으로 delegate 패턴을 사용하는 것이 너무 익숙하여 좋습니다 :) 코드를 보면서 delegate를 화용하는거랑 model을 매핑하는 부분에서 좋았습니다. 디테일 떨어지는 부분은 수정하면 좋을거같아요! index를 사용하지 않고 하는 부분과 레이아웃이 깨지는 이슈만 해결하면 좋을거 같아요! 

루얀 고생하셨습니다 :)

2021-09-04 15:41 UTC, jungseungyeo commented on CloudNotes/.swiftlint.yml
> +excluded:
excludeed와 included 써주면 무슨 일이 일어날까요?

2021-09-04 15:41 UTC, jungseungyeo commented on CloudNotes/CloudNotes/AppLifeCycle/SceneDelegate.swift
> +        let splitView = SplitViewController()
window보다 먼저 생성되는 이유가 있을까요?

2021-09-04 15:41 UTC, jungseungyeo commented on CloudNotes/CloudNotes/AppLifeCycle/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
makeKeyAndVisible를 사용하고 안하고 목적이 무엇일까요?

2021-09-04 15:41 UTC, jungseungyeo commented on CloudNotes/CloudNotes/Extensions/UIView+Extensions.swift
> +        for view in views {
너무 좋아요 :)

2021-09-04 15:41 UTC, jungseungyeo commented on CloudNotes/CloudNotes/SupportingFiles/JSONHandler.swift
> +struct JSONHandler {
JSONHandler가 struct이고 JSONUtil은 왜 enum인가요? 두가지 차이점이 무엇인가요?

2021-09-04 15:41 UTC, jungseungyeo commented on CloudNotes/CloudNotes/View/MemoDetailView/MemoDetailView.swift
> +        textView.font = UIFont.preferredFont(forTextStyle: .body)
```suggestion
        textView.font = .preferredFont(forTextStyle: .body)
```

개인 스타일이지만 이렇게 쓰는거랑 안쓰는거랑 어떤 차이가 있을까요?

2021-09-04 15:41 UTC, jungseungyeo commented on CloudNotes/CloudNotes/View/MemoDetailView/MemoDetailView.swift
> +        detailTextView.translatesAutoresizingMaskIntoConstraints = false
여기서 써주면 subViews를 만들어준 이유가 없지 않나요?

2021-09-04 15:41 UTC, jungseungyeo commented on CloudNotes/CloudNotes/View/MemoDetailView/MemoDetailViewController.swift
> +    override func setup() {
super를 뺸 이유가 있나요?

2021-09-04 15:41 UTC, jungseungyeo commented on CloudNotes/CloudNotes/View/MemoListView/MemoListCell.swift
> +extension MemoListCell {
이것도 BaseCollectionViewCell를 사용하면 좋지 않나요?

2021-09-04 15:41 UTC, jungseungyeo commented on CloudNotes/CloudNotes/View/MemoListView/MemoListViewController.swift
> +        memoList.last.flatMap {
flatMap안에서 화면 전화이 되고 있네요. flatMap의 역할이 무엇일까요?

2021-09-04 15:41 UTC, jungseungyeo commented on CloudNotes/CloudNotes/View/MemoListView/MemoListViewController.swift
> +                     date: DateFormatter.localizedString(from: Date(timeIntervalSince1970: memo.lastDate), dateStyle: .long, timeStyle: .none))
데이터 포맷 너무 좋네요 :)

2021-09-04 15:41 UTC, jungseungyeo commented on CloudNotes/CloudNotes/View/MemoListView/MemoListViewController.swift
> +                     date: DateFormatter.localizedString(from: Date(timeIntervalSince1970: memo.lastDate), dateStyle: .long, timeStyle: .none))
https://ko.wikipedia.org/wiki/ISO_8601 여기 내용도 같이 보면 좋을거 같아요! ISO 8601 라고 국제 표준 날짜표시 format입니다 :)

2021-09-04 15:41 UTC, jungseungyeo commented on CloudNotes/CloudNotes/View/MemoListView/MemoListViewController.swift
> +        memoList[index].title = newMemo.title
프로퍼티를 직접 접근에서 변경 보다는 update를 함수를 제공해주면 좋을거같아요!

2021-09-04 15:41 UTC, jungseungyeo commented on CloudNotes/CloudNotes/View/SplitViewController.swift
> +        self.delegate = self
delegate를 말할려고 했는데 ㅎㅎ 금방 고치셨네요 ㅎㅎ 항상 delegate의 역할을 잊지마세요 :)

2021-09-04 15:41 UTC, jungseungyeo commented on CloudNotes/CloudNotes/View/SplitViewController.swift
> +class SplitViewController: UISplitViewController {
이 class를 RootViewController를 상속받지 않네요 모든 UIViewController가 RootViewController를 상속받지 않는다면 RootViewController의 역할은 어떻게 해야 될까요? SplitViewController처러 모든 UIViewController를 제어 하기 위해서는 어떤 방식이 또 있을까요?

2021-09-05 09:25 UTC, KimWanki commented on CloudNotes/CloudNotes/AppLifeCycle/SceneDelegate.swift
> +        let splitView = SplitViewController()
uiwindow 위에 uiview가 올라가게 되는데, 코드의 순서를 고려하지 않았던 것 같네요. 해당 부분 반영하겠습니다 :)

2021-09-05 11:45 UTC, KimWanki commented on CloudNotes/CloudNotes/AppLifeCycle/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
window 중 가장 앞쪽에 배치된 윈도우를 keywindow라고 하는데 현재의 윈도우를 keyWindow로 만들고, 이벤트 처리행동을 제공하고, View들을 담는 컨테이너의 역할을 하게됩니다.

2021-09-05 11:50 UTC, KimWanki commented on CloudNotes/CloudNotes/SupportingFiles/JSONHandler.swift
> +struct JSONHandler {
두 타입의 가장 큰 차이는 인스턴스화를 할 수 있느냐 없느냐의 차이라고 생각해요. 두 구현 모두 가능한 방법이라고 생각하지만, JSONUtil을 Enum으로 구성한 건 Util이라는 네이밍에 집중했을 때, 타입의 역할이라기보단 개별된 기능의 모음으로 생각하는게 좋지 않을까. static 함수 형태의 Enum으로 구현하였습니다.

2021-09-05 11:59 UTC, KimWanki commented on CloudNotes/CloudNotes/View/MemoDetailView/MemoDetailView.swift
> +        textView.font = UIFont.preferredFont(forTextStyle: .body)
13, 14 라인 모두 
`textView.backgroundColor = UIColor. ~~`
`textView.font = UIFont. ~~ `
할당 연산 왼쪽에 있는 요소들이 모두 해당 타입을 유추할 수 있게 해주고 있는데, 각각 Color, font 가 중복되어 나타나고 있다고 생각되네요. 위와 같이 타입이 충분히 유추가 가능할 땐 쓰지 않는게 중복을 줄일 수 있을 것 같아요

2021-09-05 12:00 UTC, KimWanki commented on CloudNotes/CloudNotes/View/MemoDetailView/MemoDetailView.swift
> +        detailTextView.translatesAutoresizingMaskIntoConstraints = false
:) 👍

2021-09-05 12:08 UTC, KimWanki commented on CloudNotes/CloudNotes/View/MemoDetailView/MemoDetailViewController.swift
> +    override func setup() {
RootViewContoller의 setup에서 공통된 작업이 진행되고 있지 않다. 라는 판단에서 super.setup()를 사용하지 않았습니다! 
RootViewController에서 초기에 처리해야 할 작업에는 어떤 것들이 있는지 잘 모르겠습니다. ㅠㅠ

2021-09-05 12:09 UTC, KimWanki commented on CloudNotes/CloudNotes/View/MemoListView/MemoListCell.swift
> +extension MemoListCell {
향후 확장성을 생각하면 좋은 방향이라고 생각됩니다! 이부분도 한번 반영해볼게요!

2021-09-05 12:52 UTC, KimWanki commented on CloudNotes/CloudNotes/View/MemoListView/MemoListViewController.swift
> +        memoList.last.flatMap {
swift가 제공하는 flatMap 2가지 중 deprecated 경고가 나오는 non-nil의 배열을 반환하는 flatMap이 아닌 optional 타입에서 사용 가능한 flatMap(_:)을 활용해보았는데요. 사실 optional에 대한 해제에 있어서 고차함수를 사용하는 것이 어떻게 받아들여질까? 라는 부분이 궁금했습니다.

flatMap의 클로저에서 Optional Value를 해제된 상태로 사용이 가능하고,  if let 이나 guard를 통한 옵셔널을 해제할 경우처럼 추가적인 변수선언이 필요하지 않다는 점에서 위와 같은 로직으로 작성해봤어요.
하지만 말씀해주신 화면 전환 로직 flatMap에서 이뤄져야할 작업은 아니라고 생각되네요!

2021-09-08 05:02 UTC, KimWanki commented
린생! 제안해주신 부분에 대해서 다시 코드를 작성해봤어요. 한번 더 확인 부탁드릴게요!

2021-09-09 15:00 UTC, KimWanki commented on CloudNotes/.swiftlint.yml
> +excluded:
lint를 포함할 경로와 포함하지 않을 경로를 결정할 수 있습니다!

2021-09-09 15:02 UTC, KimWanki commented on CloudNotes/CloudNotes/View/SplitViewController.swift
> +class SplitViewController: UISplitViewController {
이건 직접 린생이 예시 코드를 작성하면서 보여주셨던 부분에서 크게 와닿았던 부분인 것 같아요. 프로토콜을 활용한 방법을 열심히 익혀볼게요!

2021-09-09 15:20 UTC, jungseungyeo approved these changes
루얀 고생하셨어요 ㅎㅎ 다음 step 진행해주세요 ㅎㅎ protocol을 활용하는게 너무 좋았습니다 :) 고생하셨습니다.

2021-09-09 15:20 UTC, jungseungyeo commented on CloudNotes/CloudNotes/SupportingFiles/JSONHandler.swift
> +struct JSONHandler {
너무 정확히 알고있네요 ㅎㅎ 너무 좋습니다 :)

2021-09-09 15:20 UTC, jungseungyeo commented on CloudNotes/CloudNotes/View/MemoListView/MemoListViewController.swift
> +        memoList.last.flatMap {
아부분은 같이 이야기를 했었죠? ㅎㅎ 너무 좋습니다 :)

2021-09-09 15:20 UTC, jungseungyeo commented on CloudNotes/CloudNotes/View/Root/RootViewController.swift
> +protocol RootViewControllerable {
너무좋네요 ㅎㅎ

2021-09-09 15:20 UTC, merged