동기화 메모장 [Step 1] Shapiro
yagom-academy/ios-cloud-notes pull request #53
Opened 2021-09-06 14:40 UTC by shapiro711

@wonhee009 
안녕하세요 라자냐 스탭1을 어느정도 완성하여 PR을 보냅니다!!
부족한 부분이 많을거라 생각돼요!! 잘 부탁드립니다 :)

## 구현한 내용
1. MemoListView, DetailMemoView UI 구현
2. SplitView를 이용하여 ClassSize에 반응할 수 있도록 구현
3. 메모의 추가, 수정, 저장기능 구현

## 궁금한 내용
1. Size가 변동이 있을때 보여지는 화면 - 현재 compact 이면서 처음으로 보여지는 화면이 master view로 설정하기 위해 UISplitViewContorllerDelegate 메서드를 사용하였습니다. 사용자가 regular size에서 detail view를 보고 있을때 compact size로 변하게 된다면 그때는 detail view가 나타나야 한다고 생각합니다. 이것을 처리하기 위해 flag를 두고 처리를 했는데 괜찮은 방법인지, 더 좋은 방법이 없을지 궁금합니다.
```Swift
extension SplitViewController: UISplitViewControllerDelegate {
    
    func splitViewController(_ svc: UISplitViewController, topColumnForCollapsingToProposedTopColumn proposedTopColumn: UISplitViewController.Column) -> UISplitViewController.Column {
        if isFisrtCellSelection == false {
            return .primary
        } else {
            isFisrtCellSelection = true
            return .secondary
        }
    }
}
```
2. MemoListView, DetailMemoView간의 통신 - 공식문서에 두 화면간의 통신은 SplitView를 통해서 이루어지는것이 좋다는 이야기를 보았습니다. 그래서 MemoListView, DetailMemoView의 delegate 프로토콜을 만들고 각각의 delegate를 SplitView가 가지고 있는 방식으로 구현했는데요... 바로 두화면끼리 서로 통신을하지않고 SplitView를 통해서 할때의 장점이 궁금합니다.
3. 메모 저장 시기 - 현재 UITextViewDelegate 메서드를 통해서 editing이 있다면 저장하고 MemoListView에게 알려주는 방법으로 구현하였습니다. textViewDidEndEditing 메서드를 이용할때 문제가 regular 일때 editing 도중 테이블 뷰의 다른 셀을 선택하는 등 editing이 완전 끝났다는 것을 알리는것이 모호합니다. 네비게이션 아이템에 done 버튼을 띄우는것과 같이 확실하게 끝났다는 것을 알려줄 필요가 있다고 생각하는데 어떻게 해결하는것이 좋을까요? 아니면 CoreData를 다음 스탭에서 적용하면서 CRUD 부분을 다시 생각하는 것이 좋지 않을까.... 하는 생각도 듭니다!
```Swift
extension DetailMemoViewController: UITextViewDelegate {
    
    func textViewDidEndEditing(_ textView: UITextView) {
        
        let newMemo = Memo(title: titleTextView.text, body: bodyTextView.text, date: Date().timeIntervalSince1970)
        
        memo = newMemo
        
        guard let savedMemo = memo else { return }
        delegate?.saveMemo(with: savedMemo, index: self.index)
    }
}
```
4. 코드로 UI 구현 -  코드로 UI 구현하는 부분에 집중해보기 위해 스토리보드도 아예 삭제하고 진행하였습니다. 이렇게 코드로 UI를 만들어본 경험이 처음이라 잘 한건지에 대한 감이 오지않습니다... 부족한 부분이 많을것 같은데 피드백 부탁드려요!!

2021-09-07 14:59 UTC, wonhee009 requested changes
샤피로 스텝1 수고하셨습니다!🎉

메모 추가, 수정, 저장 기능을 확인해봤는데요!
- A 메모 수정 시 제목을 수정 후 A메모의 본문을 눌러야만 수정 사항이 반영되더라구요. 혹시 이 부분은 일부러 이렇게 제한을 두신건지 궁금합니다. 의도를 가지고 제한을 두신 부분이 아니라면 수정 후 A가 아닌 다른 메모를 눌렀을 때에도 A 메모의 수정 사항이 저장되는 방향은 어떠실까요?
- '+' 버튼을 눌렀을때에는 자동으로 메모 리스트에 빈 메모가 생기는거로 확인되는데요. 사용자가 '+' 버튼을 누른 후 아무런 동작을 하지 않고 다른 메모를 누른다면 title="", body=""인 메모가 생기는데 사용자가 내용을 입력하지 않았을때에는 리스트에 남지 않도록하는 방향은 어떠실까요?
- 현재 샤피로가 구현한 코드상으로는 메모 추가/수정시에 테이블뷰 전체를 리로드해주고 있는데요. 수정시에는 수정된 셀만 리로드 혹은 추가시에는 테이블뷰에 추가된 셀을 append하는 방향은 어떠실까요?
- 현재 메모 리스트에 보이는 Date 포맷이 명세서의 포맷과 다른거 같습니다! 이 부분 확인 부탁드려요!

---

1. 이 부분은 해당 코드에 코멘트 남겼습니다!
2. 이 부분에 대해서는 공식문서 링크 한 번 남겨주시겠어요? 저도 한 번 보고 확인해보겠습니다!
3. 저는 해당 프로젝트를 구성할때 아이폰 기본 메모 어플을 기준으로 작업했었습니다. 기본 어플에서 메모를 추가하면 어떤식으로 저장이 되는지를 정리해서 그에 맞게 개발했었던 기억이 있는데요. 한 번 이 부분도 참고해보시면 좋을거 같습니다:) 
4. 이 부분은 코드상에 코멘트 남겨놨습니다. 전체적으로 잘 작성하신거 같습니다.

2021-09-07 14:59 UTC, wonhee009 commented on CloudNotes/CloudNotes/Controller/Delegate/MemoListDelegate.swift
> +}
`NSObject`로 제한을 건 이유가 있을까요?
현재로는 `AnyObject`로 제한을 걸어도 될거 같아서요!

2021-09-07 14:59 UTC, wonhee009 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +    }
이 메서드는 `viewDidLoad`보다 위에 위치해 있네요. 위에 배치한 이유가 있을까요?

2021-09-07 14:59 UTC, wonhee009 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +        self.tableView.reloadData()
memoList에 append될때 `didSet`에 의해서 테이블뷰 리로드가 될거 같은데요. 
`self.tableView.reloadData()`를 임의로 호출해주는 이유가 있을까요?

2021-09-07 14:59 UTC, wonhee009 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +        cell.dateLabel.text = DateFormatter.localizedString(from: Date(timeIntervalSince1970: memoList[indexPath.row].date), dateStyle: .long, timeStyle: .none)
```swift
class MemoListTableViewCell: UITableViewCell {
    func configure(_ memo: Memo) {
        titleLabel.text = memo.title
        ....
    }
}
```
이런식으로 cell의 UI 설정 책임을 cell이 하도록하는건 어떨까요?

2021-09-07 14:59 UTC, wonhee009 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +        self.delegate?.isFisrtCellSelection = true
이 부분이 샤피로가 궁금한점 #1에 해당하는거 같아요.
`isFisrtCellSelection`(isFirstCellSelection 오타로 이해했습니다...ㅎㅎ)으로 SplitVC의 Column을 지정해주는거로 이해했습니다.
> 사용자가 regular size에서 detail view를 보고 있을때 compact size로 변하게 된다면 그때는 detail view가 나타나야 한다고 생각

샤피로가 위와 같이 질문에 적어주셨는데요. 
Column이 .primary인지 .secondary를 구분하는 기준이 regular/compact size라고 이해했습니다.
그렇다면 regular/compact size를 활용해보는건 어떨까요?

(제가 잘못 이해하고 있다면 편하게 말씀해주세요:))

2021-09-07 14:59 UTC, wonhee009 commented on CloudNotes/CloudNotes/Controller/SplitViewController.swift
> +            isFisrtCellSelection = true
기존의 `isFisrtCellSelection`은 true일거 같은데 true로 지정해주는 이유가 있나요?

2021-09-07 14:59 UTC, wonhee009 commented on CloudNotes/CloudNotes/Controller/SplitViewController.swift
> +    }
`selectCell`, `addMemo` 메서드는 받는 파라미터도 동일하고 내부 로직도 동일한거로 보이는데요.
따로 정의한 이유가 있을까요?

현재 코드대로라면 메모 추가시 memoList에 새 메모가 append되므로 selectCell과 동일한 로직을 타도 무방할거 같아요.
그렇다면 `selectCell`보다는 `showMemo`혹은 `selectMemo`와 같은 메서드명도 괜찮아보입니다!

2021-09-07 14:59 UTC, wonhee009 commented on CloudNotes/CloudNotes/Model/Memo.swift
> +    var date: Double
date를 Double로 정의한 이유가 있을까요?
`TimeInterval`은 어떠신가요?

2021-09-07 14:59 UTC, wonhee009 commented on CloudNotes/CloudNotes/View/MemoListTableViewCell.swift
> +    private func addContentView() {
다른 VC에서는 addSubView()라는 메서드로 정의했던거로 기억하는데요!
여기서는 addContentView()로 네이밍한 이유가 있을까요?
전체적으로 프로젝트 네이밍 규칙이 있으면 이후의 사람들이 봤을때에도 이해?도가 높다고 생각합니다ㅎㅎ

2021-09-07 14:59 UTC, wonhee009 commented on CloudNotes/CloudNotes/View/MemoListTableViewCell.swift
> +            shortDiscriptionLabel.trailingAnchor.constraint(equalTo: self.trailingAnchor, constant: margin),
shortDiscriptionLabel에 마진을 주신거 같은데
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/30456206/132357453-45f21b2a-c2fe-4d62-bd92-95f146b9505a.png">
현재 마진이 잘 안 들어간거 같습니다! 이 부분 확인 부탁드려요🙏

2021-09-08 07:03 UTC, shapiro711 commented on CloudNotes/CloudNotes/Controller/Delegate/MemoListDelegate.swift
> +}
클래스에서 사용하기 위해서 우선 NSObject로 제한을 걸었었습니다...! 현재 상황에서는 라자냐의 말씀대로 AnyObject로 조금더 추상화된 제한을 걸어도 될것같아요!

2021-09-08 07:04 UTC, shapiro711 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +    }
앗 ... 보통 override 메서드를 위에 두려고 하는데 놓친 부분인것 같습니다

2021-09-08 07:06 UTC, shapiro711 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +        self.tableView.reloadData()
didset 부분을 생각하지 않은것 같습니다 ...! didset에서 reloadData() 가 되고있어서 불필요한 코드인것 같아요! 수정하겠습니다 :)

2021-09-08 07:13 UTC, shapiro711 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +        cell.dateLabel.text = DateFormatter.localizedString(from: Date(timeIntervalSince1970: memoList[indexPath.row].date), dateStyle: .long, timeStyle: .none)
프로잭트 할때마다 이부분이 계속 바뀌었는데요... View의 역할이 그려주는 부분만을 책임진다면 어떤 값이 들어갈지는 Controller가 정해주는것이 맞지 않을까? 하는 생각이 듭니다. 아니면 Controller가 View에게 데이터를 넘기고 나머지 책임을 다 View가 해야하는 것이 맞는지 고민이 됩니다. 

현재는 연산 로직이 없지만 만약 label의 그려지는 값이 연산을 통해 특정 값을 그려내야할때 책임을 어떻게 나누면 좋을지 라자냐의 생각이 궁금해요!!!

2021-09-08 07:14 UTC, shapiro711 commented on CloudNotes/CloudNotes/Controller/SplitViewController.swift
> +            isFisrtCellSelection = true
불필요한 코드인것 같아요... 수정하겠습니다!!!

2021-09-08 07:19 UTC, shapiro711 commented on CloudNotes/CloudNotes/Controller/SplitViewController.swift
> +    }
각각의 기능을 구현하다가 동일한 로직인것을 놓친것 같아요...! 라자냐의 말씀대로 네이밍을 수정하면서 메서드를 합치는 방향이 좋아보여요!!

2021-09-10 03:36 UTC, wonhee009 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +        cell.dateLabel.text = DateFormatter.localizedString(from: Date(timeIntervalSince1970: memoList[indexPath.row].date), dateStyle: .long, timeStyle: .none)
> label이 그려지는 값이 연산을 통해 정해진다.

라는 조건은 stock이 0일때는 '품절'을 보여주고 아닐때에는 갯수를 보여주는 상황을 말씀하시는걸까요?
우선 저는 이런 상황에서도 '품절'을 보여줄지 갯수를 보여줄지를 결정하는 것도 View의 역할이라고 생각합니다.
물론 이 부분은 개발자마다 View의 역할을 정의하는 방식이 다를 수 있다고 생각합니다.

그리고

2021-09-11 05:07 UTC, shapiro711 commented on CloudNotes/CloudNotes/Model/Memo.swift
> +    var date: Double
단순히 숫자로 이루어져있어서 double로 했었습니다... TimeInterval이 date를 나타내는데 더 좋은 자료형 같아요!

2021-09-11 05:08 UTC, shapiro711 commented on CloudNotes/CloudNotes/View/MemoListTableViewCell.swift
> +    private func addContentView() {
통일하는것이 라자냐 말씀대로 다른 사람들이 볼때나 나중에 제가 볼때 더 좋을것 같아요 :)

2021-09-11 07:16 UTC, wonhee009 commented on CloudNotes/CloudNotes/Model/Memo.swift
> +    var date: Double
[TimeInterval 공식문서](https://developer.apple.com/documentation/foundation/timeinterval)에서 TimeInterval을 확인해보면 Double의 Typealias임을 알 수 있어요.
`Double`이나 `TimeInterval`로 타입을 정의하는건 프로젝트에 차이는 없지만 좀 더 직관적일 수는 있을거 같아요!

2021-09-12 07:42 UTC, shapiro711 commented
@wonhee009
안녕하세요 라자냐!! 수정 부분이 너무 늦은것 같지만... 집중에서 더 해보겠습니다...!

말씀해주신 부분들을 토대로 수정을 해보았어요

## 수정한 내용
---
1. 컨벤션 수정
2. 불필요 코드 삭제 및 통합
3. 오토레이아웃 수정
4. DateFormatter 명세에 맞도록 변경
5. Cell이 책임을 가지도록 변경
6. 특정 Row의 데이터만 Reload 되도록 하게 변경

## 추가한 내용
---
1. 키보드가 올라옴에 따라 화면이 변동되도록 inset 구현

## 해결하지 못한 부분
---
1. CRUD 로직은 CoreData를 적용해보면서 실제 애플 메모앱과 비교해보며 다음 스탭에 적용해볼까 합니다... 괜찮을까요?

2021-09-14 06:30 UTC, wonhee009 requested changes
샤피로 코멘트 남겼습니다! 확인 부탁드려요.🙏
CRUD에 대한 부분은 스텝2에서 좀 더 정돈해도될거 같습니다.

2021-09-14 06:30 UTC, wonhee009 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +    }()
`lazy`로 정의한 이유가 있나요?

2021-09-14 06:30 UTC, wonhee009 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +    private func makeTest() {
`makeTest`보다 `makeSample` 같은 이름은 어떨까요?
현재 이름은 테스트를 위한거를 준비하는 메서드로 보여서요.

2021-09-14 06:30 UTC, wonhee009 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +        cell.configureCell(with: memoList[indexPath.row])
`cell.configure(with: memoList[indexPath.row])`여도 괜찮을거 같습니다!
앞에 cell이 있는데 뒤에도 cell이 나오는게 어색해보여서요.

2021-09-14 06:30 UTC, wonhee009 commented on CloudNotes/CloudNotes/View/MemoListTableViewCell.swift
> +    }
메모 리스트 셀의 description의 글자 수가 길어지면 `..`을 표시해주기 위한 메서드로 보이는데요.
오토레이아웃으로 해결가능할거 같은데요. 한 번 확인 부탁드립니다.🙏

2021-09-14 07:24 UTC, shapiro711 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +    }()
데이터를 변환시켜주는 기능을 하고 있어 메모리를 아껴보려고 사용했습니다...! 혹시 잘못된 사용법 일까요?

2021-09-14 07:25 UTC, shapiro711 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +        cell.configureCell(with: memoList[indexPath.row])
중복된 키워드가 사용되는 네이밍이었네요 ...! 수정하겠습니다~

2021-09-14 07:31 UTC, shapiro711 commented on CloudNotes/CloudNotes/View/MemoListTableViewCell.swift
> +    }
@wonhee009

2021-09-14 08:37 UTC, wonhee009 approved these changes

2021-09-14 08:37 UTC, merged