동기화 메모장 [Step1] Geon
yagom-academy/ios-cloud-notes pull request #57
Opened 2021-09-08 06:57 UTC by jgkim1008

@1Consumption 

안녕하세요~ 올라프😀
Step1을 다 구현 못했지만 너무 시간이 끌리는것 같아서 PR을 뒤늦게나마 보내봅니다.
부족한 부분이 많은것 같은것 같은데요~ 따끔한 지적 부탁드리겠습니다.
잘 부탁드립니다 :)

## 궁금한 내용
1. 원래는 `memoListTableView`에 `directionalLayoutMargins` 을 적용하여 `Cell`의 `leading` 에 `margin`을 만들어주고 싶었는데요. `layout`이 적용이 안된더라구요. 그래서 `MemoListVC`에 `view`에도 걸어보고 , `MemoCustomCell` 의 `contentView` 에도 걸어봤는데 적용이 안되었습니다..제가 이상한곳에 제약을 걸고 있는것인지 잘모르겠습니다.

2. `MemoCustomCell`에서는 `titleLabel` 로 `UILabel!` 옵셔널로 선언해두고 `override init`에서 `Cell`을 `init`할때 메서드를 추가하여 인스턴스도 생성되게끔 구현을 해놨습니다. `MemoListViewController` 에서는 `memoListTableView` 에서 `UITableView` 인스턴스를 바로 생성하게 해놨습니다. 인스턴스를 바로 생성하는것과 옵셔널로 선언해두고 `init`시 인스턴스를 생성하는것이 차이점 이나, 이득이 되는점?? 이런것을 잘 모르겠습니다.

3.  위 질문과 연관된 질문인데요. 스토리보드로 UI구성하였을떄는 아무생각 없이 `@IBOutlet weak var`로 `UI`프로퍼티를 선언했습니다. 하지만 코드로 UI를 작성하는 부분에서 `MemoListVC`에서 `memoListTableView`를 `let`으로 설정해도 문제가 없는것을 알게되었습니다. 그래서 스크럼중에 해당내용에 대해 이야기를 나누었는데요. `StoryBoard`에서 `UI`를 생성할떄는 `@IBOutlet 으로 선언된 UI 프로퍼티`가 `init`이 된 이후 `Interface Builder`와 매핑이 되어서 `let`이 아닌`var`로 선언되어야 한다고 이해를 한것 같습니다. 코드로 `UI`작성시에는 어떠한점을 염두해두고 `let`이나 `var`로 선언해야할지 감이 안오는것 같습니다..

2021-09-08 18:26 UTC, 1Consumption requested changes
안녕하세요~ 건
고생 많으셨습니다!
코드에서 고민한 흔적이 많이 보였어요!!
커밋도 대부분 한번에 하나의 역할만 하는 것 처럼 보였습니다!

그런데... gitignore 문제인지.. workspace와 podfile이 올라가있지 않아서 빌드가 안되네요ㅠㅠ 확인 부탁드릴게요.

나머지 궁금한 점에 대한 제 답변은 아래와 같아요.

## 궁금한 내용
> 1. 원래는 `memoListTableView`에 `directionalLayoutMargins` 을 적용하여 `Cell`의 `leading` 에 `margin`을 만들어주고 싶었는데요. `layout`이 적용이 안된더라구요. 그래서 `MemoListVC`에 `view`에도 걸어보고 , `MemoCustomCell` 의 `contentView` 에도 걸어봤는데 적용이 안되었습니다..제가 이상한곳에 제약을 걸고 있는것인지 잘모르겠습니다.

이부분은 빌드가 안되어서 확인하기 어렵네요...ㅠㅠ 디코로 얘기해보죠.

> 2. `MemoCustomCell`에서는 `titleLabel` 로 `UILabel!` 옵셔널로 선언해두고 `override init`에서 `Cell`을 `init`할때 메서드를 추가하여 인스턴스도 생성되게끔 구현을 해놨습니다. `MemoListViewController` 에서는 `memoListTableView` 에서 `UITableView` 인스턴스를 바로 생성하게 해놨습니다. 인스턴스를 바로 생성하는것과 옵셔널로 선언해두고 `init`시 인스턴스를 생성하는것이 차이점 이나, 이득이 되는점?? 이런것을 잘 모르겠습니다.

어차피 프로퍼티가 초기화 되고 super.init 메소드가 불리기 때문에 별 차이는 없어보인다고 생각이 됩니다. 그런데 아무리 확실한 상황이라도 되도록이면 강제언래핑은 지양하는게 좋아보여요.

> 3.  위 질문과 연관된 질문인데요. 스토리보드로 UI구성하였을떄는 아무생각 없이 `@IBOutlet weak var`로 `UI`프로퍼티를 선언했습니다. 하지만 코드로 UI를 작성하는 부분에서 `MemoListVC`에서 `memoListTableView`를 `let`으로 설정해도 문제가 없는것을 알게되었습니다. 그래서 스크럼중에 해당내용에 대해 이야기를 나누었는데요. `StoryBoard`에서 `UI`를 생성할떄는 `@IBOutlet 으로 선언된 UI 프로퍼티`가 `init`이 된 이후 `Interface Builder`와 매핑이 되어서 `let`이 아닌`var`로 선언되어야 한다고 이해를 한것 같습니다. 코드로 `UI`작성시에는 어떠한점을 염두해두고 `let`이나 `var`로 선언해야할지 감이 안오는것 같습니다..

weak var로 선언 하는 이유는 view hierarchy에서 view가 제거 되었을 때, 리테인 카운트가 정상적으로 0이 되는 방식을 유도했기 때문이라고 생각됩니다. strong으로 잡고 있으면 view hierarchy에서 view가 없어져도 리테인 카운트가 0이 아니라 메모리에 계속 남아있을 테니까요. 
그래서 코드로 선언할 때 strong으로 잡아두면 원하는 시점에 메모리에서 해제가 안될거같다는 생각이 들기도 합니다. 그럼에도 불구하고 의도적으로 strong으로 잡는 경우(tooltip이 닫혀도 다시 뜰 수 있는 경우)는 분명히 있는거 같습니다. 

저는 그동안 코드로 view를 짤 때 아무 생각 없이 항상 strong으로 잡았는데, 건이 해주신 질문 덕에 리서치를 해보게 되었고 상황에 맞게 써야겠다는 결론이 났어요. 감사합니당 🙇‍♂️🙇‍♂️🙇‍♂️

이 부분은 좀 더 얘기해보도록 해요...

2021-09-08 18:26 UTC, 1Consumption commented on CloudNotes/CloudNotes/Controller/MemoDetailViewController.swift
> +    let memoDeatailTextView = UITextView()
외부에서 몰라도 되는 프로퍼티 아닐까요?

2021-09-08 18:26 UTC, 1Consumption commented on CloudNotes/CloudNotes/Controller/MemoDetailViewController.swift
> +        self.view.addSubview(memoDeatailTextView)
self를 붙여주는 기준이 궁금합니다.

2021-09-08 18:26 UTC, 1Consumption commented on CloudNotes/CloudNotes/Controller/MemoDetailViewController.swift
> +    }
동작에 이름을 부여한게 보기 좋네요!

2021-09-08 18:26 UTC, 1Consumption commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +    let memoListTableView = UITableView()
여기도 외부에서 알아야하는 프로퍼티인가요?

2021-09-08 18:26 UTC, 1Consumption commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +        memoListTableView.register(MemoCustomCell.classForCoder(), forCellReuseIdentifier: MemoCustomCell.cellIdentifier)
이부분을 메소드로 빼고 이름을 부여하면 좋을거같아요

2021-09-08 18:26 UTC, 1Consumption commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +    }
selector에 메소드를 등록하기 위해 빈 구현을 만들어 놨다면, `TODO: - something` 주석을 달아서 어떤 작업을 할건지 보여주는게 좋아보여요.

2021-09-08 18:26 UTC, 1Consumption commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +    }
Result 타입을 사용하셨군요! 👍 다만 failure일 때 break여서 failure 여부를 알기 어렵다는 점이 아쉽습니다. 아래에 보니 custom error type을 만드셨던데, 그 타입을 적절히 활용해보면 어떨까요?

++ 매개변수 이름은 asset 보다는 assetName이 좀 더 맞아보여요

2021-09-08 18:26 UTC, 1Consumption commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +    }
DataFormatter를 따로 만들어서 viewController에서는 사용만 하는 구조였으면 좋겠습니다.

2021-09-08 18:26 UTC, 1Consumption commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +    }
여기서는 splitView에게 이벤트만 전달하는게 좋아보입니다.
구체적인 navigating 로직을 알고있는게 이 뷰컨트롤러의 역할이 아닐뿐더러, 결합도도 높아진다고 생각해요.

2021-09-08 18:26 UTC, 1Consumption commented on CloudNotes/CloudNotes/DataStructure/Memo.swift
> +    let lastModified: Double
바뀌지 않을 프로퍼티를 let으로 선언한거 좋습니다 👍

2021-09-08 18:26 UTC, 1Consumption commented on CloudNotes/CloudNotes/DataStructure/Memo.swift
> +    }
snake case를 camel case로 바꾸는 방법은 CodingKeys를 통해 명시적으로 key를 설정해주는 것도 있고, JsonDecoder의 `KeyDecodingStrategy` 값을 바꿔줘도 가능합니다! 
[`참고 링크`](https://developer.apple.com/documentation/foundation/jsondecoder/keydecodingstrategy/convertfromsnakecase)

2021-09-08 18:26 UTC, 1Consumption commented on CloudNotes/CloudNotes/Manager/ParsingManager.swift
> +    private let jsonDecoder = JSONDecoder()
은닉화 좋습니다~

2021-09-08 18:26 UTC, 1Consumption commented on CloudNotes/CloudNotes/View/MemoCustomCell.swift
> +    var veticalStackView: UIStackView!
여기는 익명 클로저로 바로 초기화 해줄 수 있을거같습니다. 그러면 var에 강제 언래핑을 해주지 않고 let으로 가능할듯 해요.

2021-09-08 18:26 UTC, 1Consumption commented on CloudNotes/CloudNotes/View/MemoCustomCell.swift
> +    static let cellIdentifier = "CustomCell"
하드코딩을 줄이려는 시도 좋습니다 👍

2021-09-09 11:14 UTC, jgkim1008 commented on CloudNotes/CloudNotes/Controller/MemoDetailViewController.swift
> +    let memoDeatailTextView = UITextView()
외부에서 몰라도 되는 프로퍼티인데 접근제어자가 빠진것 같네요!
수정해놓겠습니다~

2021-09-09 11:19 UTC, jgkim1008 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +    let memoListTableView = UITableView()
이것도 외부에서 따로 알필요가 없는 프로퍼티 라서 접근 제어자 추가 해놓을게요!

2021-09-09 11:36 UTC, jgkim1008 commented on CloudNotes/CloudNotes/Controller/MemoDetailViewController.swift
> +        self.view.addSubview(memoDeatailTextView)
따로 구현해주지 않아도 내부적으로 가지고 있는 프로퍼티의 경우 self를 붙이려고 했었는데, 코드를 보니 일관성이 없네요.
꼭있어야 될 필요도 없는데, 일관성을 위해서 제거하는 방향으로 생각이 드는것 같아요!!

2021-09-09 11:42 UTC, jgkim1008 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +        memoListTableView.register(MemoCustomCell.classForCoder(), forCellReuseIdentifier: MemoCustomCell.cellIdentifier)
navigationItem 을 셋팅해주는 메서드를 따로 구현할수 있을것 같은데요.
나머지는 메서드를 어떻게 분리를 해줄수 있을지 감이 잘 안오는것 같습니다..
단순히 한줄이라도 재사용성을 위해 분리를 해줘야 할까요??

2021-09-09 11:42 UTC, jgkim1008 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +    }
아하! 이런 방법이 있었군요.. 주석을 달아서 추후에 무엇을 할지 나타내는게 정말 좋은 방법인것 같습니다.
감사합니다!

2021-09-09 12:32 UTC, jgkim1008 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +    }
parsingError를 만들어놓고 제대로 활용을 못하고 있었군요. 해당 내용도 반영해놓겠습니다!
매개변수명도 assetName 으로 하는게 좀더 잘 읽히는것 같습니다.

2021-09-09 12:54 UTC, jgkim1008 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +    }
음..제가 잘 이해를 못한것 같습니다.
따로 만든다는 의미가 DataFormatter를 extension으로 확장해서 새로운 메서드를 만드는걸 말하시는걸까요??

2021-09-09 12:59 UTC, jgkim1008 commented on CloudNotes/CloudNotes/DataStructure/Memo.swift
> +    }
와..이런것도 있었군요!! 다음에 적용해봐야겠습니다!
감사합니다!

2021-09-09 13:38 UTC, jgkim1008 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +    }
이벤트만 전달해서 ViewController간 결합도를 낮추면 좋은것 같다고 생각이 들어서 해당 방법으로 구현해보겠습니다.

2021-09-11 14:56 UTC, jgkim1008 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +    }
https://github.com/yagom-academy/ios-cloud-notes/pull/57/commits/10400713d0272b23399171c8cd004df68082cdf4
Delegation 패턴 적용을 하여 결합도를 낮추고, 뷰컨트롤러의 역할을 다시 나누어봤습니다.
바꿔야될 부분이 많아서 커밋단위를 지키지는 못했습니다 ㅠㅜ

처음에는 textView의 변경이 일어나면 Cell에 내용이 저장되도록 resignFirstResponder()를 활용해 일정시간이 지나면 cell에 내용이 저장되게 구현을 해보았는데요.
textView에서 Cell로 responder가 바뀌어서 입력이 끊기는 현상이 있었습니다. 그래서 현재 방법으로 구현해보았습니다.
이렇게 되면 변화가 있을떄마다 Cell에 내용을 저장하기에 부하가 있을것 같은데요. 
Cell을 전부 초기화하는게 아닌 바뀐 부분만 초기화하고 있어서 이정도는 문제가 없을것 같다고 생각이 들었습니다.
아래 코드는 resignFirstResponder() 를 활용해 구현해봤던 코드입니다.

```swift
private func autoSave() {
        DispatchQueue.main.asyncAfter(deadline: .now() + 5.0) {
            self.memoDeatailTextView.resignFirstResponder()
        }
    }

extension MemoDetailViewController: UITextViewDelegate {
    func textViewDidEndEditing(_ textView: UITextView) {
        let lastIndex = Int(textView.text.components(separatedBy: linebreak).count - 1)
        let title = textView.text.components(separatedBy: linebreak)[.zero]
        let body = textView.text.components(separatedBy: linebreak)[1...lastIndex].joined(separator: "")
        let now = Date()
        delegate?.sendToListVC(data: Memo.init(title: title, body: body, lastModified: now))
    }
    
    func textViewDidChange(_ textView: UITextView) {
        autoSave()
    }
}
```

2021-09-11 18:54 UTC, jgkim1008 commented on CloudNotes/CloudNotes/View/MemoCustomCell.swift
> +    var veticalStackView: UIStackView!
Label들은 클로저로 생성했지만, stackView를 생성할떄는 Label들이 아직 초기화중이라서  stackView를 lazy closure로 생성해야 했습니다.

위 내용을 적용하다가 stackoverflow의 글을 하나 읽었는데, swift에서는 two-stage initialization 을 권장한다고 써있더라구요.
그래서 해당 링크에 있는 글을 읽었는데요. 링크는 아래에 첨부해놓겠습니다.
viewDidLoad에서 layout 을 변경하거나, view를 추가 또는 제거, 그리고 데이터를 가져오라는 문서를 보고 적용을 잠시 멈췄습니다.
제 생각엔 선언하면서 인스턴스를 만들고 viewDidLoad에서 해당 인스턴스에 대한 layout constraints이나 데이터를 적용하는 방향이 좋을것 같다고 생각이 들었습니다.🤔
이에 대해 올라프의 생각이 궁금합니다!!

![image](https://user-images.githubusercontent.com/52707151/132955798-49f00715-4d0e-4ed2-9519-1e0e062bd0e7.png)


lazy로 stackView적용해야하는 이유
https://stackoverflow.com/questions/60778106/why-cant-i-add-a-subview-to-my-stackview-without-making-the-stackview-a-lazy-va

viewDidload 문서 (Displaying Your Views at Runtime) 
https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/DefiningYourSubclass.html#//apple_ref/doc/uid/TP40007457-CH7-SW1

2021-09-14 11:37 UTC, 1Consumption commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +    }
debounce를 구현하고 싶었던건가요? 이건 단지 5초후에 동기화하는 코드인거같습니다.
마지막 입력이 들어오고 5초뒤에 저장하고싶다면 `DispatchWorkItem`을 활용해보세요.

2021-09-14 11:38 UTC, 1Consumption commented on CloudNotes/CloudNotes/View/MemoCustomCell.swift
> +    var veticalStackView: UIStackView!
네 저도 viewDidLoad에서 레이아웃을 잡아주고있어요. 그런데 생성과 레이아웃을 잡는거는 서로 다른거같은데요... 그래서 바로 초기화를 해도 될거같습니다.

2021-09-14 11:41 UTC, 1Consumption commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +    }
그리고 `sendToListVC()`, `sendToDetailVC()`라는 이름이 이상해보입니다. 어디로 보내는지를 알아야하나요? 그냥 이벤트를 전달만 할 뿐이라고 생각합니다.

++ VC 라는 약어보다는 ViewController를 사용하는게 가독성에 좋아보입니다. 약어를 쓰는 버릇을 들이면 나중에는 나만 알아볼 수 있는 약어를 쓸 수도 있거든요.

2021-09-14 11:42 UTC, merged

2021-09-14 11:42 UTC, 1Consumption commented
고생하셨습니다. 피드백 반영해주신 내용에 대한 코멘트는 다음 스텝에서 반영하셔도 좋고, 참고만 하셔도 좋습니다.