동기화 메모장 [Step1] Hosinging
yagom-academy/ios-cloud-notes pull request #62
Opened 2021-09-09 21:27 UTC by Hosinging

안녕하세요 쿠마~! @leejun6694
프로젝트 스텝1 진행에 필요한
스플릿뷰를 구현하는 방법들(스토리보드, 코드), 세그없이 화면간 데이터 전달, 코드로 UI구현 등 모두 공부가 충분히 필요하다고 판단해서 Step1-1조금 구현 후에 충분히 연습 프로젝트들을 만들어보며 익숙함의 정도를 올리고자 했습니다.

전일까지 애를 먹다가 해결된 부분도 있고, 명세서에는 나와있지 않지만 Step2에서 해결하고자하여 Step1에서는 해결을 시도하지 않은 부분(텍스트 뷰의 상단에서 조금 내려간 위치가 보이는 것)도 있습니다. 이점 참고해주시면 감사하겠습니다~!

---

궁금한점
> 1. SplieViewController의 viewcontroller에 배열 형태로 네비게이션에 임베드된 뷰들을 넣어주고, 화면전환에 해당 뷰를 푸시하려고 했던 적이나 해당 뷰에 접근해서 해당뷰의 속성에 접근하려고 아래와 같은 방법으로 코드를 작성해본적이 있는데요. 이렇게 했을 경우 navigationController.push....를 통해 푸시를 하고자 했을 때나 해당 뷰컨트롤러의 delegate속성에 접근하려고 하면 정상적으로 동작하지 않고, error타입이라고 나왔던 것 같습니다. 어떤 부분을 놓친 것인지 궁금합니다.
```swift
if let vc = splitViewController.viewcontrollers.first.children.first as? 해당 뷰 컨트롤러 타입 { ... }

if let vc = splieViewController.viewcontrollers.last.children.first as? 해당 뷰 컨트롤러 타입{ ... }
```

> 2. 현재 코드에서는 지워서 정확히 기억이 나지 않지만, 기본적으로 splieViewController의 displaymode를 oneBesideSecondary로 설정해뒀지만, 일부 기기가 landscape모드가 됐을 때 해당 displayMode를 따르지 않았던 것 같습니다. 여기에서는 어떤 부분을 놓친 것인지 궁금합니다.

> 3. 바로 위의 질문에서 이어지는 내용인데요. Size Class에 따라 splitview의 displaymode를 변경해주는 것과UITraitCollection.current.userInterfaceIdiom이 .phone일 때, .pad일 때로 분기해서 splieView의 displaymode를 분기해주는 것이 가능할 것이라고 생각했지만, 현재는 따로 분기를 해두지 않고 기본 설정한 displaymode대로만 실행되게 되어있어서 일부 기기의 landscape에서는 masterView만 보여지는 상황인데요. 이 부분은 위의 두 가지 방법 중에 선택적으로 구현 가능할까요? 아니면 SizeClass에 따라 분기되도록 해야할까요?

> 4. 그 외에 아직 구조적으로 짜기보다는 생각나는대로 짜는것, 짜다보니 이어지는 것 같으니 커밋 단위가 길어졌던 것 등 문제될 만한 부분들이 계속 있었던 것 같습니다. 이런 부분들에 대해서 도움될 수 있는 말, 키워드, 링크 등 뭐든 남겨주시면 감사하겠습니다.

2021-09-10 14:19 UTC, leejun6694 requested changes
Hosinging, 구현하느라 고생 많으셨습니다.
아래 리뷰 내용 확인 부탁드립니다 : )

2021-09-10 14:19 UTC, leejun6694 commented on CloudNotes/CloudNotes/Controllers/ContentViewController.swift
> +        }
if 와 else 내 코드가 동일한 것으로 보입니다...!
확인 부탁드려요

2021-09-10 14:19 UTC, leejun6694 commented on CloudNotes/CloudNotes/Controllers/ContentViewController.swift
> +    var textView: UITextView?
외부 class 에서 쓰이지 않는다면 access control 이 필요할 것 같습니다~!!

2021-09-10 14:19 UTC, leejun6694 commented on CloudNotes/CloudNotes/Controllers/ContentViewController.swift
> +    var textView: UITextView?
이 `textView` 는 쓰여지고 있는 것일까요...?

2021-09-10 14:19 UTC, leejun6694 commented on CloudNotes/CloudNotes/Controllers/ContentViewController.swift
> +    func applyAdaptiveLayoutByDevice(textView: () -> UITextView) {
textView 를 생성하고 설정해주는 구조가 저는 조금 생소하네요.
혹시 참고한 내용이 있으실까요?

2021-09-10 14:19 UTC, leejun6694 commented on CloudNotes/CloudNotes/Controllers/MemoListTableViewController.swift
> +private let reusableIdentifier = "cell"
global 로 선언해야하는 변수일지 궁금합니다..!

2021-09-10 14:19 UTC, leejun6694 commented on CloudNotes/CloudNotes/Controllers/MemoListTableViewController.swift
> +private var parsedDatas = [SampleData]()
전역 변수로 선언하신 이유가 궁금합니다.
(여러 곳에서 쓰이는 데이터의 경우, singleton 등의 방법으로 handling 이 가능합니다.

2021-09-10 14:19 UTC, leejun6694 commented on CloudNotes/CloudNotes/Controllers/MemoListTableViewController.swift
> +       let f = DateFormatter()
임시로, 간단하게 선언하는 변수여도 항상 네이밍은 신경써주면 좋을 것 같아요 : )

2021-09-10 14:19 UTC, leejun6694 commented on CloudNotes/CloudNotes/Controllers/MemoListTableViewController.swift
> +        print("tableView did Load")
p/r 을 올릴 땐, 불필요한 코드는 제거 부탁드립니다.

2021-09-10 14:19 UTC, leejun6694 commented on CloudNotes/CloudNotes/Controllers/MemoListTableViewController.swift
> +    func decoding() {
UIViewController 의 method 로 선언하신 이유가 궁금합니다...!

2021-09-10 14:19 UTC, leejun6694 commented on CloudNotes/CloudNotes/Views/TableCell.swift
> +class TableCell: UITableViewCell {
네이밍이 좀 더 명확하면 좋겠네요 @.@

2021-09-10 14:19 UTC, leejun6694 commented on CloudNotes/CloudNotes/Controllers/MemoListTableViewController.swift
> +        let contentView = ContentViewController()
contentView 가 아닌 contentViewController 로 명확하게 선언되면 좋겠네요!

2021-09-10 14:19 UTC, leejun6694 commented on CloudNotes/CloudNotes/Controllers/MemoListTableViewController.swift
> +        delegate?.didTapMemo(self, memo: body)
동작이 달라지는 코드들 중간엔 줄바꿈이 있으면 더 가독성이 올라갈 것 같습니다 ㅎㅎ

2021-09-10 14:19 UTC, leejun6694 commented on CloudNotes/CloudNotes/Controllers/SplitViewController.swift
> +    static let shared = SplitViewController()
어떤 구조로 구현된 것인지 궁금합니다...!?

2021-09-10 14:19 UTC, leejun6694 commented on CloudNotes/CloudNotes/Controllers/SplitViewController.swift
> +            delegate = self
들여쓰기가 잘못 되어 있네요~~!

2021-09-10 14:19 UTC, leejun6694 commented on CloudNotes/CloudNotes/Extension/Extension+UIView.swift
> +    func setConstraintEqualToAnchor(view: UIView) {
자주 쓰일 수 있는 method 를 UIView method 로 만들어주셨군요 👍

2021-09-10 14:19 UTC, leejun6694 commented on CloudNotes/CloudNotes/Views/TableCell.swift
> +       let label = UILabel()
들여쓰기 확인 부탁드립니다.

2021-09-10 14:19 UTC, leejun6694 commented on CloudNotes/CloudNotes/Views/TableCell.swift
> +    private func cellComponentConfigure() {
하나의 method 에서 너무 많은 동작이 진행되는 것 같습니다.
한번 구분을 해볼까요?

2021-09-10 14:19 UTC, leejun6694 commented on CloudNotes/CloudNotes/Views/TableCell.swift
> +
불필요한 줄바꿈입니다.

2021-09-11 00:58 UTC, Hosinging commented on CloudNotes/CloudNotes/Controllers/ContentViewController.swift
> +        }
else 블록 내 폰트 사이즈 조정했습니다.

2021-09-11 01:00 UTC, Hosinging commented on CloudNotes/CloudNotes/Controllers/ContentViewController.swift
> +    var textView: UITextView?
access controller 추가해줬습니다. 
MemoListTableViewController에서 delegate메서드 호출 시 textView가 사용되고 있습니다.

2021-09-11 01:04 UTC, Hosinging commented on CloudNotes/CloudNotes/Controllers/ContentViewController.swift
> +    func applyAdaptiveLayoutByDevice(textView: () -> UITextView) {
스토리보드에서 vary for trait으로 기기에 따라 다르게 표현되게 할 수 있는 부분을 코드로 작성하게되어서 고민을 해보다가 이렇게 해보면 조금 쉽게 적용가능하지 않을까 싶어서 함수를 기능단위로 분류하는 것을 고려하면서 생각 나는대로 적용해봤는데요. 혹시 문제가 되는 부분이나 개선 하면 좋을 부분이 있을까요?ㅠ

2021-09-11 01:08 UTC, Hosinging commented on CloudNotes/CloudNotes/Controllers/MemoListTableViewController.swift
> +        print("tableView did Load")
네 확인했습니다. 마지막에 제거하고 보낸 다는 것이 깜빡했네요ㅠㅠ

2021-09-11 01:10 UTC, Hosinging commented on CloudNotes/CloudNotes/Views/TableCell.swift
> +
네 확인했습니다.

2021-09-11 01:15 UTC, Hosinging commented on CloudNotes/CloudNotes/Views/TableCell.swift
> +    private func cellComponentConfigure() {
셀에 컴포넌트를 추가해주는 configureCellComponent()와 컴포넌트들에 제약을 추가해주는 addConstraintCellComponent()로 분리해봤습니다.

2021-09-11 01:19 UTC, Hosinging commented on CloudNotes/CloudNotes/Extension/Extension+UIView.swift
> +    func setConstraintEqualToAnchor(view: UIView) {
일단 계속 쓰일만한 것이 이렇게 제약을 추가하는 형태일 것 같아서 만들어봤는데요. 혹시 쿠마라면 이 프로젝트에서 제약 추가 관련한 메서드를 익스텐션으로 만드신다면 어떤 기능의 메서드를 어떤 형태로 만들어 보실 것 같으신지 궁금합니다.

2021-09-11 01:20 UTC, Hosinging commented on CloudNotes/CloudNotes/Views/TableCell.swift
> +       let label = UILabel()
네 확인했습니다.

2021-09-11 01:20 UTC, Hosinging commented on CloudNotes/CloudNotes/Controllers/SplitViewController.swift
> +            delegate = self
네 확인했습니다.

2021-09-11 01:23 UTC, Hosinging commented on CloudNotes/CloudNotes/Views/TableCell.swift
> +class TableCell: UITableViewCell {
MemoListTableViewCell이라는 네이밍으로 수정해봤습니다.

2021-09-11 01:36 UTC, Hosinging commented on CloudNotes/CloudNotes/Controllers/MemoListTableViewController.swift
> +private let reusableIdentifier = "cell"
해당 부분 TableViewController의 프로퍼티로 변경했습니다.

2021-09-11 01:41 UTC, Hosinging commented on CloudNotes/CloudNotes/Controllers/MemoListTableViewController.swift
> +private var parsedDatas = [SampleData]()
처음에는 다른 뷰에서 쓰지 않을까 하는 생각에 글로벌로 만들어뒀었는데 해당 부분 테이블뷰 컨트롤러 프로퍼티로 변경해줬습니다.

2021-09-11 01:42 UTC, Hosinging commented on CloudNotes/CloudNotes/Controllers/MemoListTableViewController.swift
> +       let f = DateFormatter()
네 확인했습니다. 다음과 같이 변경해줬습니다. 
formatter -> dateFormatter
f -> formatter

2021-09-11 01:44 UTC, Hosinging commented on CloudNotes/CloudNotes/Controllers/MemoListTableViewController.swift
> +    func decoding() {
처음에는 다른 뷰에서도 쓰지 않을까 하는 생각에 MemoListTableViewController의 메서드로 뒀다가 상위 클래스의 익스텐션으로 추가해줬었는데요. 다른 뷰에서 사용되고 있지 않아서 해당 부분 MemoListTableViewController의 메서드로 변경해줬습니다.

2021-09-11 01:49 UTC, Hosinging commented on CloudNotes/CloudNotes/Controllers/MemoListTableViewController.swift
> +        let contentView = ContentViewController()
네 확인했습니다. 해당 내용으로 변경했습니다.

2021-09-11 01:57 UTC, Hosinging commented on CloudNotes/CloudNotes/Controllers/MemoListTableViewController.swift
> +        delegate?.didTapMemo(self, memo: body)
아래와 같이 세 파트로 나눠 줄바꿈 해봤습니다.
* 파싱한 데이터를 바인딩해주는 부분과 바인딩된 것을 델리게이트 메서드 인자로 넣어주는 부분 
* UINavigationViewController와 ContentViewController의 인스턴스를 생성하고, 인스턴스의 프로퍼티에 바인딩해주는 부분
* 네비게이션 컨트롤러를 통해 DetailViewController가 보여지게 메서드 호출하는 부분

2021-09-11 02:03 UTC, Hosinging commented on CloudNotes/CloudNotes/Controllers/SplitViewController.swift
> +    static let shared = SplitViewController()
스플릿뷰 컨트롤러를 SceneDelegate외에 다른 컨트롤러에서도 사용되야만 될 것 같아서 Singleton으로 만들고 사용을 했었는데 현재는 SceneDelegate외에 사용되는 부분이 없고, splitViewController라는 속성을 통해서 스플릿뷰 컨트롤러에 접근이 가능함을 확인했어서 해당 내용 제거해줬습니다.

2021-09-12 11:26 UTC, leejun6694 approved these changes
리뷰 내용 반영 감사합니다~~!

2021-09-12 11:26 UTC, leejun6694 commented on CloudNotes/CloudNotes/Controllers/ContentViewController.swift
> +    func applyAdaptiveLayoutByDevice(textView: () -> UITextView) {
textView 는 보통 위와 같은 구조로 만들게 될 경우, lazy var 를 통해 생성하거나 property 로 갖게되는 경우를 많이 접했던 것 같습니다...!

2021-09-12 11:26 UTC, leejun6694 commented on CloudNotes/CloudNotes/Controllers/ContentViewController.swift
> +    var textView: UITextView?
textView 가 어디에서 생성되고 있는 것일까요..?

2021-09-12 11:26 UTC, leejun6694 commented on CloudNotes/CloudNotes/Extension/Extension+UIView.swift
> +    func setConstraintEqualToAnchor(view: UIView) {
충분히 잘 만들어주신 것 같습니다. 
다만, parameter 의 `view` 가 헷갈릴 수 있는 여지가 있을 것 같네요. superview 등의 다른 이름으로 교체해서, 현재 view 와는 명확히 구분되도록 구현할 수 있습니다 : )

2021-09-12 15:03 UTC, leejun6694 commented
회의실에서 말씀드렸던 것처럼 에러가 발생했던 내용은 당시 코드나 상황을 남겨두면 좋을 것 같습니다.
놓치기 쉬운 부분이지만...! 네이밍, 코딩 컨벤션을 조금만 더 신경써주시면 좋겠습니다~~!
감사합니다 : )

2021-09-12 15:03 UTC, merged