동기화 메모장 [Step2] Geon
yagom-academy/ios-cloud-notes pull request #71
Opened 2021-09-17 08:54 UTC by jgkim1008

@1Consumption 

안녕하세요 올라프!
완성되지 않은 스텝2PR을 보내게됬습니다 ㅠㅜ
PR을 보낼까 말까 고민을 정말 많이했는데요..
오류도 많고 CRUD도 제대로 구현이 안되어있는데 어디서부터 손봐야될지 모르겠어서 PR을 보냅니다.
이상한 코드가 많을것 같은데 미리 양해를 구합니다 ㅠㅜ
Step1 PR리뷰를 받고 정말 많이 도움이 되었고 더 깊게 생각을 하게 되었습니다. 3주동안 정말 감사했습니다~ 🙇

---
### 오류 사항 및 궁금한 내용

1. 현재 Cell에 수정이 있을떄 Cell이 새로 만들어지고 해당 Cell에 내용이 업데이트 되는 오류 사항이 있습니다. 또한 Cell이 계속 생성되는 현상도 습니다.
![CloudNotes](https://user-images.githubusercontent.com/52707151/133748421-2bf94d01-bc17-4e93-ba74-30b74be6c622.gif)
    - 제가 생각했던 방향은 indexPath를 통해 터치된 Cell을 알아내고 변경된 text의 내용을 다시 Cell에게 보내어 설정해주면 된다고 생각했습니다.
  기존에 Json을 파싱한 데이터를 가지고 있을때는 동작이 원할하게 되었는데, CoreData를 적용하니 Cell을 새로 생성하고 있는 오류가 발생하고 있습니다.

2.  새로운 Memo를 생성했을떄도 동일한 문제가 발생하고 있습니다.현재 새로운 Memo를 생성시에 cell을 클릭했을떄와 동일한 delegate를 통해 메세지를 전달하게 하고 있고,  textView에서 textViewDidChange메소드를 통해서 다시 값을 업데이트를 하고 있는 구조입니다.위 내용에서 update가 잘안되서 이것도 영향이 끼치는것 같습니다.

    - 새로운 메모를 생성 과 업데이트를 다른 메서드로 분리하는게 좋을까요??

    - 새로운 메모를 생성했을떄에는 indexPath가 없으니 tableView에 최상단에 Cell이 생기게 하였습니다. 그래서 IndexPath를 (0,0)으로 설정하고 tableView를 Reload하면 문제가 없을거라고 생각했는데요. 이로인해 indexPath가 이전과 값이 달라져있을것 같습니다. indexPath를 sync를 해야될것 같다는 생각이 들었는데 sync를 어떻게 해야될지 감이 잘 안잡히는것 같습니다.

3. 위 방법말고 현재의 MemoEntity를 전달하는 좋은 방법이 없을까요? 제가 CoreData의 이해가 부족해서 제대로 활용하지 못하고 있다는 생각이 들었습니다. 

4. 기존에 delegate 패턴을 통해 ViewController간의 역할을 분리해놨는데 coreData를 싱글턴으로 적용하고 있어서 역할의 분리가 애매해진것 같습니다. 

    - `MemoSplitViewController`에서 CoreData를 관리하게 하고 delegate패턴을 적용해서 `MemoListViewController`, `MemoListTextViewController`에서 값이 필요할떄마다 `MemoSplitViewController`에 요청을 하게 바꿔보았는데요. 역할이 명확하게 구분되는 장점이 있는데, 매번마다 delegate 패턴을 통해 데이터를 요청한다는게 코드가 복잡하게 되어 다시 롤백을 했는데요.
delegate 패턴을 적재적소에 적용하는것은 아직도 잘 모르겠습니다.

2021-09-19 11:54 UTC, 1Consumption requested changes
안녕하세요 건~ 고생 많으셨습니다.

구현에 너무 급급하셨는지 코드가 정리되지 않은채로 PR을 보낸거같아 조금 아쉽습니다.

그래도 고민한 흔적이 많이 보여서 좋았습니다.



대표적으로 주신 질문에 대한 답변은 아래에 있고, 코드를 보며 생겼던 궁금한 점이나 피드백은 코멘트를 통해 남겼습니다.

> 현재 Cell에 수정이 있을떄 Cell이 새로 만들어지고 해당 Cell에 내용이 업데이트 되는 오류 사항이 있습니다. 또한 Cell이 계속 생성되는 현상도 있습니다.
> ![CloudNotes](https://user-images.githubusercontent.com/52707151/133748421-2bf94d01-bc17-4e93-ba74-30b74be6c622.gif)
>
> 제가 생각했던 방향은 indexPath를 통해 터치된 Cell을 알아내고 변경된 text의 내용을 다시 Cell에게 보내어 설정해주면 된다고 생각했습니다.
> 기존에 Json을 파싱한 데이터를 가지고 있을때는 동작이 원할하게 되었는데, CoreData를 적용하니 Cell을 새로 생성하고 있는 오류가 발생하고 있습니다.
>
> 새로운 Memo를 생성했을떄도 동일한 문제가 발생하고 있습니다.현재 새로운 Memo를 생성시에 cell을 클릭했을떄와 동일한 delegate를 통해 메세지를 전달하게 하고 있고,  textView에서 textViewDidChange메소드를 통해서 다시 값을 업데이트를 하고 있는 구조입니다.위 내용에서 update가 잘안되서 이것도 영향이 끼치는것 같습니다.
>
> 새로운 메모를 생성 과 업데이트를 다른 메서드로 분리하는게 좋을까요??
>
> 새로운 메모를 생성했을떄에는 indexPath가 없으니 tableView에 최상단에 Cell이 생기게 하였습니다. 그래서 IndexPath를 (0,0)으로 설정하고 tableView를 Reload하면 문제가 없을거라고 생각했는데요. 이로인해 indexPath가 이전과 값이 달라져있을것 같습니다. indexPath를 sync를 해야될것 같다는 생각이 들었는데 sync를 어떻게 해야될지 감이 잘 안잡히는것 같습니다.

1, 2번 질문은 당연한 동작이라고 생각합니다. 

``` swift
func textViewDidChange(_ textView: UITextView) {
    configureDebounce { [self] in
        // do something..
        if lastIndex > firstIndex {
            let currentEntity = CoreDataManager.shared.createMemo(title: title, body: body, lastModifiedDate: now)
            delegate?.textViewModify(at: currentEntity)
        } else {
            let currentEntity = CoreDataManager.shared.createMemo(title: title, body: PlaceHolder.body, lastModifiedDate: now)
            delegate?.textViewModify(at: currentEntity)
        }
    }
}
```

여기서 변경사항이 발생하면 매번 메모를 만들어주고 있네요... 그리고 fetchMemo 메소드를 통해 변경사항을 땡겨오고요. 

그리고 listViewController의 dataSource는 CoreDataManager의 memoList와 관련이 있네요.

 

> 위 방법말고 현재의 MemoEntity를 전달하는 좋은 방법이 없을까요? 제가 CoreData의 이해가 부족해서 제대로 활용하지 못하고 있다는 생각이 들었습니다. 

CoreData를 사용하기 위해 순서대로 진행되어야 하는(메모를 저장하고 fetch한다거나) 이런 작업들을 CoreDataManager 내부에서 래핑하고, 사용하는 곳에서는 하나의 인터페이스를 통해 접근하는게 좋아보입니다. MemoEntity를 만드는 작업도 CoreDataManager 내부에서 해줘야할거같고요... 이러면 전달할 값은 title과 body, indexPath 정도가 되겠네요.



> 기존에 delegate 패턴을 통해 ViewController간의 역할을 분리해놨는데 coreData를 싱글턴으로 적용하고 있어서 역할의 분리가 애매해진것 같습니다. 
>
> `MemoSplitViewController`에서 CoreData를 관리하게 하고 delegate패턴을 적용해서 `MemoListViewController`, `MemoListTextViewController`에서 값이 필요할떄마다 `MemoSplitViewController`에 요청을 하게 바꿔보았는데요. 역할이 명확하게 구분되는 장점이 있는데, 매번마다 delegate 패턴을 통해 데이터를 요청한다는게 코드가 복잡하게 되어 다시 롤백을 했는데요.
> delegate 패턴을 적재적소에 적용하는것은 아직도 잘 모르겠습니다.

이벤트 전달만 잘해준다면 싱글톤일 이유가 전혀 없습니다. 지금은 하위 뷰에서 CoreData와 관련된 동작을 하려고하니 어디서든 접근할 수 있는 싱글톤이 된거같습니다. 이를 SplitViewController에서 CoreDataManager 인스턴스를 가지고 로직을 담당하는게 어떨까요? 하위 뷰컨에는 변경사항만 뿌려주면 괜찮을거같습니다.

2021-09-19 11:54 UTC, 1Consumption commented on CloudNotes/CloudNotes/Controller/MemoDetailViewController.swift
> +    private let firstIndex = 1
이 두개는 꼭 필요한 상수인가요? 억지로 만든 느낌이 드네요

2021-09-19 11:54 UTC, 1Consumption commented on CloudNotes/CloudNotes/Controller/MemoDetailViewController.swift
> +        CoreDataManager.shared.fetchMemo()
by보다는 with이 어떨까요?

2021-09-19 11:54 UTC, 1Consumption commented on CloudNotes/CloudNotes/Controller/MemoDetailViewController.swift
> +        CoreDataManager.shared.fetchMemo()
하위 뷰컨트롤러에서는 이벤트만 보내는 역할이라면, 여기서 코어데이터매니저에 접근할 이유가 없습니다. 상위뷰컨에서 판단을 담당하고, 하위 뷰컨에서는 로직 실행만 하면 되니까요. 그렇다면 코어데이터 매니저도 싱글톤일 이유가 없겠죠.

2021-09-19 11:54 UTC, 1Consumption commented on CloudNotes/CloudNotes/Controller/MemoDetailViewController.swift
> +    }
꼭 main thread에서 수행되어야하는 작업인가요?

2021-09-19 11:54 UTC, 1Consumption commented on CloudNotes/CloudNotes/Controller/MemoDetailViewController.swift
> +        configureDebounce { [self] in
self를 weak가 아니라 strong하게 캡쳐한 이유가 있나요?

2021-09-19 11:54 UTC, 1Consumption commented on CloudNotes/CloudNotes/Controller/MemoDetailViewController.swift
> +        }
at은 보통 위치(index, indexPath)를 나타날때 쓰는거 같아요. 따라서 여기서는 적절하지 못한거같습니다.

2021-09-19 11:54 UTC, 1Consumption commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +
weak로 선언하지 않은 이유가 있나요?

2021-09-19 11:54 UTC, 1Consumption commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
> +        }
여기서 self를 캡쳐한 이유가 있나요?

2021-09-19 11:54 UTC, 1Consumption commented on CloudNotes/CloudNotes/Enumeration/PlaceHolder.swift
> +}
좋습니다 👍

2021-09-19 11:54 UTC, 1Consumption commented on CloudNotes/CloudNotes/Extension/UIAlertController+Extension.swift
> +        }
이 코드가 필요한 이유는 뭔가요?

2021-09-19 11:54 UTC, 1Consumption commented on CloudNotes/CloudNotes/Manager/CoreDataManager.swift
> +    }
이 context는 어떤 thread에 바인딩 되나요? main일까요 background일까요?

2021-09-19 11:54 UTC, 1Consumption commented on CloudNotes/CloudNotes/Manager/CoreDataManager.swift
> +    }()
internal lazy var인 이유가 있나요?

++ fatalError는 앱이 죽으니 다른 에러처리를 고민해보세요.

2021-09-19 11:54 UTC, 1Consumption commented on CloudNotes/CloudNotes/Manager/CoreDataManager.swift
> +    static let shared = CoreDataManager()
splitViewController에서 해당 객체를 가지고 데이터를 받아오고, 하위 뷰에는 데이터만 전달해준다면 싱글톤이 필요없지 않을까요?

2021-09-19 11:54 UTC, 1Consumption commented on CloudNotes/CloudNotes/Manager/CoreDataManager.swift
> +        let context = persistentContainer.viewContext
이미 mainContext라는 computed property를 통해서 viewContext에 접근하고 있으니 해당 프로퍼티를 사용하는게 좋아보입니다.

2021-09-19 11:54 UTC, 1Consumption commented on CloudNotes/CloudNotes/Manager/CoreDataManager.swift
> +        }
여기도 context를 저장하지 못하면 앱이 죽네요. 커스텀 에러를 사용하는 객체에게 넘겨주고, 에러처리를 하는게 좋아보입니다.

2021-09-19 11:54 UTC, 1Consumption commented on CloudNotes/CloudNotes/Manager/CoreDataManager.swift
> +    }
이 동작들은 모두 하나의 queue에서 동작한다는 보장이 있나요? context의 작업은 하나의 queue에서 수행되어야한다고 알고있는데요,
https://developer.apple.com/documentation/coredata/nsmanagedobjectcontext/1506578-perform
이 문서를 참고해보세요.

2021-09-19 11:54 UTC, 1Consumption commented on CloudNotes/CloudNotes/Manager/DateFormattingManager.swift
> +        return dateFormatter.string(for: date)
여기는 왜 from에서 for로 바꾼건가요?

2021-09-19 11:54 UTC, 1Consumption commented on CloudNotes/CloudNotes/View/MemoCustomCell.swift
> +    }()
외부에서 몰라도 되는 프로퍼티 같습니다.

2021-09-21 08:10 UTC, closed without merging

2021-09-21 10:44 UTC, jgkim1008 commented on CloudNotes/CloudNotes/Controller/MemoDetailViewController.swift
> +    }
현재 workItem이 textField.text에 접근하고 있고,
델리게이트 패턴을 통해 MemoListViewController에서 Cell의재사용 및 값을 셋팅해주고 있습니다. 
textField.text에 접근하는것과, UITableViewCell이 UIView를 상속받아서 재사용할떄는 main thread에서 처리해야될것으로 생각하였습니다. 

아래는 globalQueue로 구현하였을떄 나타난 오류를 캡처해놨던 내용입니다!
![Untitled (2)](https://user-images.githubusercontent.com/52707151/134154448-8cba5cad-2db3-4343-b16e-7ccdcd480806.png)
![Untitled (1)](https://user-images.githubusercontent.com/52707151/134154453-02a979d6-4e4b-4e43-b3a4-e985d7fe4f48.png)

2021-09-21 11:27 UTC, jgkim1008 commented on CloudNotes/CloudNotes/Extension/UIAlertController+Extension.swift
> +        }
아이패드의 경우 화면분할로 두개의 앱을 동시에 사용할수 있기에 아래쪽 전체로 나오는 형태의 ActionSheet를 사용못하는걸로 찾아봤습니다. 그래서 아이패드의 경우 UIModalPresentaionPopOver로 보여주고 있고, 이때 barButtonItem 또는 팝업에 대한 위치를 설정해줘야 됩니다. 저는 아이패드의 경우 팝업에 대한 위치를 설정하는 코드를 구현하였습니다.

2021-09-21 12:30 UTC, jgkim1008 commented on CloudNotes/CloudNotes/Manager/DateFormattingManager.swift
> +        return dateFormatter.string(for: date)
dateFormatter.String(for:)는 반환값이 `String?` 이고, Entity attribute 인 `lastModifiedDate` 의 데이터 타입은 `Date?` 입니다.
`Label.text`는 강제 언래핑을 하기에, 옵셔널 체이닝으로 효율적으로 처리할수 있을것 같아서 `dateFormatter.String(for:)`로 변경하였습니다.

2021-09-21 12:42 UTC, jgkim1008 commented on CloudNotes/CloudNotes/Controller/MemoDetailViewController.swift
> +    private let firstIndex = 1
firstIndex의 경우 전체 문장의 갯수를 구할때와, body에서 join으로 title을 제외한 문장들을 합칠떄 쓰고 있는데요
이떄 매직넘버를 대체할만한것을 찾지 못해서 그랬던것 같습니다. 그러다 보니 억지로 만들어지는 느낌이 생긴것 같아요ㅠㅜ
linebreak의 경우 중복으로 사용하고 있어서 상수로 설정하였습니다.