동기화 메모장 [STEP1] 호댕, 요한, 아샌
yagom-academy/ios-cloud-notes pull request #75
Opened 2022-02-08 08:54 UTC by ICS-Asan

안녕하세요. 라이언! @ryan-son 🦁!
아샌(@ICS-Asan), 호댕(@yanghojoon), 요한(@YohanBlessYou)입니다. 

이번 프로젝트 첫 PR 올립니다! 잘 부탁드려요!! 

감사합니다!!

## 💻    주요 구현 내용

### < 다크모드 대응>

요구조건에 다크모드에 대응하는 부분이 있어서 각 label의 색상을 변경할 때 `UIColor`의 `label`을 사용하였습니다.

일반적으로 사용하는 `white`, `black`등의 색상을 사용하면 다크모드로 변경시에도 해당 색상을 유지하여 각 디스플레이 모드에 대응할 수 없었습니다.

기존 label을 생성할 때의 default로 설정된 색상은 다크모드를 지원하기에 그에 해당하는 색상을 찾아 이렇게 색을 설정하였습니다.

## ❓   질문할 내용

### < Cell이 선택 되었을 때의 View 처리 방법>

기본적으로 cell이 선택되면 단순히 회색으로 칠해지는데 심미적이지 못한 것 같아 아래와 같이 systemblue-Background + white-Text 조합으로 변경해보았습니다. 

구현방법을 찾다보니 여러가지 방법이 있었고, 그 중 `selectedBackgroundView` 와 `setSelected()` 를 override하는 방식을 사용했습니다. 

이런 selected cell control은 굉장히 자주 쓰이므로 나름의 Best practice 혹은 전형적인 방식이 있을지도 모르겠다는 생각이 들었습니다 

질문드리고 싶은 점은 Ryan은 이런 경우 어떻게 구현하시는지, 구현하실지 궁금합니다!

![Simulator Screen Recording - iPad Pro (9 7-inch) - 2022-02-08 at 17 50 22](https://user-images.githubusercontent.com/91048487/152951788-1d51ad86-b8d4-47b5-ba55-7b8e11b74918.gif)

```swift
override func setSelected(_ selected: Bool, animated: Bool) {
    super.setSelected(selected, animated: animated)
    if selected {
        titleLabel.textColor = .white
        dateLabel.textColor = .white
        previewLabel.textColor = .white
    } else {
        titleLabel.textColor = .label
        dateLabel.textColor = .label
        previewLabel.textColor = .systemGray
    }
}

private func configureSelectedBackgroundView() {
    let backgroundView = UIView()
    backgroundView.layer.cornerRadius = 10
    backgroundView.backgroundColor = .systemBlue
    selectedBackgroundView = backgroundView
}
```

### < 초기화면 NavigationBarBackButtonTitle>

`ListViewController`에서 `configureNavigationBar()`를 viewDidLoad에서 호출할 경우 초기화면이 `MemoViewController`가 되면서 NavigationBar의 back 버튼이 `back`으로 표시되는 문제가 있었습니다. 

이 때 초기화면이 `MemoViewController`로 `ListViewController`가 보이지 않게 되어 `ListViewController`의 View Life Cycle 관련 메서드들이 호출되지 않았기 때문으로 그 이유를 추측해봤습니다. 

현재는 `ListViewController`의 init에서 NavigationTitle을 설정하도록 변경하여 문제를 해결했는데, 저희가 생각한 원인이 맞을까요?

![Simulator Screen Recording - iPad Pro (9 7-inch) - 2022-02-08 at 17 46 08](https://user-images.githubusercontent.com/91048487/152951743-48ab9824-4af8-4013-a9f8-8c9ddf2fa72f.gif)

```swift
convenience init(memos: [Memo]) {
    self.init(nibName: nil, bundle: nil)
    self.memos = memos
    configureNavigationBar()
}

private func configureNavigationBar() {
    navigationItem.title = navigationTitle
    navigationItem.rightBarButtonItem = UIBarButtonItem()
    navigationItem.rightBarButtonItem?.image = UIImage(systemName: navigationButtonImageName)
}
```

2022-02-09 08:40 UTC, ryan-son requested changes
요한, 호댕, 아샌, 고생 많으셨습니다! iPad용 애플리케이션 개발과 `UISplitView` 활용에 생소한 내용이 많았을텐데 진도가 굉장히 빠르네요! 👏

구현하신 내용이 굉장히 구조화가 잘 되어 있어 별도의 주석 없이도 잘 읽혔습니다. 커밋도 제목과 메시지에 언급된 내용과 동일하게 수행되어 문제가 있을 때도 원하는 시점으로 잘 돌아갈 수 있을 것이라 판단되네요. 👍

##  < Cell이 선택 되었을 때의 View 처리 방법>

여러분이 구현한 방식이 best practice라고 생각합니다. 실제로 이 방식을 이용하는 경우가 가장 많고, 의도한 동작을 가장 정확히 수행하기도 합니다. 애플이 이렇게 사용하게 할 목적으로 만든 메서드니까 어떻게 보면 당연하기도 하네요.

## < 초기화면 NavigationBarBackButtonTitle>

현재 상태에서는 `configureNavigationBar()`의 호출 시점을 `viewDidLoad()`로 변경해도 말씀하신 문제가 발생하지 않네요. 자세한 내용은 회의실에서 이야기 해보시죠. 편하신 시간 알려주시면 참석하겠습니다!

제 의견과 논의해볼 거리, 공부해보면 좋을 내용을 코드 개별 코멘트를 통해 말씀 드렸으니 천천히 살펴보세요~ 이해가 되지 않거나 어디서 어떻게 시작해야할지 모르겠다는 경우에는 말씀해주시기 바랍니다. 화이팅!

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/.swiftlint.yml
> + - trailing_whitespace
아래와 같이 작성하면 빈 라인에 대한 whitespace 규칙만 삭제할 수도 있습니다~ 자세한 내용은 [SwiftLint 공식 페이지](https://github.com/realm/SwiftLint)와 [SwiftLint Docs](https://realm.github.io/SwiftLint/trailing_whitespace.html)를 통해 확인하실 수 있어요~

```
trailing_whitespace:
  ignores_empty_lines: true
```

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/CloudNotes/Model/Memo.swift
> +    let lastModified: TimeInterval
`Double`의 별칭 타입인 `TimeInterval`을 사용하셨네요. 다른 개발자에게 이 프로퍼티의 용도를 명확하게 드러낼 수 있겠어요! 👍

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/CloudNotes/Model/Memo.swift
> +    }
여러분들과 논의해보고 싶은 주제가 있어요. 아래 내용을 읽어보시고 이야기 나누어봐요! (디스코드, 리뷰 코멘트 모두 가능)

- [How expensive is DateFormatter - Sarunw](https://sarunw.com/posts/how-expensive-is-dateformatter/)
- [How Expensive is DateFormatter? - Matthias Deuschl](https://deuschl.net/swift/how-expensive-is-dateformatter/)
- [25 iOS App Performance Tips & Tricks - Reuse Expensive Objects - Raywenderlich.com](https://www.raywenderlich.com/2752-25-ios-app-performance-tips-tricks#reuseobjects)
- [Is caching a NSDateformatter application-wide good idea? - Stack Overflow](https://stackoverflow.com/questions/27321993/is-caching-a-nsdateformatter-application-wide-good-idea)

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/CloudNotes/Model/Memo.swift
> +    }
이미 아시겠지만, 키 값이 snake_case와 camelCase의 차이만 있다면 `CodingKeys`를 작성하지 않고 `JSONDecoder`의 [`keyDecodingStrategy`](https://developer.apple.com/documentation/foundation/jsondecoder/keydecodingstrategy)를 설정하는 방식으로도 대응할 수 있어요!

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/CloudNotes/SceneDelegate.swift
>      }
현재 scene을 이용해서 window 설정을 따로 하지 않아도 화면이 정상적으로 표현되는건 storyboard 파일이 남아있기 때문이에요. 프로젝트 또는 info.plist의 deployment info에서 확인할 수 있는 main interface가 스토리보드로 설정되어 있기 때문이죠. 하지만 스토리보드를 활용하지 않는 프로젝트라면 결국에는 스토리보드 파일 자체가 없는것이 혼선을 방지하는데 유리하다고 생각해요. 스토리보드 파일을 제거하고, window를 이용해서 화면이 표현될 수 있도록 만들어봅시다! 여러가지 개념에 대해 더 배울 수 있는 기회가 될거에요.

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/CloudNotes/SceneDelegate.swift
>          (UIApplication.shared.delegate as? AppDelegate)?.saveContext()
실패하지 않을 구문이지만, 다운캐스팅과 같은 구문은 향후 디버깅의 편의를 위해서 변수로 받아두었다 사용하는 것도 좋겠어요.

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/CloudNotes/SceneDelegate.swift
>          // Save changes in the application's managed object context when the application transitions to the background.
불필요한 주석은 하나씩 제거해볼까요?

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/CloudNotes/View/ListTableViewCell.swift
> +final class ListTableViewCell: UITableViewCell {
현재 프로젝트는 기획과 디자인이 모두 결정되어 이 이외의 리스트 형식 셀은 없다고 판단할 수 있지만, 앞으로 어떤 내용이 추가될지 모르는 프로덕트에는 제너럴한 형식의 네이밍을 사용하면 앞으로 같은 형식의 디자인이 추가되면 대응하기 어려울 것 같아요. 번거롭지만, 이름만으로 용처를 파악할 수 있도록 명확한 이름을 지어보는 것도 좋겠어요.

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/CloudNotes/View/ListTableViewCell.swift
> +    static let identifier = String(describing: self)
좋은 접근 방식이네요. 셀을 등록하고 dequeue할 때 `reuseIdentifier`라는 요소를 고려하지 않게끔 만들 수 있다면 더 좋을 것 같아요!

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/CloudNotes/View/ListTableViewCell.swift
> +    }()
초기화 시점에 요구사항을 세팅하는 방식, 저도 선호합니다 👍
현업에서는 [Then](https://github.com/devxoul/Then)과 같은 라이브러리를 활용하는 경우도 있으니 이런 구문을 어떤 방식으로 작성할 수 있는지, 라이브러리가 어떻게 만들어져있는지 알아보는 것도 재미 있을거에요~ (파일 1 개짜리 100 줄도 안되는 라이브러리인데 스타가 3700 개!)

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/CloudNotes/View/ListTableViewCell.swift
> +    }
구현하지 않은 인터페이스는 available [attribute](https://docs.swift.org/swift-book/ReferenceManual/Attributes.html)를 통해 이용할 수 없게끔 만들어줄 수 있으니 참고하세요~
추가로, 이러한 attribute를 이용해서 deprecated, 해당 인터페이스가 곧 이용하지 못하게(또는 지원 종료) 되거나 이름이 변경되었음 (renamed) 사실을 사용자에게 알려줄 수 있습니다!

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/CloudNotes/View/ListTableViewCell.swift
> +        cellStackView.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -5).isActive = true
모두 contentView와 cellStackView의 관계인데 작성된 위치가 반대인 경우도 있네요. 어떤 내용을 의도하신건가요~?

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/CloudNotes/ViewController/ListViewController.swift
> +        navigationItem.rightBarButtonItem?.image = UIImage(systemName: navigationButtonImageName)
여러분이 Asset을 불러오는 방식을 정리해봤어요.
```swift
UIImage(systemName: navigationButtonImageName) // MemoViewController.swift
NSDataAsset(name: "sample") // MainSplitViewController.swift
```
여러분들이 이미 아시고 계시듯이 이미지나 컬러, 샘플 JSON과 같은 Asset을 안전하게 불러다 사용할 수 있는 방법은 **등록한 Asset의 이름을 정확하게 작성하는 것**이에요. 이름을 ViewController에서 정의하고 사용하시는 모습에서 안전하게 Asset을 이용하고 싶다라는 의지가 보입니다.

이 ViewController 이외에도 앞으로 여러 UI 요소를 작성할 때 등록해둔 다양한 Asset을 이용할 일이 있을거에요. 그 때마다 매 번 이런 반복되는 작업을 자동화하기 위해 현업에서는 [SwiftGen](https://github.com/SwiftGen/SwiftGen)이나 [R.swift](https://github.com/mac-cain13/R.swift)와 같은 방식을 사용하기도 합니다 (지금 적용하거나 공부해볼 필요는 전혀 없어요).

지금 생각해보면 좋은 내용은, 다양한 위치에서 등록한 Asset을 불러다 사용하려면 어떤 형식으로 만들어보면 좋을까라고 생각해요. 예를 들면 아래와 같은 방식으로 어디에서든지 불러다 사용할 수 있으면 좋지 않을까요? 만들어본 이후에 향후 이런 툴들을 이용할 때 지금 만든 방식과 어떻게 다른지 비교하는 재미도 있을 것 같아요.
```swift
Asset.plus.image // UIImage(systemName: "plus")
Asset.memos.data
Asset.ellipsisCircle.image
```

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/CloudNotes/ViewController/ListViewController.swift
> +        return listCell
지금까지는 return 구문 전에 공백 라인이 없었는데, 여기는 의도된 공백인가요? 어떤 의미가 있나요?

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/CloudNotes/ViewController/MainSplitViewController.swift
> +    private var memos: [Memo] = []
지금의 설계에서도 이번 프로젝트를 수행하는데 문제는 없을 것 같아요. 그래서 아래 의견은 참고하셔도 되고, 동의하지 않으시면 그대로 진행하셔도 무방합니다.

개인적인 의견으로는 `SplitViewController`는 `primary` 및 `secondary` `ViewController`들의 화면 이동이나 데이터 전달과 같은 역할만 수행하는게 어떨까하는 생각이 드네요. 연관이 있는 두 화면이라고는 하지만 ViewController가 다른 ViewController에 소유해서 동작하는 방식은 ViewController 간에 강한 결합이 발생한다는 측면에서 흔하지 않은 것 같습니다 (물론 방식을 변경해도 `SplitViewController`와 `ViewController`들 간에 결합이 발생합니다만, 결합도를 낮춘다는 개념을 이해하면 향후 이 문제를 해결할 `Coordinator` 패턴을 이해하는데도 도움이 될겁니다).

정리 (100% 개인 의견이니 따를 필요는 없습니다)
- `MainSplitViewController`
  - 화면 이동 / 데이터 이동 처리
- `ListViewController`
  - 메모 로드 작업
  - 화면 이동 필요 시 `SplitViewController`를 통해 데이터 전달

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/CloudNotes/ViewController/MainSplitViewController.swift
> +        setViewController(memoViewController, for: .secondary)
`setViewController(_:for:)` 메서드는 iOS 14.0부터 이용 가능하네요. 현업에서는 이제 iOS 13.0으로 전환되는 추세인데, 이전에는 어떤 방식을 이용했을까요? 공부만 해보시고, 변경하지는 않으셔도 괜찮습니다~

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/CloudNotes/ViewController/MemoViewController.swift
> +    private func configureMemoViewAutoLayout() {
이 이름도 명확해서 마음에 드네요. 저는 layout을 제외한 모든 내용이 유추 가능할 것 같아서 `layout()`이라는 이름도 괜찮아보이기도 하네요. 변경하라는 의미는 전혀 아닙니다!!

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/Podfile
> +  pod 'SwiftLint'
이미 아시듯이, `SwiftLint`는 CocoaPods을 활용해서 프로젝트 개별로 사용할 수도 있고, 프로젝트에 참여하는 개발자들 모두 사용하는 기기에 설치해서 사용할 수도 있어요. 그래도 사용하는 버전은 맞추는게 좋아보이는데, 어떻게 통일시킬 수 있을까요?

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/Podfile
> +  use_frameworks!
`use_frameworks!`의 의미는 무엇인가요? 이후에 여유가 생긴다면 static/dynamic library, static/dynamic framework의 의미와 장단점을 공부해보시는걸 추천드립니다~

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/Podfile
> +    inherit! :search_paths
이건 무슨 의미인가요~?

2022-02-09 08:40 UTC, ryan-son commented on CloudNotes/Podfile
> +target 'CloudNotes' do
`CocoaPods` 의존성 관리 도구를 사용해 보셨으니, 작동 원리에 대해서도 궁금하실거라 생각합니다. 시간이 허락한다면 아래 내용들을 공부해보는 것도 좋을거에요.

1. `pod install`을 수행할 때 어떤 일이 일어나나요? [참고자료](https://www.objc.io/issues/6-build-tools/cocoapods-under-the-hood/)
1-1. `CocoaPods`는 지정한 라이브러리를 어떻게 가져오나요? [참고자료](https://stackoverflow.com/questions/18917137/how-does-cocoapods-work)

2022-02-09 08:52 UTC, ryan-son commented on CloudNotes/CloudNotes/Model/Memo.swift
> +    }
`autoUpdatingCurrent`와 `current`는 어떤 점이 다른지 알아봅시다!

2022-02-10 04:58 UTC, ICS-Asan commented on CloudNotes/Podfile
> +  pod 'SwiftLint'
podfile내부에 
```
target 'CloudNotes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint', '0.45.1'
```
다음과 같이 작성해서 버전을 맞출 수 있는 것을 확인했습니다! 감사합니다!

2022-02-10 05:15 UTC, ICS-Asan commented on CloudNotes/Podfile
> +  use_frameworks!
저희가 찾아본바로는 cocoapod이 static library/framework를 지원하지 않는데 이것을 명시해놓기 위해 `use_frameworks!` 를 사용한다고 확인했습니다.
저희가 이해한 것이 맞을까요?

2022-02-10 05:32 UTC, ICS-Asan commented on CloudNotes/Podfile
> +    inherit! :search_paths
간단하게 `inherit! : search_path`은 부모의 검색 경로만 상속을 의미한다는 것은 알았지만 이게 정확히 어떤 의미인지 이해하기가 어렵습니다.
이 부분을 이해하기 위해선 사전에 어떤 개념들을 알고 있으면 좋을까요?

2022-02-10 05:52 UTC, yanghojoon commented on CloudNotes/CloudNotes/Model/Memo.swift
> +    }
autoUpdatingCurrent의 경우 공식문서에 따르면 user의 Timezone 설정이 바뀔 경우 더이상 시스템의 timezone을 따르지 않게 되지만, current의 경우 시스템의 설정을 계속해서 따르는 차이가 있다고 찾아봤습니다. 

여기서 user의 TimeZone 설정 변경이 Apple ID의 지역 설정이 바뀌는 경우를 말하는 걸까요?

2022-02-10 05:55 UTC, yanghojoon commented on CloudNotes/CloudNotes/Model/Memo.swift
> +    }
현재는 `keyDecodingStrategy`를 사용할 수 있으나 추후 JSON이 추가되거나 key값이 변경된다면 오히려 대응이 어렵다고 판단되어 기존 코드 그대로 놔뒀습니다!

2022-02-10 06:12 UTC, yanghojoon commented on CloudNotes/CloudNotes/SceneDelegate.swift
>      }
말씀해주신대로 스토리파일을 제거하고 SceneDelegate에서 window를 생성하여 화면에 표시되도록 수정했습니다.

2022-02-10 06:25 UTC, YohanBlessYou commented on CloudNotes/CloudNotes/SceneDelegate.swift
>          (UIApplication.shared.delegate as? AppDelegate)?.saveContext()
말씀해주신대로 LLDB에서 찍어볼 수 있도록`delegate`라는 상수를 따로 할당해주었습니다

2022-02-10 06:28 UTC, YohanBlessYou commented on CloudNotes/CloudNotes/SceneDelegate.swift
>          // Save changes in the application's managed object context when the application transitions to the background.
불필요한 주석과 사용되지 않는 delegate 메서드는 제거해주었습니다

2022-02-10 06:32 UTC, YohanBlessYou commented on CloudNotes/CloudNotes/ViewController/ListViewController.swift
> +        return listCell
return 전에는 공백라인을 주도록 합의했었지만, 다른 곳에는 프로퍼티 초기화 구문이라 인지를 못 했던 것 같습니다. 전부 공백라인이 들어가도록 통일해주었습니다

2022-02-10 06:40 UTC, ICS-Asan commented on CloudNotes/CloudNotes/View/ListTableViewCell.swift
> +final class ListTableViewCell: UITableViewCell {
전체적으로 `MemoListViewController`, `MemoContentViewController`, `MemoListTableViewCell`로 네이밍을 수정했습니다!

2022-02-10 06:49 UTC, ICS-Asan commented on CloudNotes/CloudNotes/View/ListTableViewCell.swift
> +    static let identifier = String(describing: self)
저희는 identifier를 사용하지 않고 cell을 등록하고 재사용하는 방법을 의도하신 것이라고 이해를 했습니다!
tableViewCell을 사용할 때 identifier가 없이는 불가능한 것으로 알고 있습니다.
혹시 저희가 의도를 잘못 이해한 것일까요?

2022-02-10 07:14 UTC, ICS-Asan commented on CloudNotes/CloudNotes/View/ListTableViewCell.swift
> +    }
available attribute에 대해 간단히 살펴봤지만 어떠한 의도로 말씀을 해주신건지 이해를 하지 못했습니다🥲
혹시 조금 더 상세하게 알려주실 수 있으실까요??🙏

2022-02-10 07:18 UTC, yanghojoon commented on CloudNotes/CloudNotes/View/ListTableViewCell.swift
> +        cellStackView.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -5).isActive = true
코드를 수정하다보니 미처 고려를 하지 못했네요. 😵‍💫
StackView를 기준으로 통일하여 수정 완료했습니다!

2022-02-10 07:37 UTC, YohanBlessYou commented on CloudNotes/CloudNotes/ViewController/ListViewController.swift
> +        navigationItem.rightBarButtonItem?.image = UIImage(systemName: navigationButtonImageName)
말씀해주신 방향이 깔끔하고 관리도 쉬울 것 같아서 `Assets` 타입을 만들어 타입 프로퍼티로 갖도록 구현하였습니다. UIImage, NSDataAsset이 class라 여러 곳에서 공유하는 상황에서, 어느 한 곳에서의 수정이 의도치 않게 전체에서 바뀌는 일이 없도록 연산 프로퍼티로 구현하였습니다

2022-02-10 08:04 UTC, ICS-Asan commented on CloudNotes/CloudNotes/ViewController/MainSplitViewController.swift
> +    private var memos: [Memo] = []
`loadMemos` 메서드의 위치를 `MemoListViewController`로 이동하여 메모 로드 작업을 해당 뷰컨에서 하도록 수정하였습니다.
그리고 `MainSplitViewController`에 `updateMemoContentsView`메서드를 생성하여 `MemoContentViewController`로 데이터를 전달할 수 있도록 구현하였습니다.
이 과정에서 화면 전환부도 `updateMemoContentsView`메서드 내부에 위치를 변경하였습니다.

2022-02-10 08:17 UTC, ICS-Asan commented on CloudNotes/CloudNotes/ViewController/MainSplitViewController.swift
> +        setViewController(memoViewController, for: .secondary)
찾아보니까 `self.viewControllers = [VC1, VC2]`의 형식으로 사용하는 것을 알게 되었습니다!

2022-02-13 16:01 UTC, ryan-son commented on CloudNotes/CloudNotes/Protocol/CellManagable.swift
> +extension UITableView: CellManagable { }
👍

2022-02-13 16:01 UTC, ryan-son commented on CloudNotes/CloudNotes/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
`window`의 개념이 잘 이해가 되시던가요~?

2022-02-13 16:01 UTC, ryan-son commented on CloudNotes/CloudNotes/View/MemoListTableViewCell.swift
> +    static let identifier = String(describing: self)
Cell 타입도 어느 프로토콜을 채택하면 이런 identifier를 제공할 수 있게끔 프로토콜 기본구현 형식으로 만들어둔다면 활용성이 높을 것 같아요~!

2022-02-13 16:01 UTC, ryan-son commented on CloudNotes/CloudNotes/ViewController/MainSplitViewController.swift
> +    }
1. 이 메서드는 어디에서도 호출하고 있지 않으니 `gestureRecognizer`도 등록되지 않을 것 같아요.
2. 메서드 이름과 수행하는 동작이 다른 것 같아요.
3. 이 메서드를 호출하여 `gestureRecognizer`를 `view`에 추가하여도 원하는대로 키보드 dismiss가 일어나지 않는 이유는 뭘까요~?

2022-02-13 16:01 UTC, ryan-son commented on CloudNotes/CloudNotes/ViewController/MainSplitViewController.swift
> +        guard let keyboardFrame = sender.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue,
`UIResponder.keyboardFrameEndUserInfoKey` 키 값에 대한 userInfo value는 바로 `CGRect` 타입으로도 타입 캐스팅 가능한 것으로 알고 있어요. 이 내용은 [이 글](https://seizze.github.io/2019/11/17/iOS에서-키보드에-동적인-스크롤뷰-만들기.html)의 중반부인 **Notification Center를 통해 키보드 알림 받기** 섹션을 참고하세요.

`NSValue` 형식으로 다운캐스팅하여 사용했을 때 장점은 무엇인가요?

2022-02-13 16:01 UTC, ryan-son commented on CloudNotes/Podfile
> +  use_frameworks!
이틀 전 디스코드에서 이야기 나누었듯이 `CocoaPods`도 1.5.0 버전부터 정식으로 static library를 지원합니다. 그 때 말씀드린 내용과 부가적인 내용들에 대해 시간이 되면 차근차근 알아보는 것도 많은 도움이 될 거에요~! 의존성 관리를 할 때 어떤 형태로 둘 것인가를 결정할 수 있을겁니다! 이 내용에 대해서는 [이 블로그](http://minsone.github.io)에서 깊게 다룬 내용들이 있으니 참고하세요~

- [CocoaPods 1.5.0 — Swift Static Libraries - CocoaPods](https://blog.cocoapods.org/CocoaPods-1.5.0/)

2022-02-13 16:01 UTC, ryan-son commented on CloudNotes/Podfile
> +    inherit! :search_paths
이 내용도 이야기 나눈 내용이죠? [공식 페이지](https://guides.cocoapods.org/syntax/podfile.html#inherit_bang)를 통해 정의에 대해 알 수 있고, `inherit!` 구문 이후에 나온 내용은 부모의 특정 build setting을 따를 것인가를 나타낸다고 보시면 되겠습니다.

2022-02-13 16:01 UTC, ryan-son commented on CloudNotes/CloudNotes/Model/Memo.swift
> +    }
[이 글](https://radu-ionut-dan.medium.com/ios-calendars-current-vs-autoupdatingcurrent-3581635684ad)을 함께 살펴보며 예상되는 결과에 대해서는 이야기해보았죠? 실험 결과는 어떻던가요~?

2022-02-13 16:02 UTC, ryan-son commented on CloudNotes/CloudNotes/Model/Memo.swift
> +    }
좋은 판단입니다!

2022-02-13 16:02 UTC, ryan-son commented on CloudNotes/CloudNotes/SceneDelegate.swift
>      }
왜 이런 작업을 해야하는지 라인 바이 라인으로 이해해두시면 좋겠습니다~

2022-02-13 16:04 UTC, ryan-son commented on CloudNotes/CloudNotes/View/ListTableViewCell.swift
> +    static let identifier = String(describing: self)
셀마다 이와 같은 구문을 반복적으로 작성하지 않고, 프로토콜 채택만으로 identifier 타입 프로퍼티를 제공한다면 반복되는 작업을 줄일 수 있을 것 같네요~

2022-02-13 16:05 UTC, ryan-son commented on CloudNotes/CloudNotes/View/ListTableViewCell.swift
> +    }
이야기 나누고 훌륭하게 적용하셨네요!

2022-02-13 16:07 UTC, ryan-son commented on CloudNotes/CloudNotes/ViewController/ListViewController.swift
> +        navigationItem.rightBarButtonItem?.image = UIImage(systemName: navigationButtonImageName)
Thread-safety까지 고려하셨군요~ 그런데 Asset을 읽어오기는 하여도 수정하는 경우는 어떤 경우인가요?

2022-02-13 16:08 UTC, ryan-son commented on CloudNotes/Podfile
> +  pod 'SwiftLint'
버전 명시 방법에 대해서는 더 공부해보셨나요~?

2022-02-13 16:11 UTC, ryan-son approved these changes
아샌, 호댕, 요한! 이야기를 나누고 거의 모든 사항들이 코드에 반영되었네요. 빠른 성장이 정말 놀랍습니다! 😊

추가 코멘트는 코드에 개별 코멘트로 달아두었으니 참고하세요~

STEP 1 수행 고생 많으셨고, 다음 스텝에서 뵙겠습니다! 화이팅! 💪

2022-02-13 16:11 UTC, merged

2022-02-14 05:22 UTC, ICS-Asan commented on CloudNotes/CloudNotes/Model/Memo.swift
> +    }
시간이 부족해서 아직 실험은 하지 못했습니다 ㅠㅠ
실험하고 나면 다시 말씀드리겠습니다!!

2022-02-14 05:28 UTC, ICS-Asan commented on CloudNotes/CloudNotes/View/ListTableViewCell.swift
> +    static let identifier = String(describing: self)
현재 구현한 프로토콜을 사용하면 따로 identifier가 필요없을 것 같다고 생각됩니다.

2022-02-14 05:37 UTC, ICS-Asan commented on CloudNotes/CloudNotes/ViewController/ListViewController.swift
> +        navigationItem.rightBarButtonItem?.image = UIImage(systemName: navigationButtonImageName)
Thread-safety를 고려했다기 보다는 참조타입의 오류상황을 대비하고자 이렇게 구현했습니다.
저희가 예상한 오류는 다음과 같은 상황입니다.

```swift
// AViewController
let aaa = Assets.plusImage
// BViewController
let bbb = Assets.plusImage

// ex)
bbb?.size = CGSize(width: 15, height: 15)
```
위와 같이 두군데서 사용되는 경우에 `bbb`의 프로퍼티를 변경하면 `aaa`도 같이 변경되는 문제를 고려했습니다!!

2022-02-14 05:41 UTC, ICS-Asan commented on CloudNotes/Podfile
> +  pod 'SwiftLint'
부등호를 사용하여 버전을 설정하는 방법과 `~>`를 통해 특정 버전 이상 특정 버전 미만인 범위를 설정하는 방법이 있는 것을 알아보았습니다!

2022-02-14 05:46 UTC, ICS-Asan commented on CloudNotes/CloudNotes/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
아직 완벽하게 이해하지는 못했습니다 ㅠㅠ
어떤 느낌이다 라고 생각하고 활용은 해봤는데 정확히 설명하지는 못하는 단계입니다😅
추후에 window/scene에 대해 더 자세히 알아보겠습니다

2022-02-14 07:05 UTC, ICS-Asan commented on CloudNotes/CloudNotes/ViewController/MainSplitViewController.swift
> +    }
키보드를 숨기기 위해 구현을 해놓았는데 사용하는 것을 깜빡했습니다.
라이언 말씀대로 실제로 사용을 해보니 적용이 되지 않았습니다. 
splitView가 제스쳐를 가져가서 아래 테이블 뷰가 터치가 인식되지 않는 문제가 발생했습니다.
아직은 완벽한 해결책을 찾지 못해 우선은 테이블 뷰 스크롤 시 키보드가 내려가도록 처리해 두었습니다.

2022-02-14 07:06 UTC, ICS-Asan commented on CloudNotes/CloudNotes/ViewController/MainSplitViewController.swift
> +        guard let keyboardFrame = sender.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue,
키보드에 대해서는 깊게 공부해보지 않았습니다 ㅠㅠ
여러 예제들을 통해 어떻게 해야 동작하는지 정도만 알고 사용했습니다.
추후에 시간 여유가 있을 때 조금 더 자세히 공부해보도록 하겠습니다