동기화 메모장 [STEP 1] 고사리, 숲재
yagom-academy/ios-cloud-notes pull request #78
Opened 2022-02-10 00:30 UTC by FIIIIN

안녕하세요 찰리! @kcharliek STEP1 PR작성하여 보내드립니다. 프로젝트 시작 전 미팅이 구현과 공부에 큰 도움이 된 것 같습니다 감사합니다!

3주간 잘 부탁드립니다 🙇‍♀️🙇🏻

## 0. 구현내용

- SplitViewController를 사용한 화면 구현
    - 좌측 PrimaryView : TableViewController, 메모의 리스트를 dataSource로 정보 표현
    - 우측 SecondaryView : TextView를 사용하여 개별 메모를 dataSource로 정보 표현
- SplitViewController가 `NoteDataSource` 프로토콜을 채택한 `JSONDataSourceProvider` 타입의 객체를 소유하고 있으며, 해당 객체를 이용하여 DataSource의 저장과 매니징을 할 수 있음
- PrimaryView의 메모 리스트에서 메모를 선택하면 SecondaryView에 상세 메모가 보여지고, 수정 가능
- SecondaryView에서의 메모 수정은 PirmaryView의 메모리스트에도 실시간으로 영향을 미치도록 구현
- 기타 요구사항에 명시되어있지 않은 상세 구현부분은 iPadOS기본 메모앱을 참고하여 진행했습니다.

## 1. 고민했던 점

### 1-1. DataSourceProvider를 위한 Protocol

- 이후 적용될 CoreData에 대응하기 위해 JSONData 외의 타입도 포괄하는 Protocol을 구현하였습니다.
    - 향후 기능 업데이트에 따라 `delete()` , `search()`, `save()`등이 추가될 예정입니다.

### 1-2. 지역 설정에 따른 날짜의 포맷 변경

- 사용자의 첫 번째 `PreferredLanguage`를 토대로 지역화를 진행했습니다.
    - 사용자에게 익숙한 문화권의 양식을 제공한다는 점에 의의가 있다고 판단하였습니다.
    - `Current`로 언어 설정을 가져올 경우, 앱 설정의 언어 환경을 가져오는 점을 확인했습니다.

### 1-3. TextView의 Text를 메모 객체로 변환하는 방법

- 텍스트 뷰가 수정되었을 때 실시간으로 PrimaryVC에도 반영하기 위해서 아래와 같이 TextViewDelegate메서드를 사용하여 구현하였습니다.
- 제목과 내용을 분리하는 기준을 줄바꿈이 있을 경우 줄바꿈으로 구분, 그 외의 경우는 제목 100자까지로 제한하였습니다.

```swift
func textViewDidChange(_ textView: UITextView) {
        var content = textView.text.components(separatedBy: ["\n"])
        var title = content.removeFirst()
        var body = content.joined(separator: "")

        if title.count > 100 {
            title = String(textView.text.prefix(100))
            body = String(textView.text.suffix(textView.text.count - 100))
        }

        let modifiedDate = Date().timeIntervalSince1970
        let newNote = Note(title: title, body: body, lastModifiedDate: modifiedDate)
				...
    }
```

## 2. 해결이 되지 않은 점

### 2-1. TextView의 AttributedText 설정

- TextView에서 제목에 해당하는 부분의 폰트를 부분적으로 변경해 주기 위해 `AttributedText` 프로퍼티와 `NSMutableAttributedString` 클래스를 사용하여 구현하였습니다. 다만 메모가 실시간으로 수정되어도 해당 설정이 유지되도록 구현하고자 하였는데, 내용 수정 후 AttributedText의 값을 다시 업데이트 해주는 과정에서 커서가 내용의 끝으로 이동하는 현상이 발생하는 것을 확인할 수 있었습니다.  이 상황에 대응하려면 AttributedText프로퍼티에 새로운 값을 주입하는 방식이 아닌 다른 방식을 사용해야 될 것 같다고 생각이 되는데 방법을 찾지 못했습니다.
    - 참고 이미지
    
 ![](https://i.imgur.com/ZepAYDV.png)

### 2-2. 하단의 내용을 상단으로 스크롤하는 기능

- 기본 메모앱의 경우, 사용의 쾌적한 편집환경을 위해서 TextView의 Bottom Inset을 주어 편집 시 커서가 있는 부분을 상단으로 스크롤 할 수 있도록 구현되있는 것을 확인했습니다.
- TextView 자체의 ScrollView를 활용하는 상황에서는 어떤 방식으로 Inset을 부여해도 의도한 대로 동작하지 않아 별도의 `ScrollView` 내부에 TextView를 하위뷰로 넣는 방식으로 고민해 보았는데요. 해당 방법을 선택했을 시 줄바꿈 스크롤 대응을 별도로 구현해 줘야 한다는 단점이 있었습니다. 좀 더 좋은 방법을 고민해 보고 있습니다.

---

## 3. 조언을 얻고 싶은 부분

### 3-1. VC간 데이터 전달 방식

- 부모VC → 자식VC의 경우는 `프로퍼티 직접 주입`, 자식VC→ 부모VC의 경우는 `NotificationCenter`를 사용하였습니다.
    - SplitVC가 PrimaryVC와 SecondaryVC를 알고있기 때문에, 프로퍼티를 직접 주입하는 방식을 택했습니다.
    - PrimaryVC와 SecondaryVC에서 필요한 DataSource를 특정하기 위해 `IndexPath`를 전달해야 했는데 이때 NotificationCenter를 활용하여 전달 해 주었습니다.
- 처음 구현을 할때는, 다수의 객체들에 동시에 이벤트를 송신할 일이 있을수도 있다고 생각하여 `NotificationCenter`를 사용하였는데요 구현을 하고 나니 단일 객체에만 이벤트를 보내고 있어서 Delegate패턴을 사용해도 괜찮을 것 같다는 생각이 들었습니다. 이런 경우에는 `Delegate`패턴을 사용하는 게 더 좋은 선택일까요?

2022-02-10 12:27 UTC, kcharliek commented
## 해결이 되지 않은 점

1. TextView의 AttributedText 설정

구글링 키워드 'ios uitextview first line font' 로 구글링을 권해드립니다.

https://hartl.co/2015/05/21/Highlight-first-line.html
https://stackoverflow.com/questions/16423632/how-to-allow-nsattributedstring-text-be-typed-into-a-uitextview

2.  하단의 내용을 상단으로 스크롤하는 기능

UIScrollView를 Container로 사용하는 방법도 좋습니다만, 조금 더 심플하게 풀 수 있지 않을까 싶은데요. 핵심 기능이 아닌 만큼 여유를 가지고 같이 고민해봐요. 그리고 저는 이 이슈의 해결에서 배울 수 있는 점이 크지 않을 것 같다고 생각해서요. 많은 시간은 투자하지 마시길 권해드립니다.

3. NotificationCenter 는 대부분의 경우에서 좋은 선택이 되지 않습니다. Notification 은 '나는 이벤트 쏜다! 받고싶은 사람 아무나 받아!' 라는 식으로 앱의 논리 흐름을 복잡하게 하기 때문입니다. 좋은 코드는 논리가 단방향으로 흐르고, 앱의 흐름을 추적하기 쉽게합니다. Singleton 등과 함께 피해야하는 스타일이라는 점에서 수정되었으면 합니다. 다수에게 이벤트를 보내고 싶을 때에도 Delegate Pattern을 사용할 수 있습니다. https://www.raywenderlich.com/books/design-patterns-by-tutorials/v3.0/chapters/16-multicast-delegate-pattern 를 참고 바랍니다. 또는 closure array 로 해결할 수도 있을 것 같고요. Reactive 개념을 사용하는 팀들은  Rxswift나 combine을 통해 해결하기도 합니다. 우선 이번 과제에서는 Delegate Pattern으로 접근하는 것을 권해드릴게요. Delegate Pattern의 숙련도를 높히는 것이 지금은 중요하다고 생각합니다.

2022-02-10 12:33 UTC, kcharliek commented on CloudNotes/CloudNotes/Controller/DetailedNoteViewController.swift
> +    let noteTextView: UITextView = {
UI Component는 private 제어자를 붙여주세요. UI Component 에 대한 변경은 닫혀있는 것이 좋습니다. 가능한 변경 가능성을 줄여서 앱의 흐름을 통제해주세요.

2022-02-10 12:47 UTC, kcharliek commented on CloudNotes/CloudNotes/Controller/DetailedNoteViewController.swift
> +    var index: Int?
DetailedNoteViewController 는 SplitViewController 관점에서 'View'로 이해되고요. index 프로퍼티가 외부에서 주입되고, 이후에 Notification을 통해 외부로 재전달하는 상황으로 이해했습니다.

View는 Model을 표현하고, Delegate Pattern등을 통해 이벤트의 발생을 알려주는 역할만 하는 것이 좋습니다. 그런데 지금 DetailedNoteViewController는 index라는 상태를 관리 하고 있는데요. '상태 홀더' 의 역할을 하는 것이 Model의 역할을 하는 것으로 보입니다. 현재 model의 index는 Parent가 관리해도 될 것 같아요. DetailedNoteViewController 는 단순히 Note Text를 노출하고, 텍스트를 수정하고, '내 텍스트가 변했다' 라는 이벤트만 처리하면 됩니다.  상태 관리는 View의 역할이 아닙니다.

2022-02-10 12:49 UTC, kcharliek commented on CloudNotes/CloudNotes/Controller/DetailedNoteViewController.swift
> +        NotificationCenter.default.post(
위에 코멘트 드렸습니다. 객체간 통신 방법으로 NotificationCenter 는 대부분 좋은 방법이 아닙니다.

2022-02-10 12:52 UTC, kcharliek commented on CloudNotes/CloudNotes/Controller/NoteListCell.swift
> +    let titleLabel: UILabel = {
위에 코멘트 드린 것 처럼, View의 UI Component 는 private 제어 해주세요. UI Component 가 아닌 상태를 저장하는 property들도 기본은 private입니다. 
그리고 나면 UITableView 에서 Cell에 configure method를 통해 데이터를 세팅해야 할 것이고요. 그러면 우리는 외부에서(UITableVIew 등) 에서 View를 사용하는 방법을 '통제' 할 수 있게됩니다.

2022-02-10 12:57 UTC, kcharliek commented on CloudNotes/CloudNotes/Controller/NoteListViewController.swift
> +        guard let cell = tableView.dequeueReusableCell(
[참고 사항입니다]

현업에서는 보통 reuseIdentifier를 class name과 같게 설정하여, 관리 부하를 줄입니다.

https://github.com/SwifterSwift/SwifterSwift/blob/master/Sources/SwifterSwift/UIKit/UITableViewExtensions.swift#L74

의 방법을 한번 읽어보세요.

2022-02-10 12:59 UTC, kcharliek commented on CloudNotes/CloudNotes/Controller/SplitViewController.swift
> +    let noteListViewController = NoteListViewController()
private 접근 제어자 챙겨주세요.

2022-02-10 13:05 UTC, kcharliek commented on CloudNotes/CloudNotes/DataSourceProvider/JSONDataSourceProvider.swift
> +    mutating func fetch() throws {
성능 관점에서 struct를 사용하신걸까요. 또는 값타입이 필요한 상황이 있을까요.
값타입은 변경으로부터 자유롭다는 장점이 있고요. mutating은 struct 를 올바르게 사용하지 않았다는 반증이 됩니다.
이 경우는 class가 더 적절할 것 같습니다.

2022-02-10 13:07 UTC, kcharliek commented on CloudNotes/CloudNotes/DataSourceProvider/JSONDataSourceProvider.swift
> +        guard let decodedData: [Note] = try? DecodingUtility.decode(data: data) else {
try? 로 인해 decode가 뱉는 error가 씹힐 것 같습니다. fetch가 throws 를 지원하니

``` swift
let decodedData: [Note] = try DecodingUtility.decode(data: data)
```

를 그대로 사용하시는 것이 더 좋을 것 같습니다.

2022-02-10 13:08 UTC, kcharliek commented on CloudNotes/CloudNotes/DataSourceProvider/NoteDataSource.swift
> +    var noteList: [Note] { get set }
setter를 열어줄 필요가 있을까요.

2022-02-10 13:08 UTC, kcharliek requested changes
NotificationCenter 를 제거하는 것을 필수 수정 사항으로 하겠습니다.

2022-02-11 02:37 UTC, gogosilver commented on CloudNotes/CloudNotes/DataSourceProvider/JSONDataSourceProvider.swift
> +        guard let decodedData: [Note] = try? DecodingUtility.decode(data: data) else {
`decode(data:)`단에서 이미 오류를 지정해주고 있어서 해당 라인에서는 불필요하다는 것을 알게 되었습니다.

감사합니다!

2022-02-11 02:41 UTC, FIIIIN commented on CloudNotes/CloudNotes/DataSourceProvider/NoteDataSource.swift
> +    var noteList: [Note] { get set }
내부 메서드로 변경될 프로퍼티이기 때문에 말씀하신 것처럼 setter는 불필요하다고 생각하여 리팩토링 진행하였습니다.

2022-02-11 02:45 UTC, forestjae commented on CloudNotes/CloudNotes/DataSourceProvider/JSONDataSourceProvider.swift
> +    mutating func fetch() throws {
말씀하신대로, struct를 사용할 이유가 없는 타입이어서 class로 변경하였습니다.

2022-02-11 05:13 UTC, FIIIIN commented on CloudNotes/CloudNotes/Controller/NoteListViewController.swift
> +        guard let cell = tableView.dequeueReusableCell(
알려주신 링크 참고하여 개선하였습니다. 멋진 방법 제안해주셔서 감사합니다!

2022-02-11 06:22 UTC, forestjae commented on CloudNotes/CloudNotes/Controller/DetailedNoteViewController.swift
> +    var index: Int?
DetailedNoteVC도 View Controller이기에 관리해도 문제가 없다고 생각했는데, 설계 측면에서는 'View'와 같이 기능하기 때문이군요!

Index를 SplitVC에서 관리하도록 수정해 주었습니다.

2022-02-11 06:26 UTC, FIIIIN commented on CloudNotes/CloudNotes/Controller/DetailedNoteViewController.swift
> +        NotificationCenter.default.post(
처음 논의때 말씀드렸던 `Delegation Pattern`을 사용하여 개선해보았습니다.
말씀해주신 것처럼, 델리게이션을 사용하는 편이 여러모로 흐름이 간결해졌습니다👍 델리짱짱

2022-02-11 08:25 UTC, forestjae commented on CloudNotes/CloudNotes/Controller/SplitViewController.swift
> +    let noteListViewController = NoteListViewController()
접근제어자 추가하였습니다 !

2022-02-11 08:25 UTC, forestjae commented on CloudNotes/CloudNotes/Controller/DetailedNoteViewController.swift
> +    let noteTextView: UITextView = {
기본적인걸 놓쳤네요 ㅠㅠ 추가하였습니다!

2022-02-11 13:33 UTC, kcharliek approved these changes
수정 잘 해주셨고 고생 많으셨습니다 ㅎㅎ 제 코멘트는 모두 해결되었다고 생각하고, 어프룹하겠습니다 ;)

2022-02-13 13:47 UTC, merged