동기화 메모장 [STEP 1] 줄라이, 릴리, 앨리
yagom-academy/ios-cloud-notes pull request #81
Opened 2022-02-10 12:30 UTC by yeahg-dev

안녕하세요 찰리 @kcharliek
릴리, 앨리, 줄라이 입니다!
STEP1 구현 완료되어 PR 드립니다.
부족한점이 많지만 리뷰 잘 부탁드려요☺️

# 고민했던 점

## 1. Delegate 사용

DetailView의 textView에 데이터를 띄워주는 방식에 대해 고민해보았습니다.

TableView가 이미 data를 가지고 있고, SplitViewController가 ListVC와 DetailVC를 둘다 알고있어서 delegate 패턴을 활용하여 ListVC의 delegate를 SplitVC로 지정해주었습니다.

ListVC에 있는 Cell이 클릭되었을 때 SplitVC의 noteListViewController() 메소드를 실행시켜 textView가 업데이트 되도록 해주었습니다.
![ㅇㅇㅇㅇ](https://user-images.githubusercontent.com/81469717/153408663-9116d5bb-c688-4d6d-9abd-af47e7138c17.jpg)

<br>

## 2. `NoteTableViewCell` 레이아웃, constraint 설정

### 문제상황

TableViewCell의 contentView는 아래 그림과 같이 정상적(기대하는) 사이즈인데, 셀의 레이블이 잘려서 나오는 버그가 있었습니다. 

<img width="1304" alt="스크린샷 2022-02-08 오후 9 50 01" src="https://user-images.githubusercontent.com/81469717/153408766-82525da7-8b7a-4367-b50c-80149c0ec4ff.png">

그래서 레이블들을 담는 가장 큰 스택뷰의 오토레이아웃을 잘못 설정해주었나 싶어서, `contentView` 대신 `safeAreaLayoutGuide` 와 제약을 줘보는 시도도 해보았습니다.

```swift
private func setUpLayout() {
        NSLayoutConstraint.activate([
            textVerticalStackView.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -5),
            textVerticalStackView.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 15),
            textVerticalStackView.topAnchor.constraint(equalTo: contentView.topAnchor, constant: 7),
            textVerticalStackView.bottomAnchor.constraint(equalTo: contentView.bottomAnchor, constant: -7)
        ])
    }
```

그런데 `textVerticalStackView` 의 leading, top, bottom anchor의 제약은 정상적으로 적용되는데, trailing만 안되는 것이 이상하다고 판단되고, splitView의 invisible mode로 보았을 때 셀이 아래와 같이 보이는 점으로 추측해서 `tableView` 자체의 크기가 화면전체의 크기라는 것을 깨달았습니다🤦‍♀️
<img width="940" alt="스크린샷 2022-02-10 오후 9 12 24" src="https://user-images.githubusercontent.com/81469717/153408837-147df924-6328-4d1b-8fb7-1d410da818cb.png">

### 해결

`NoteListViewController` 의 `listTableView` 의 제약을 뷰의 `safeAreaLayoutGuide` 와 줘서 tableView 사이즈를 줄여줌으로써 해결했습니다.

```swift
private func setUpLayout() {
        NSLayoutConstraint.activate([
            listTableView.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor),
            listTableView.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor),
            listTableView.widthAnchor.constraint(equalTo: view.safeAreaLayoutGuide.widthAnchor),
            listTableView.heightAnchor.constraint(equalTo: view.safeAreaLayoutGuide.heightAnchor)
        ])
    }
```

# 궁금한 점

1. `contentView.addSubview` 와  `self.addSubview` 의 차이

`customTableViewCell` 의 뷰를 채울 때 `contentView.addSubview` 또는  `self.addSubview` 으로 뷰를 추가해줄 수 있었습니다. 그런데 두 방법 모두 같은 결과를 가져오는 것을 확인했습니다. 두 방법의 차이는 없는 걸까요?? 

2. `tableViewCell` 의 컨텐트의 제약을 `contentView` 와 주는게 맞을까요? `safeAreaLayoutGuide` 와 주는게 더 맞을까요?

<br>

# 조언을 얻고 싶은 부분

## Data를 가질 타입

DataStorage( 데이터를 가지고 있는 타입)을 누가 가지고 있어야 할까에 대하여 고민했습니다.

SplitView는 TableView와 TextView를 가지고 있는 각각의 뷰컨트롤러를 알고 있고 TableView 와 TextView를 들고있는 뷰컨은 서로를 모르는 상태입니다. 하지만 저희 생각으로는 TableView가 클릭되었을 때 TextView의 글자가 업데이트 되는 흐름으로 진행되어, TableView가 데이터를 가지고 있게 했습니다. 

다른 방법으로는 각각이 데이터를 가지고 있는 방법, 두개의 뷰컨트롤러를 알고 있는 SplitView가 가지고 있는 방법 등이 있을 것 같습니다. 찰리라면 어떤 방식으로 구현을 하셨을지가 궁금합니다. ( 저희가 생각한 방식이 맞는지도 궁금합니다 ) !! 

## DateFormatter

JSON으로 받아오는 Int 타입의 날짜 형식을 `DateFormatter`를 이용하여 원하는 형식으로 변환해주었습니다. 지금은 모델 내부에서 연산프로퍼티로 DateFormatter 인스턴스를 생성해 변환해주고 있는데 해당방식은 데이터를 받아올 때마다 인스턴스를 생성해주고있어서 다른 방식에 대해서도 고민을 해보았습니다.

싱글턴으로 사용하는 방법도 있을 것 같은데, 싱글턴을 사용하면 프로그램이 종료될 때까지 메모리에 남아있게 된다는 단점도 있을 것 같습니다. 

또 다른 방법이 있을까요?

2022-02-11 03:57 UTC, kcharliek commented
## 궁금한 점에 대해

1. Cell에서 contentView.addSubview 와 self.addSubview 의 차이

두 결과의 차이가 없다는 점이 의아하네요. 대부분의 경우 contentView 안에 추가 하는 것이 맞습니다. Content 영역을 스와이프 한다던지, Cell Accessary를 다룬다던지 할 때 Content 영역이 동적으로 움직이게 되는데요. 이런 기능 지원을 위해서는 contentView 안에 컨텐츠가 들어있어야합니다. contentView 뒤쪽에 backgroundView를 넣는다던지 할 때 self.addSubview를 했던 기억이 나는데요. 두 방식의 결과 차이가 분명 있을거 같아요.

2. tableViewCell 의 컨텐트의 제약을 contentView 와 주는게 맞을까요? safeAreaLayoutGuide 와 주는게 더 맞을까요?

위의 splitVC 케이스에서는 구조 캡처해주신 것 처럼 실제 TableView의 영역이 화면 크기와 같기때문에 이를 safeArea로 해결할 수 밖에 없을 것 같네요. 그런데 위 케이스가 일반적이지는 않은 것같고, 보통은 contentView에 constraint를 걸어주고요. 노치 등에 의한 컨텐츠 가려짐을 처리하고싶다면 safeArea에 걸기도 하고요. 'SafeArea' 지원이 필요한지 여부에 따라 케바케로 고민해보시면 될 것 같습니다.

2022-02-11 04:07 UTC, kcharliek commented
## 조언을 얻고 싶은 부분에 대해

아키텍처를 불문하고 View가 상태를(데이터를) 관리하는 경우는 없습니다. View는 전달된 데이터(Model)를 그대로 보여주고, 터치 이벤트 등이 발생하면 이를 다른 객체에 전달할 뿐이에요. 그런 관점에서 TextView가 데이터를 들고있고, 이를 SplitVC로 전달, 이를 다시 TextView쪽으로 전달하는 흐름이 수정되었으면 합니다. 저라면 SplitVC가 메인 컨트롤러의 역할을 하고있으니 SplitVC가 데이터를 관리하도록 할 것 같아요. 앞서 말씀 드린 것 처럼 TableView는 데이터를 노출하고, 사용자가 터치한 indexPath를 그저 SplitVC에 전달할 뿐이죠. 그리고 SplitVC는 전달받은 indexPath에 맞는 데이터를 가져다가 TextView에 전달하는. 그런 흐름일 것 같습니다. 

2. DateFormatter 사용 방법에 대해

static property / method를 사용하면 프로그램이 종료될 때까지 메모리에 남아있게 된다는 사실에 대해 고민 잘 해주셨습니다. static 을 사용할 때에는 이 점을 항상 고민해야합니다. 

제 생각은 Dateformatter의 경우 아주 작은 객체이니까요. 이를 매번 생성하거나 이를 App 의 생명주기동안 살려두거나 어떤 방식으로 사용하던지 괜찮을 것 같습니다.

2022-02-11 04:08 UTC, kcharliek commented on CloudNotes/CloudNotes/Controller/NoteDetailViewController.swift
> +    private var textView: UITextView = {
private 처리 잘 해주셨습니다. UI Component는 가능한 외부에 숨기는 것이 좋습니다.

2022-02-11 04:08 UTC, kcharliek commented on CloudNotes/CloudNotes/Controller/NoteDetailViewController.swift
> +    override func loadView() {
loadView 타이밍을 사용하신 이유가 있나요 ?

2022-02-11 04:09 UTC, kcharliek commented on CloudNotes/CloudNotes/Controller/NoteListViewController.swift
> +    func noteListViewController(didSelectedCell data: Sample)
protocol 네이밍을 UIKit 스타일로 맞춘 캠퍼는 처음 본 것 같네요. 잘 해주셨습니다.

2022-02-11 04:10 UTC, kcharliek commented on CloudNotes/CloudNotes/Controller/NoteListViewController.swift
> +        guard let cell = tableView.dequeueReusableCell(
[참고 사항입니다]

현업에서는 보통 reuseIdentifier를 class name과 같게 설정하여, 관리 부하를 줄입니다.

register : https://github.com/SwifterSwift/SwifterSwift/blob/master/Sources/SwifterSwift/UIKit/UITableViewExtensions.swift#L127

dequeue : https://github.com/SwifterSwift/SwifterSwift/blob/master/Sources/SwifterSwift/UIKit/UITableViewExtensions.swift#L88

의 방법을 한번 읽어보세요.

2022-02-11 04:13 UTC, kcharliek commented on CloudNotes/CloudNotes/Controller/NoteListViewController.swift
> +        guard let data = self.dataStorage?.assetData[safe: indexPath.row] else {
데이터를 얻어오지 못했을 때, crash를 발생시키는 건 가혹한 것 같습니다. 개발자의 실수로 indexPath에 맞는 data를 얻어오지 못했던 경우가 빈번했던 것 같습니다.

저라면 위의 guard문의 경우처럼 빈 cell을 보여주던지, 아니면 데이터가 없는 경우에 대한 UI를 생각해서 cell에 표시한다던지 할 것 같아요. 다른 방법을 고민해주세요.

2022-02-11 04:13 UTC, kcharliek commented on CloudNotes/CloudNotes/Controller/NoteSplitViewController.swift
> +    let noteListViewController = NoteListViewController()
private 접근제어자 챙겨주세요.

2022-02-11 04:15 UTC, kcharliek commented on CloudNotes/CloudNotes/Utility/JSONParser.swift
> +            fatalError()
여기도 fatalError가 가혹한 것 같습니다. JSON Parsing 실패할 수도 있죠 모 ...

decodeData 를 throws 처리한다던지, nil을 내려준다던지 하는 건 어떨까요.

2022-02-11 04:16 UTC, kcharliek requested changes
Data 관리를 SplitVC가 하도록 하는 것을 필수 수정 사항으로 하겠습니다

2022-02-14 06:22 UTC, July911 commented on CloudNotes/CloudNotes/Controller/NoteDetailViewController.swift
> +    override func loadView() {
loadView 는 뷰를 로드해주는 작업이라 생각되어, 뷰의 backgroundColor나 addsubview 해주는 작업을 해주었습니다.
이를 제외하고 평소 viewDidLoad에서 해주었던 메소드같은 경우에는 그대로 viewDidLoad에 해주었습니다.
사용한 이유는 .. 좀 더 명확하게 표현하고 싶었다 가 맞는거 같습니다 .

2022-02-14 06:35 UTC, July911 commented on CloudNotes/CloudNotes/Controller/NoteListViewController.swift
> +        guard let cell = tableView.dequeueReusableCell(
앗 ... 이런 방법이 있었군요 ! 
타입캐스팅을 따로 해주지 않아도 되는점과 indentifier가 정해진다니 정말 놀랍네요 ..! 
좋은 방법 감사합니다 :) 적용했습니다 !

2022-02-14 06:35 UTC, yeahg-dev commented on CloudNotes/CloudNotes/Controller/NoteListViewController.swift
> +        guard let data = self.dataStorage?.assetData[safe: indexPath.row] else {
fatalError는 가혹한 것 같아서 `NoteListTableViewCell`인스턴스를 반환하는 방법으로 수정하였습니다~

2022-02-14 06:53 UTC, July911 commented on CloudNotes/CloudNotes/Utility/JSONParser.swift
> +            fatalError()
nil을 내려주는 방법으로 수정했습니다! :) 감사합니다

2022-02-14 09:55 UTC, kcharliek approved these changes
고생 많았어요 :)

2022-02-14 09:55 UTC, merged