동기화 메모장 [STEP 1] Nicholas, 신나, yeha
yagom-academy/ios-cloud-notes pull request #83
Opened 2022-02-11 06:06 UTC by ye-ha

안녕하세요, 콘! @protocorn93 
저희 스텝1 마무리해서 PR 보내드립니다. 
스텝 진행하며 고민한 부분 함께 적어보았습니다. 
잘 부탁드립니다! 🙏 감사합니다.

## 고민했던 점

### NoteModelManager에서 Note 데이터를 가져올 때 인터페이스 분리하는 것에 관한 고민

- 테이블 뷰 셀의 레이블을 설정할 때, NoteModelManager의 인터페이스에 대해서 고민을 해보았습니다.
    - 의견1. 하나의 인터페이스(메서드)를 통해 Note타입을 반환하자는 의견
        
        ```swift
        func fetchDetailData(at index: Int) -> Note {
        	return noteData[index]
        }
        ```
        
    - 의견2. 각 레이블별로 인터페이스(메서드)를 분리하여 화면에 보여질 타입인 String타입을 각각 반환하자는 의견
        
        ```swift
        func fetchTitle(at index: Int) -> String {
        	  let noteData = self.noteData[index]
        	  return noteData.title
        }
        
        func fetchDate(at index: Int) -> String {
        	  let noteData = self.noteData[index]
        	  let formattedDate = formatter.string(from: noteData.lastModified).replacingOccurrences(of: "/", with: ". ")
        	  return formattedDate
        }
        
        func fetchBody(at index: Int) -> String {
        	  let noteData = self.noteData[index]
        	  return noteData.body
        }
        ```
        
- 의견1의 특징: 객체의 메서드 호출이 잦으면 method 의 메모리 상 위치를 추적하는 컴퓨팅 비용이 추가적으로 필요하기 때문에 성능상의 손실이 발생할 수 있을 것으로 짐작하고 있습니다.
- 의견2의 특징: 인터페이스를 분리함으로서 확장이 유리함
- 상기와 같이 2가지의 의견이 있었습니다.
- 저희가 고민한 부분에 있어서 콘은 어떻게 생각하시는지, 무엇을 선택하실 것인지, 다른 좋은 방법이 있는지 궁금합니다.

---

### 뷰에게 데이터를 전달하는 방법에 대하여

- `UISplitViewController` 특성 상 두 개의 `ViewController`를 가지고 있으며 공통의 데이터를 다루게 되어서 **데이터를 갖고 있는 `NoteModelManager`를 어떻게 처리할지** 고민했습니다.
    - 현재 SceneDelegate에서 각 ViewController를 아래와 같이 생성하고 있습니다.
        
        ```swift
        let mainViewController = UISplitViewController(style: .doubleColumn)
                let primaryViewController = NoteListTableViewController()
                let secondaryViewController = NoteDetailViewController()
                
                primaryViewController.delegate = secondaryViewController
                mainViewController.view.backgroundColor = .systemBackground
                
                mainViewController.setViewController(primaryViewController, for: .primary)
                mainViewController.setViewController(secondaryViewController, for: .secondary) 
        ```
        
- 가장 먼저 `NoteListTableViewController` 를 생성하고, 데이터를 어떻게 다룰지 고민했습니다.
    - 현재  `NoteListTableViewController` 내에서 `NoteModelManager`라는 인스턴스를 가지고 있습니다. 데이터가 필요한 상황에 `noteModeMmanager` 내부의 메서드를 호출하고 있습니다.
        
        ```swift
        override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
                let cell = tableView.dequeueReusableCell(withIdentifier: cellId, for: indexPath)
                
                if let cell = cell as? NoteListTableViewCell {
                    cell.titleLabel.text = noteModelManager.fetchTitle(at: indexPath.row)
                    cell.lastModifiedLabel.text = noteModelManager.fetchDate(at: indexPath.row)
                    cell.bodyLabel.text = noteModelManager.fetchBody(at: indexPath.row)
                    return cell
                }
                return cell
            }
        ```
        
        ---
        
- 그 다음 `NoteDetailViewController` 를 생성했습니다. 이 때 **공통의 데이터를 어떻게 처리해야 할지** 고민했습니다.
- 아래와 같은 방법을 생각해보았습니다.
    1. SceneDelegate에서 인스턴스 생성 후 ViewController의 생성자를 통해 의존성 주입
    2. Delegate 메서드를 통해 Master(NoteListTableViewController) → Detail(NoteDetailViewController) 의존성 주입
    3. Model 인스턴스 대신 NoteDetailViewController 에서 보여줘야 할 데이터만 주입
    4. NoteListTableViewController의 noteModelManager의 참조를 함수를 이용해 전달
- 저희가 선택하고 고민한 과정에서 조언해주실 부분이 있을까요? 콘이 자주 사용하시는 방법이 있으신지도 궁금합니다.

---

### Data를 View에 보여주는 용도로 가공해주는 업무를 어떤 객체가 담당하면 좋을지 고민

- 프로젝트 요구사항에는 메모 수정 일자(Date) 정보를 시스템 Local 에 맞추어 포멧팅된 모습으로 출력하도록 구현하라는 명세가 있었습니다.
- ViewController 로 부터 데이터와 로직에 관련된 코드를 Model 객체로 분리시키기 위해 Date 인스턴스를 지역에 알맞게 포멧팅 해주는 업무를 Model 객체 `NoteModelManager`가 담당하도록 구현하였습니다.

```swift
private let formatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.setLocalizedDateFormatFromTemplate("yyyy MM dd")
        formatter.locale = NSLocale.current
        return formatter
    }()

func fetchDate(at index: Int) -> String {
        let noteData = self.noteData[index]
        let formattedDate = formatter.string(from: noteData.lastModified).replacingOccurrences(of: "/", with: ". ")
        return formattedDate
    }
```

- 다만, 분리 과정에서 여러 의견이 있었습니다.
    1. 객체를 생성하고, 메세지를 자주 주고 받을수록 성능 상의 손실이 있다.
    2. 데이터를 View에 보여주기 적합하게 가공해주는 역할의 객체를 선언해주는 것이 좋다. 특정 View와 연관된 데이터 로직을 ViewController와 Model에서 분리해야 다른 ViewController에서 Model을 사용할 때 불필요한 인터페이스가 따라오지 않게 된다. 
    3. 데이터를 가공하는 일은 ViewController에서 하는 일이 아니다. Model에서 하거나 extension으로 분리해야 한다. 
- 조언해주실 부분이 있을까요? 이 또한 콘이 사용하시는 방법이 궁금합니다.

---

### JSONDecoder 유틸리티를 어떻게 관리하면 좋을까요??

- JSONDecoder의 경우 JSON 데이터에 따라 어떤 모델 타입으로 디코딩 될지 달라지 질 수 있습니다.
- 현재 프로젝트에는 데이터를 관리하는 모델 객체 `NoteModelManager`에서 JSONDecoder 인스턴스를 생성하여 관리하고 있습니다.
    
    ```swift
    func fetchData() {
            let decoder: JSONDecoder = {
                let decoder = JSONDecoder()
                decoder.keyDecodingStrategy = .convertFromSnakeCase
                decoder.dateDecodingStrategy = .secondsSince1970
                return decoder
            }()
            let jsonAsset = NSDataAsset(name: "sample")
            guard let jsonData = jsonAsset?.data else {
                return
            }
            if let result = try? decoder.decode([Note].self, from: jsonData) {
                noteData = result
            }
        }
    ```
    
- 바로 위에 질문드린 DateFormatter도 유틸리티로 분류할 수 있을 것같습니다.
- 콘은 JSONDecoder, DateFormatter와 같은 유틸리티 기능들을 어떤 방식으로 관리하시는 편인지 의견을 여쭤보고 싶습니다.

2022-02-11 12:15 UTC, protocorn93 requested changes
세 분 모두 수고하셨습니다! 

먼저 기능에 따른 역할을 나누려는 시도에 박수를 보내고 싶어요! 👏 유연한 설계는 여기서 시작되는데 벌써 시작하셨군요!!

그리고 전체적으로 코드의 가독성도 좋아 읽기 수월했습니다. 

# 고민했던 점 

## NoteModelManager에서 Note 데이터를 가져올 때 인터페이스 분리하는 것에 관한 고민

저는 `의견1`에 한표를 던지고 싶습니다. 말씀해주신 것처럼 메모리 영역에서의 성능을 생각하고 계신 점 매우 훌륭하게 생각해요. 다만 저는 조금 다른 의견을 갖고 있어요. 여기서 발생하는 성능상의 차이는 크게 차이가 나지 않는다고 생각합니다. (물론 이런 부분을 고려하시는건 매우 좋은 습관이고 꾸준히 가져가셔야 할 습관입니다.) 

여기서 세 분이 생각하는 확장성은 무엇인가요? 제가 생각하기엔 여기서 고려될 확장성은 크게 보이진 않네요. 셀에 보여줄 값이 하나 더 늘었다면 `Note`에 프로퍼티를 하나 더 추가해서 넘기면 될 것 같아요. 그게 아니라 메서드를 추가하는 방식이라면 오히려 유지보수성이 떨어진다고 생각합니다. 

또한 알아야할 퍼블릭 인터페이스가 많을수록 (객체 사용법) 유연성은 떨어진다고 생각해요. 

그렇기 때문에 저는 `의견1`에 한표를 던지겠습니다. 

## 뷰에게 데이터를 전달하는 방법에 대하여

먼저 현재 사용하고 계신 방법이 저는 지금 단계에선 최선의 방법이라고 생각해요. 다만 추가로 `NoteModelManager`는 추상화되어 외부에서 주입해주는게 더 좋은 방법이라 생각하구요. 

다만 노트앱이기에 추후 스탭에서 컨텐츠(제목, 내용)의 변경이 되었을 때 리스트와 저장소에도 모두 변경이 반영이 되어야 할텐데, 상세 화면에서 제목이 변경된다면 리스트 화면에도 반영이 되어야겠죠. 

이를 위해선 말씀해주시는 공유하는 데이터를 갖고 있고 이를 가공할 수 있는 객체를 두 화면(리스트, 상세) 객체가 공유해야할겁니다. 이는 추후 스탭을 진행하면서 생각해보면 좋을 것 같아요. 

## Data를 View에 보여주는 용도로 가공해주는 업무를 어떤 객체가 담당하면 좋을지 고민

네~ 이런 고민을 하고 계시다는 것부터가 저는 훌륭하다고 생각해요! 맞아요 결국 데이터를 화면에 보여주기 용이한 형태로 가공하는 것도 하나의 역할입니다. 

다양한 아키텍처에서 이를 담당하는 객체들이 존재합니다. ViewModel, Presenter 등등. 이런 객체 사용에 앞서 먼저 필요한 것은 계층별로 모델을 나누는 것이 선행되어야 합니다. 

이와 관련되어 매우 친절하게 설명하고 있는 [영상](https://youtu.be/M58LqynqQHc)을 하나 첨부해드리겠습니다.

결론을 말씀드리자면 현재 상황에선 이 역할을 `NoteModelManager`가 가져가는것이 좋아보입니다. 

## JSONDecoder 유틸리티를 어떻게 관리하면 좋을까요??

네~ `JSONDecoder`를 사용하는 것은 구현부에 속합니다. 현재 파일로부터 값을 파싱하는 역할을 `NoteModelManager`가 하고 있습니다. 그렇기 때문에 내부에서 이를 다루는 것은 매우 자연스러운 일이라고 생각해요. 

`DateFormatter` 역시 누군가는 이를 의존성으로 바라볼 수 있지만 저는 이를 그렇게 바라보진 않습니다. 물론 `NoteModelManager`가 이 객체에 의존을 하고 있지만 우리가 이를 외부에서 주입해줄 필요는 없다고 생각해요. 변경되거나 대체될 필요가 없는 정적인 의존성이기에 저는 보통 사용하는 객체 안에서 정의해서 사용하곤합니다.

2022-02-11 12:15 UTC, protocorn93 commented on CloudNotes/CloudNotes/Controller/NoteDetailViewController.swift
> +    }()
뷰컴포넌트는 `private`으로 정의해주시는게 좋을 것 같습니다. 값을 뷰에 직접 접근해서 지정하는 것은 지양하고 값을 전달받고 지정은 내부에서 해주시는게 좋습니다. 최대한 내부 정보는 외부로 감추는게 좋습니다!

2022-02-11 12:15 UTC, protocorn93 commented on CloudNotes/CloudNotes/Controller/NoteDetailViewController.swift
> +        textView.isScrollEnabled = false
`isScrollEnabled`를 `false`로 지정한 이유가 있을까요?

2022-02-11 12:15 UTC, protocorn93 commented on CloudNotes/CloudNotes/View/NoteListTableViewCell.swift
> +    }()
마찬가지로 접근제어자가 추가되면 좋을 것 같습니다.

2022-02-11 12:15 UTC, protocorn93 commented on CloudNotes/CloudNotes/Controller/NoteListTableViewController.swift
> +    let cellId = "reuseIdentifier"
셀 재사용을 위한 식별자는 셀 클래스가 갖고 있는게 맞습니다. 테이블뷰나 콜렉션뷰를 사용하면서 셀을 register하거나 dequeue하는데 있어 보다 편리한 방법들을 많은 블로그들에서 소개하고 있어요. 이들을 참고해서 보다 사용하기 쉬운 방법을 제공하는 helper 메서드를 구현해보시는건 어떨까요? 

작성된 코드는 소개하는 글마다 조금씩 다르지만 큰 맥락에선 같은 방법을 사용하고 있습니다. 다음은 이를 소개하는 예시 글입니다. 

- [An easier way to dequeue cells in iOS](https://medium.com/over-engineering/an-easier-way-to-dequeue-cells-in-ios-5c8b8de4dfed)

2022-02-11 12:15 UTC, protocorn93 commented on CloudNotes/CloudNotes/Controller/NoteListTableViewController.swift
> +        self.navigationItem.rightBarButtonItem = addBarButtonItem
이 영역의 들어가는 코드들도 각각의 역할에 따라 메서드를 분리하는게 가독성 향상에 도움이 될 것 같아요. 

한줄짜리 메서드라도 이름이 전달하는 의미가 분명하다면 메서드로 분리하는게 좋습니다.

2022-02-11 12:15 UTC, protocorn93 commented on CloudNotes/CloudNotes/Controller/NoteListTableViewController.swift
> +            delegate?.selectNote(title: "", body: "")
제거되고 빈 상세 화면을 보여주기 위한 코드로 보이는데 그에 맞는 메서드 네이밍과 형태를 가져가는게 좋을 것 같아요.

2022-02-11 12:15 UTC, protocorn93 commented on CloudNotes/CloudNotes/Model/NoteModelManager.swift
> +            decoder.dateDecodingStrategy = .secondsSince1970
strategy를 활용한 점 좋은 것 같아요!

2022-02-11 12:15 UTC, protocorn93 commented on CloudNotes/CloudNotes/Model/NoteModelManager.swift
> +        if let result = try? decoder.decode([Note].self, from: jsonData) {
`do-catch`를 사용하지 않고 `try?`를 사용하기로 선택한 이유가 궁금합니다.

2022-02-11 12:15 UTC, protocorn93 commented on CloudNotes/CloudNotes/Supporting Files/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
이 영역도 지금은 간단한 형태의 앱이지만 실제 입사를 하고 사내 프로덕트를 다루게 되면 이 영역에도 상당히 많은 양의 코드가 들어가게 됩니다. 그렇기 때문에 이 영역에서도 적절한 메서드 분리를 해보시는 연습을 하시는걸 권장드립니다.

2022-02-11 12:15 UTC, protocorn93 commented on CloudNotes/CloudNotesTests/CloudNotesTests.swift
> +        XCTAssertNotNil(result)
이 테스트가 유의미한 테스트인지는 고민해볼 필요가 있을 것 같아요. 

테스트한 대상을 보면 결국 애플이 제공하는 `JSONDecoder` 객체를 테스트하고 있습니다. 기본으로 제공되는 구현체는 테스트 코드를 작성할 필요는 없습니다. 

이 테스트가 유의미한 테스트가 되려면 파일을 디코딩할 때, 유효한 형식의 파일일 경우 결과를 정상적으로 반환하는지 여부를, 유효하지 않은 형식의 파일일 경우 에러를 뱉는지 여부를 테스트해야 합니다. 

그리고 그 대상은 `JSONDecoder`가 아니라 "파싱을 하고 결과를 반환하는 객체"를 대상으로 해야할 것입니다.

2022-02-11 12:15 UTC, protocorn93 commented on CloudNotes/CloudNotes/Controller/NoteListTableViewController.swift
> +    var noteModelManager = NoteModelManager()
`NoteModelManager`로 역할을 나눠주신 부분 너무 훌륭합니다! 👏

다만 보다 유연한 앱 구조를 위해서 우리는 특정 객체를 직접 바라보는 것은 지양해야합니다. 현재 뷰컨트롤러와 매니저는 강하게 결합되어 있습니다. 

이를 위해선 먼저 `NoteModelManager`를 프로토콜로 추상화할 필요가 있어보입니다. 
그리고 이를  `NoteListTableViewController` 생성시 주입해 주는 것이 좀 더 바람직한 설계를 위한 첫발걸음일 것 같아요.

2022-02-11 12:15 UTC, protocorn93 commented on CloudNotes/CloudNotes/Controller/NoteDetailDelegate.swift
> +protocol NoteDetailDelegate: AnyObject {
`NoteDetailDelegate`라는 네이밍에 대해 고민을 해볼 필요가 있어요. delegate란 위임하다, 위임자라는 뜻으로 개발을 하는데 있어서는 특정 일을 누군가에게 위임하여 처리하도록 한다로 생각해주시면 될 것 같아요.

여기서 우리는 리스트에서 셀이 선택되었을 때 행동을 위임하고 있습니다. 즉 리스트가 자신의 일을 누군가에게 위임하는 것이므로 `NoteListTableViewDelegate`라는 네이밍이 적절할 것 같아요.

2022-02-14 05:40 UTC, ye-ha commented on CloudNotes/CloudNotes/Controller/NoteDetailViewController.swift
> +    }()
뷰 컴포넌트에 접근제어 지정을 깜빡했습니다.. 말씀해주신 대로 최대한 내부 정보가 노출되지 않도록 수정해보았습니다!

2022-02-14 05:41 UTC, smart8612 commented on CloudNotes/CloudNotes/Controller/NoteDetailViewController.swift
> +        textView.isScrollEnabled = false
* textView의 스크롤 기능을 사용하지 않고 별도의 ScrollView 에  embed 해서 사용하기 위해 false 설정을 해두었습니다.
* 별도의 ScrollView를 사용하는 목적은 키보드가 올라왔을 때 UI 컴포넌트를 가리지 않도록 기능을 구현하는 목적이었습니다.

2022-02-14 05:43 UTC, ye-ha commented on CloudNotes/CloudNotes/View/NoteListTableViewCell.swift
> +    }()
추가했습니다!

2022-02-14 06:16 UTC, smart8612 commented on CloudNotes/CloudNotes/Controller/NoteListTableViewController.swift
> +    let cellId = "reuseIdentifier"
* 주어진 링크를 참조하여 Cell의 클래스 이름을 String으로 변환해주는 기능을 프로토콜을 통해 덧붙여 주는 코드를 볼 수 있었습니다.
* 다른 여러 코드를 참조해보았을 때 프로토콜의 네이밍으로 `Reusable` 혹은 `ReusableView` 를 사용하는 예시를 보았습니다.
* 위 네이밍이 프로토콜이 제공해주는 행위와 가깝지 않은 것 같아서 고민입니다!
* 위 네이밍이 범용적으로 사용되는 방식인지 궁금하며 저희가 생각해본 네이밍은 `TypeNameConvertible` 입니다.

2022-02-14 07:05 UTC, ye-ha commented on CloudNotes/CloudNotes/Controller/NoteListTableViewController.swift
> +        self.navigationItem.rightBarButtonItem = addBarButtonItem
한 줄이라 어떻게 해야 할지 고민 됐었는데 이 코멘트와 아래 코멘트를 보고 분리하는게 좋겠다는 생각이 들었습니다! 👍

2022-02-14 08:53 UTC, ye-ha commented on CloudNotes/CloudNotes/Controller/NoteListTableViewController.swift
> +    var noteModelManager = NoteModelManager()
NoteModel을 새로 만들어 NoteModelManager 추상화해보았습니다!

2022-02-14 08:56 UTC, ye-ha commented on CloudNotes/CloudNotes/Controller/NoteListTableViewController.swift
> +    var noteModelManager = NoteModelManager()
주입하기 위해 NoteListTableViewController 내에 convenience init 을 만들었습니다.
생성 전 프로퍼티를 사용하는 이슈가 있어서 `private var noteModelManager: NoteModel = NoteModelManager()` 처럼 인스턴스를 생성해주었습니다. 😥

2022-02-14 09:03 UTC, ye-ha commented on CloudNotes/CloudNotesTests/CloudNotesTests.swift
> +        XCTAssertNotNil(result)
앗.. 맞습니다. 이 부분은 이미 완성을 하고 지나가서 해주신 말씀만 기록해두고 테스트케이스를 더 추가하지 않고 지나갔습니다..!

2022-02-14 09:04 UTC, smart8612 commented on CloudNotes/CloudNotes/Controller/NoteListTableViewController.swift
> +            delegate?.selectNote(title: "", body: "")
* 프로토콜 기본 구현을 활용하여 비어있는 화면을 위한 메서드를 구현해주었습니다!
```swift
protocol NoteListTableViewDelegate: AnyObject {
    func selectNote(title: String, body: String)
    func selectBlankNote()   
}
```
```swift
extension NoteDetailViewController: NoteListTableViewDelegate {
    func selectNote(title: String, body: String) {
        self.noteDetailTextView.text = "\(title)\n\n\(body)"
    }
    
    func selectBlankNote() {
        selectNote(title: "", body: "")
    }
}
```

2022-02-14 09:05 UTC, hayeonhee commented on CloudNotes/CloudNotes/Supporting Files/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
SceneDelegate 내에 메서드와 연산 프로퍼티를 추가해서 분리를 해보았습니다. 
SceneDelegate 내부에 메서드와 연산 프로퍼티를 사용하는 것은 처음이라서 현재 바뀐 코드가 적절한지 궁금합니다.

2022-02-14 09:06 UTC, ye-ha commented on CloudNotes/CloudNotes/Controller/NoteListTableViewController.swift
> +        self.navigationItem.rightBarButtonItem = addBarButtonItem
메서드로 분리했습니다!

2022-02-14 09:09 UTC, smart8612 commented on CloudNotes/CloudNotes/Model/NoteModelManager.swift
> +        if let result = try? decoder.decode([Note].self, from: jsonData) {
* `do-catch`를 사용하면 `JSONDecoder`의 decode 메서드가 반환하는 error 타입에 따른 예외처리 동작을 지정해 줄 수 있습니다.
* 다만, 이번 코드의 경우 에러 타입에 관계없이 디코딩에 실패하면 모델에 빈 배열을 담아주도록 구현하고 싶었습니다.
* 따라서 별도의 에러 타입 구분 없이 동일한 처리를 위해 옵셔널 값으로 변환하는 코드 처리를 진행하였습니다!

2022-02-14 09:10 UTC, ye-ha commented on CloudNotes/CloudNotes/Controller/NoteDetailDelegate.swift
> +protocol NoteDetailDelegate: AnyObject {
맞습니다. 현재 리스트가 일하고 있어서 NoteListTableViewDelegate 로 네이밍을 변경해보았습니다!

2022-02-14 13:05 UTC, protocorn93 commented on CloudNotes/CloudNotes/Controller/NoteListTableViewController.swift
> +    let cellId = "reuseIdentifier"
`String`으로 변환해주는 프로토콜의 네이밍은 말씀해주신 네이밍이 더 적절해보이네요!

2022-02-14 13:11 UTC, protocorn93 commented on CloudNotes/CloudNotes/Controller/NoteListTableViewController.swift
> +    var noteModelManager = NoteModelManager()
뷰로 코드를 작성하고 있으니 굳이 `convenience init`을 쓰지 않고도 충분히 주입해줄 수 있어요

```swift
class SomeViewController: UIViewController { 
  private let someDependency: SomeDependency
 
  init(someDependency: SomeDependency) { 
    self.someDependency = someDependency 
    super.init(nibName: nil, bundle: nil)
  }
}

```

2022-02-14 13:11 UTC, protocorn93 commented on CloudNotes/CloudNotes/Supporting Files/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
네네! 적절해보입니다!

2022-02-15 01:10 UTC, ye-ha commented on CloudNotes/CloudNotes/Controller/NoteListTableViewController.swift
> +    let cellId = "reuseIdentifier"
첨부해주신 링크에서 ReusableView 를 사용해서 비슷하게 가야하나 고민했었습니다. ㅎㅎ 말씀해주신 대로 TypeNameConvertible 로 바꾸어보았습니다!

2022-02-15 01:48 UTC, ye-ha commented on CloudNotes/CloudNotes/Controller/NoteListTableViewController.swift
> +    var noteModelManager = NoteModelManager()
아.. 😭👍 감사합니다. 이렇게 바꾸었습니다.

2022-02-15 01:56 UTC, ye-ha commented on CloudNotes/CloudNotes/Supporting Files/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
말씀해주신 대로 configureSplitView 메서드로 분리했습니다!

2022-02-15 02:22 UTC, merged