동기화 메모장 [STEP2] 요한, 아샌, 호댕
yagom-academy/ios-cloud-notes pull request #85
Opened 2022-02-16 09:30 UTC by yanghojoon

안녕하세요. 라이언! @ryan-son 🦁!
아샌(@ICS-Asan), 호댕(@yanghojoon), 요한(@YohanBlessYou)입니다. 

STEP2 PR 올립니다! 

부족한 부분이 많겠지만 피드백 주시면 같이 고민하고 공부해보겠습니다😅

잘 부탁드려요!! 

감사합니다!!

## 💻    주요 구현 내용

### < CoreDataManager >

- CoreDataProperties에 추가적으로 연산 프로퍼티를 추가해야 했기에 `Manual/None`으로 설정했습니다.
    
    ```swift
    extension Memo {
        •••
        var convertedDate: String {
            let dateFormatter = DateFormatter.shared
            let currentDate = Date(timeIntervalSince1970: lastModified)
            
            return dateFormatter.string(from: currentDate)
        }
        
        var entireContent: String {
            let title = title ?? ""
            if let body = body {
                return "\(title)\n\(body)"
            } else {
                return title
            }
        }
    }
    ```
    
- 기존 ViewController끼리 전달하던 데이터를 `CoreDataManager`를 통해 한 번에 ViewController에 데이터를 전달할 수 있도록 수정했습니다. 
`MemoListViewController`와 `MemoContentViewController`에 나눠져 있던 CoreData의 CRUD 관련 메서드를 전부 CoreDataManager에서 수행하도록 변경했습니다.
- ViewController의 경우 `MemoReloadable` 프로토콜을 만들어 이를 채택하도록 했고, `reload` 메서드를 각각 ViewController에서 생성해야 하도록 구현했습니다.
    
    ```swift
    // MemoListViewController
    func reload() {
        memos = CoreDataManager.shared.load()
        tableView.reloadData()
        tableView.selectRow(at: selectedIndexPath, animated: false, scrollPosition: .none)
    }
    
    // MemoContentViewController
    func reload() {
        guard let currentMemo = selectedMemo else {
            textView.text = nil
            return
        }
        setTextView(memo: currentMemo)
        let startPosition = textView.beginningOfDocument
        textView.selectedTextRange = textView.textRange(from: startPosition, to: startPosition)
    }
    ```
    
    `MemoListViewController`에선 tableView를 `reload`한 후 선택된 cell이 선택된 것을 표시해주기 위해 Highlight가 될 수 있도록 했습니다. 
    
    `MemoContentViewController`에선 `reload`를 할 때 시작 지점이 항상 `.beginningOfDocument`가 될 수 있도록 구현했습니다. 
    

### < 메모 작성 시 제목/본문 폰트 변경 >

- 기본 메모어플과 비슷하게 구현하기 위해 메모를 작성하는 뷰에서 제목이 되는 첫줄과 그 이외의 폰트를 다르게 해주었습니다.
- cell이 선택되어 해당 선택된 메모를 불러올 때는 `addAttributes(_:range:)`메서드를 사용하여 title과 body를 각각 설정해 주었습니다.
    
    > 줄바꿈 문자(`\n`)를 따로 설정해준 이유는 제목의 마지막 폰트가 줄바꿈 문자에 맞춰지게 되어 제목이 길어지면 제목이 겹치게 되는 상황이 발생했기 때문입니다.
     줄바꿈은 되지 않았지만 제목의 길이가 길어진 경우 제목의 마지막 부분이 줄바꿈 문자이기 때문에 그에 맞춰 설정되는 것은 아닌가 추측했습니다.(영어는 해당사항이 없었습니다.)
    > 
    
  ![](https://i.imgur.com/odgUy9G.gif)
    
    ```swift
    private func setTextView(memo: Memo) {
        let attributtedString = NSMutableAttributedString(string: memo.entireContent)
        let entireContent = memo.entireContent as NSString
            
        guard let title = memo.title else {
            textView.attributedText = attributtedString
            return
        }
    
        if let body = memo.body {
            attributtedString.addAttributes(headerAttributes, range: entireContent.range(of: title))
            attributtedString.addAttributes(headerAttributes, range: entireContent.range(of: "\n"))
            attributtedString.addAttributes(bodyAttributes, range: entireContent.range(of: body))
            textView.attributedText = attributtedString
        } else {
            attributtedString.addAttributes(headerAttributes, range: entireContent.range(of: title))
            textView.attributedText = attributtedString
        }
    }
    ```
    
- 입력 중인 부분이 첫 줄바꿈 이후 즉, 본문인지 제목인지를 판단하여 폰트를 변경해 주었습니다.
    
    ```swift
    func textView(_ textView: UITextView, shouldChangeTextIn range: NSRange, replacementText text: String) -> Bool {
        let textAsNSString = self.textView.text as NSString
        let replaced = textAsNSString.replacingCharacters(in: range, with: text) as NSString
        let boldRange = replaced.range(of: "\n")
        if boldRange.location <= range.location {
            self.textView.typingAttributes = self.bodyAttributes
        } else {
            self.textView.typingAttributes = self.headerAttributes
        }
        
        return true
    }
    ```
    

### < Popover >

- 아이패드 전용 앱이었기 때문에 Popover를 사용하여 수정 및 삭제가 가능하도록 구현했습니다.
- Popover의 경우 화면의 다른 부분을 탭했을 때 Popover를 닫을 수 있기 때문에 Cancel Action의 경우 따로 구현해주지 않았습니다. 
deprecated된 문서이긴 하나 [[UIActionSheet 문서](https://github.com/yagom-academy/ios-cloud-notes/compare/%5B%3Chttps://developer.apple.com/documentation/uikit/uiactionsheet%3E%5D(%3Chttps://developer.apple.com/documentation/uikit/uiactionsheet%3E))]([https://developer.apple.com/documentation/uikit/uiactionsheet](https://developer.apple.com/documentation/uikit/uiactionsheet))에서도 다음과 같이 나와 있었기에 Cancel을 구현하지 않아도 괜찮다고 판단했습니다.
    
    > Because taps outside the popover dismiss the action sheet without selecting an item, this results in a default way to cancel the sheet. Including a cancel button would therefore only cause confusion.
    > 
- Popover를 띄우는 위치를 정해주기 위해 popoverPresentationController의 프로퍼티를 사용했습니다. (`sourceView`, `barButtonItem`)
    
    ```swift
    @objc func presentPopover(sender: UIBarButtonItem) {
        let alert = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
        •••
        alert.popoverPresentationController?.barButtonItem = sender
        •••
    }
    ```
    

## ❓   질문할 내용

### < Cell Swipe시 선택된 Cell의 selection 유지 >

- Cell Swipe시 deselect 되는 문제를 해결하기 위해서 어떤 것을 알고 접근하면 좋은지 도움을 얻고 싶습니다.
- 선택된 Cell이 있는 상태에서 Cell을 Swipe할 때 Cell의 selection을 유지하고 싶었습니다.
- 그래서 아래의 코드를 통해 선택한 Cell의 indexPath를 저장해놓은 뒤 selectRow메서드를 통해 선택 상태를 유지하고자 했습니다.
    
    ```swift
    private var selectedIndexPath: IndexPath?
    
    private func changeSelectedCell(indexPath: IndexPath) {
        guard let splitViewController = splitViewController as? MainSplitViewController else { return }
        let selectedMemo = memos[indexPath.row]
        splitViewController.updateMemoContentsView(with: selectedMemo)
        self.selectedIndexPath = indexPath
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        changeSelectedCell(indexPath: indexPath)
    }
    
    func tableView(_ tableView: UITableView, willBeginEditingRowAt indexPath: IndexPath) {
        tableView.selectRow(at: selectedIndexPath, animated: false, scrollPosition: .none)
    }
    
    func tableView(_ tableView: UITableView, didDeselectRowAt indexPath: IndexPath) {
        selectedIndexPath = nil
    }
    ```
    
- 그러나 처음 Cell을 Swipe 할 때 일시적으로 isSelected가 false로 변경되는 것을 `lldb`를 통해 확인했습니다.
    
![](https://i.imgur.com/Ec7l3aA.gif)
    
- 처음 다른 Cell을 Swipe할 때 왜 isSelected가 false가 되는지 정확하게 어느 시점에 변경이 되는지 찾을 수가 없었습니다.
- Cell Swipe시 deselect 되는 문제를 해결하기 위해서 어떤 것을 알고 접근하면 좋은지 도움을 얻고 싶습니다.

### < persistentContainer 선언 방식 >

- persistentContainer를 생성하는 대부분의 예제(여태까지 본 모든 예제)에서 AppDelegate의 lazy var로 선언하고 있었습니다
- 하지만 저희가 생각하기론, static으로 선언하는게 사용이 편리하고, AppDelegate은 어차피 해제되지 않기에 인스턴스 프로퍼티로 선언하더라도 메모리 관점에서 유리하지 않을 것 같아서 굳이 lazy var를 사용하는 이유가 있는지 의문이 들었습니다
- 혹시 이 부분에 대해 Ryan은 어떻게 생각하시는지 궁금합니다. 저희가 뭔가 놓치고 있는 관점이 있는 걸까요?
    
    ```swift
    // lazy var로 작성된 이유가 뭘까?
    // static let도 가능한데..
    lazy var persistentContainer: NSPersistentCloudKitContainer = {
      let container = NSPersistentCloudKitContainer(name: "CloudNotes")
      container.loadPersistentStores(completionHandler: { (storeDescription, error) in
          if let error = error as NSError? {
              fatalError("Unresolved error \(error), \(error.userInfo)")
          }
      })
      
      return container
    }()
    ```
    

### < 키보드에 따른 화면 크기 변경 >

- 키보드가 올라올 경우 기존의 view가 가려지지 않도록 size를 줄이거나 scroll을 조정해주는게 필요했습니다
- 찾아보니 이를 구현하기 위한 다양한 방법이 존재했습니다. 다른 팀의 경우 scrollview를 상속받는 tableView와 textView의 bottomInset을 적용하는 경우도 있었고, 저희는 키보드 관련 notification에 observer를 등록하여 키보드 크기만큼 splitview의 size를 줄이는 방식을 택했습니다
- 하지만, 동작은 잘 하는 것 같은데 찾아낸 모든 방법들이 다소 어거지스러운 면이 있는 것 같다고 느꼈습니다. 혹시 Ryan은 과거에 이를 구현하신 적이 있는지와 경험이 있으시다면 어떻게 구현하셨는지 궁금합니다
    
    (iOS 15부터는 `keyboard layout guide` 란게 생겼다고 하니 오토레이아웃을 걸면 될 것 같네요!)
    

### < 다른 메모를 선택하더라도 키보드가 사라지지 않는 문제 >

- 일반적인 메모 App의 경우, [...]

2022-02-17 17:17 UTC, ryan-son requested changes
호댕, 요한, 아샌, CoreData는 지금까지 다루었던 프레임워크와는 다른 맥락의 내용을 이해해야해서 학습이 쉽지 않았을텐데 요구 기능을 훌륭히 구현하셨네요! 고생 많으셨습니다.

구현하신 구조를 PR에 잘 정리해주셔서 변경된 구조 파악에 많은 도움이 되었습니다. 

이번 리뷰는 구현하신 내용에는 제시할 의견이 많지 않아 PR해주신 내용과 질문주신 사항에 대해 더 많은 이야기를 나누어보려 합니다.

## 질문드리고 싶은 것

> CoreDataProperties에 추가적으로 연산 프로퍼티를 추가해야 했기에 `Manual/None`으로 설정했습니다.
#### 1. 코어데이터 모델의 `Codegen`의 `Manual/None` 속성을 사용해보신 것으로 이해되네요. 
#### - 나머지 두 가지 옵션에 대해서도 알아보셨나요? 
#### - 네트워크 통신을 위해 `Codable` 프로토콜을 채택하려 한다면 어떤 옵션을 선택하는 것이 좋을까요?

## 질의응답

#### 1. < Cell Swipe시 선택된 Cell의 selection 유지 >
1. 왜 `setSelected(_:animated)`는 예상한대로 동작하지 않는가
정확한 설계 의도는 구현한 당사자가 알고 있겠지만, 제 의견을 말씀드리겠습니다. 여러분들이 학습하셔서 이미 아시겠듯이, UISplitViewController에 나타난 각 화면은 서로 다른 ViewController입니다. 우리는 양쪽 화면을 한꺼번에 보고 있으니 스와이프 액션이 일어나도 셀이 선택되는게 자연스럽다고 생각할 수 있지만, 만약 메모리스트 화면만 볼 수 있는 상황이라면 스와이프 액션을 수행할 때 다른 셀의 선택이 유지되고 있는 것은 부자연스럽다고 생각할 수 있습니다 (해당 화면에서 사용자의 관심은 스와이프한 셀으로 이동하기 때문). 그래서 `setSelected(_:animated:)`의 기본 동작은 스와이프 액션 발생 시 셀 선택이 풀리게끔 설정되어 있는 것이 아닌가 추측합니다.

 2. 그럼 어떻게 해결할 것인가
 접근 방법은 여러분이 하신 것처럼 기존에 구현된 셀 선택 로직이 동작하는 것을 관찰하고 보완하는 방법과, 여러분이 의도한 논리대로 UI를 만드는 것. 이렇게 두 가지가 있을 것 같습니다. 저라면 후자를 선택할 것 같네요. select/deselect의 논리에서 벗어나서 어떤 경우에 선택된 셀처럼 파란 배경/흰 글씨를 유지하여야 하는지, 언제는 아닌지를 분석하여 해당 상황을 true/false의 상황으로 나눈 후에 Cell에 해당 상태를 기록하기 위한 프로퍼티를 만들고 외부에서 해당 상황이 발생할 때 상태를 변경하여 배경과 글자색과 같은 설정값을 변경하도록 하는 것입니다. 정확히 원하는 것이 있다면 새로운 논리로 이렇게 구현할 수 있다고 생각해요.

#### < persistentContainer 선언 방식 >
여러분께서 말씀하셨듯이 타입프로퍼티나 lazy var는 호출할 때 초기화됩니다. 다만 이들의 관점은 인스턴스가 `AppDelegate`에 위치하여 메모리에서 해제되지 않으니 메모리 관점에서 유리하지 않다는 방식의 접근이 아니라 당장 필요하지 않은 것을 초기화하느라 다른 곳에 리소스를 제공하지 못하는 상황을 방지하기 위한 관점이 크다고 생각합니다. 

#### 그럼 누구를 언제 사용하여야 하는가?
지연 초기화라는 관점에서는 둘 모두 동일하다고 한다면 누구를 언제 사용하여야 하는가라는 의문이 남습니다. 여러분과 이야기 나누어보고 싶은 주제인데, 먼저 제 의견을 말씀드릴게요.
저의 경우에는 싱글턴, 글로벌 상수와 같이 앱 내부에 공유하는 자원이 필요한 경우에 타입 프로퍼티를 활용하고, 사용 빈도가 높지 않은 비싼 인스턴스 프로퍼티를 정의하는데 lazy var를 활용합니다 (지연 초기화의 특성을 이용해 인스턴스 프로퍼티/메서드를 활용하여 자신의 초기화에 활용하 것은 그 방향이 더 낫다고 판단되는 경우가 아니라면 지양하고자 생각하고 있습니다). 

#### 타입프로퍼티로 선언해서 lazy var 보다 편리하게 사용하고 싶은데 문제 있나?
현재 예상되는 문제점은 없습니다. 코어데이터를 다루는데 유의해야할 점은 컨테이너를 어떤 형식으로 두는지보다 `NSManagedObjectContext (MOC)`를 정의한 스레드에서 이를 활용한 작업 (save, update, delete, create 등)을 하는가 입니다. 현재는 MOC를 통해 무거운 작업을 할 소요가 없어 멀티스레딩에 대해 고려해보지 않아도 문제가 없지만, 그러한 작업이 발생한다면 반드시 이 내용을 고려해야 앱 크래시를 회피할 수 있습니다. 여러분이 사용하고 계신 `[viewContext](https://developer.apple.com/documentation/coredata/nspersistentcontainer/1640622-viewcontext)`는 어떤 형식의 MOC인지 파악해보시고, 요구한 스레드에서 사용하고 있는지 점검해보시기 바랍니다. 그리고 이후에 시간이 된다면 멀티스레딩 환경에서 어떻게 MOC를 다루어야할지, 어떤 방법이 있는지 알아보시면 많은 도움이 될 것 같습니다. [참고자료1](https://developer.apple.com/documentation/coredata/using_core_data_in_the_background), [참고자료2](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreData/Concurrency.html), [참고자료3](https://www.haibosfashion.com/posts/apply%20muliti-threading%20in%20coredata/)
- 사용에 문제는 없지만, 여러분이 생각하는 장단점은 어떤 것이 있나요?

#### < 키보드에 따른 화면 크기 변경 >
저도 키보드 높이만큼 inset을 추가해서 문제를 해결했었던걸로 기억해요. 이 방법이 세련되지 않다고 생각해서 keyboard layout guide를 추가한게 아닐까요? 😋

#### < 다른 메모를 선택하더라도 키보드가 사라지지 않는 문제 >
새로운 키워드 하나 공부해봅시다~! 회의실에서 어떤 내용인지, 어떻게 활용했는지 설명해주시면 재미있는 경험을 공유할 수 있겠네요~ 
- [cancelsTouchesInView](https://developer.apple.com/documentation/uikit/uigesturerecognizer/1624218-cancelstouchesinview)

더 궁금한 것이 있으시거나 리뷰 내용 중에 이해가 되지 않는 내용이 있으시면 언제든지 말씀해주세요~ 😊

2022-02-17 17:17 UTC, ryan-son commented on CloudNotes/CloudNotes/Model/CoreDataManager.swift
> +    weak var memoContentViewController: MemoReloadable?
delegate 형식으로 사용하고 있는데 이름으로 보면 구체적인 타입처럼 느껴지네요. 이 상태가 더 좋다면 유지해도 괜찮습니다.

2022-02-17 17:17 UTC, ryan-son commented on CloudNotes/CloudNotes/Model/CoreDataManager.swift
> +    private init() { }
싱글턴 패턴을 활용하셨네요. 앱에서 유일한 공유 인스턴스이고, 어디서든지 호출하기 용이한 반면에 어떤 단점이 있었나요? 추가적인 장점이 있다면 공유해주세요~

2022-02-17 17:17 UTC, ryan-son commented on CloudNotes/CloudNotes/Model/CoreDataManager.swift
> +            let context = AppDelegate.persistentContainer.viewContext
`load()`, `delete(data:)`, `update(data:title:body:)`, `create()` 모두 `persistentContainer`가 가진 `viewContext` (`NSManagedObject`)가 필요하다면 이 타입 내부에 인스턴스 프로퍼티로 둘 수도 있을 것 같은데, `AppDelegate`에 타입 프로퍼티로 둔 의도는 무엇인가요~?

2022-02-17 17:17 UTC, ryan-son commented on CloudNotes/CloudNotes/Model/CoreDataManager.swift
> +            return try context.fetch(Memo.fetchRequest()).reversed()
`fetchRequest`에 `predicate` (`NSPredicate`)를 설정하면 특정 프로퍼티를 기준으로 오름/내림차순 정렬하거나 필터링해서 결과를 얻을 수 있으니 참고하세요~

2022-02-17 17:17 UTC, ryan-son commented on CloudNotes/CloudNotes/Model/CoreDataManager.swift
> +            print(error)
이제 UI도 있으니 에러 핸들링을 다른 방식으로 해볼 수 있을 것 같아요.

2022-02-17 17:17 UTC, ryan-son commented on CloudNotes/CloudNotes/View/MemoListTableViewCell.swift
> +        if memo.title == nil || memo.title?.count == 0 {
눈에 띄는 차이는 없겠지만, 일반적으로 성능 상 이점으로 인해 `.count == 0` 보다는 `isEmpty`를 선호합니다.

[Empty Count - SwiftLintFramework 0.46.2 Docs](https://realm.github.io/SwiftLint/empty_count.html)

#### 유사사례
```swift
var isNotEmpty: Bool {
    return !isEmpty
}

// 1
// elements.count > 0
elements.isNotEmpty

// 2
// elements.filter { $0 == something }.first
elements.first(where: { $0 == something })

// 3
// elements.filter { $0 == something}.isEmpty
elements.contains(where: { $0 == something })

// 4
// elements.first(where: { $0 == something }) != nil
elements.contains(where: { $ == something })

...
```

2022-02-17 17:17 UTC, ryan-son commented on CloudNotes/CloudNotes/View/MemoListTableViewCell.swift
>          dateLabel.text = memo.convertedDate
여러분은 어떤 경우에 연산프로퍼티로, 어떤 경우에 메서드로 정의하시나요~?

2022-02-17 17:17 UTC, ryan-son commented on CloudNotes/CloudNotes/ViewController/MemoListViewController.swift
>      }
`MemoReloadable` 프로토콜을 채택한 extension으로 따로 분리해두는 것도 나쁘지 않겠어요.

2022-02-17 17:17 UTC, ryan-son commented on CloudNotes/Memo+CoreDataClass.swift
> +public class Memo: NSManagedObject {
struct로 만든 엔티티를 코어데이터 엔티티로 변경하시면서 어떤 장단점이 있다고 느꼈나요?

2022-02-17 17:17 UTC, ryan-son commented on CloudNotes/CloudNotes/AppDelegate.swift
>          container.loadPersistentStores(completionHandler: { (storeDescription, error) in
이후에 시간이 된다면 [`NSFetchedResultsController`](https://developer.apple.com/documentation/coredata/nsfetchedresultscontroller)로 구현해보는 것도 추천드려요. 
공식문서에서처럼 `NSFetchedResultsControllerDelegate`의 [`controllerDidChangeContent(_:)`](https://developer.apple.com/documentation/coredata/nsfetchedresultscontrollerdelegate/1622290-controllerdidchangecontent) 메서드만 작성해도 (구현 안해도 됨) 변경사항들을 자동으로 인식해서 반영해주는 똑똑한 타입이에요.
![image](https://user-images.githubusercontent.com/69730931/154523745-09d8c008-a038-4741-b360-77ae2c6fbebc.png)

2022-02-21 06:59 UTC, ICS-Asan commented on CloudNotes/CloudNotes/Model/CoreDataManager.swift
> +    weak var memoContentViewController: MemoReloadable?
현재 상태를 유지하는 것으로 결정했습니다.
다른 뷰컨이 들어올 것 같다고 판단되지 않고 정해져있다면 어느정도 구체적인 네이밍도 괜찮다고 생각해서 이렇게 정했습니다.
혹시 라이언은 어떤 네이밍이 떠오르시는지 궁금합니다.

2022-02-21 07:06 UTC, ICS-Asan commented on CloudNotes/CloudNotes/Model/CoreDataManager.swift
> +    private init() { }
저희가 생각했을 때 저희가 구현해야하는 조건에서는 싱글턴 패턴을 사용했을 때 눈에 띄는 단점이 없다고 생각해서 싱글턴 패턴을 사용했습니다.
저희 코드에서 싱글턴의 장점은 CoreDataManager가 사용되는 뷰컨마다 인스턴스를 생성해주지 않아도 되고 만약 새로운 뷰컨이 추가되더라도 간단하게 사용할 수 있다는 점이 있었습니다.
그리고 메모리 관점에서도 무거운 인스턴스의 경우에는 필요없을 때 해제해주는 것이 좋겠지만 CoreDataManager의 경우에는 가벼워서 메모리 부담이 없을 것이라 판단했습니다.

2022-02-21 07:08 UTC, ICS-Asan commented on CloudNotes/CloudNotes/Model/CoreDataManager.swift
> +            let context = AppDelegate.persistentContainer.viewContext
처음 구현 당시에는 lazy var 와 static let 의 관점에서만 고민을 해서 위치에 대해서는 깊게 생각하지 못했습니다.
리뷰를 보고 고민을 해보니 저희도 CoreDataManager내부에 있는 것이 더 적절하다고 생각해서 위치를 변경하기로 했습니다!

2022-02-21 07:44 UTC, ICS-Asan commented on CloudNotes/CloudNotes/Model/CoreDataManager.swift
> +            return try context.fetch(Memo.fetchRequest()).reversed()
```swift
@nonobjc public class func fetchRequest() -> NSFetchRequest<Memo> {
        let request = NSFetchRequest<Memo>(entityName: "Memo")
        request.sortDescriptors = [NSSortDescriptor(key: "lastModified", ascending: false)]
    
        return request
    }
```
이렇게 구현해봤습니다.
하지만 저희는 제일 최근에 수정된 순서 보다는 생성된 순서로 정렬하는 것이 좋을 것 같다고 생각되어 정렬순서는 유지하기로 했습니다.
그리고 저희가 공부하면서 확인한 바로는 predicate로 필터링은 가능한데 정렬을 따로 지원을 하지 않는 것 같았습니다.
정렬이 필요할 때에는 `NSSortDescriptor`를 사용하는 것이 좋을까요?
predicate로 하는 방법을 찾지 못했는데 어떻게 정렬기능을 사용할 수 있는지 힌트를 알려주시면 조금 더 알아볼 수 있을 것 같습니다!!

2022-02-21 08:09 UTC, ICS-Asan commented on CloudNotes/CloudNotes/Model/CoreDataManager.swift
> +            print(error)
에러 발생 시 뷰컨에서 Alert를 띄울 수 있도록 구현했습니다!!
```swift
func delete(data: Memo, errorHandler: (Error) -> Void) {
        context.delete(data)
        do {
            try context.save()
            memoListViewController?.reload()
            memoContentViewController?.reload()
        } catch {
            errorHandler(error)
        }
    }

private func presentDeleteAlert(currentMemo: Memo) {
        let alert = UIAlertController(title: "진짜요?", message: "정말로 삭제하시겠어요?", preferredStyle: .alert)
        let cancelAction = UIAlertAction(title: "취소", style: .cancel, handler: nil)
        let deleteAction = UIAlertAction(title: "삭제", style: .destructive) { _ in
            CoreDataManager.shared.delete(data: currentMemo) { error in
                self.presentErrorAlert(errorMessage: error.localizedDescription)
            }
        }
        alert.addAction(cancelAction)
        alert.addAction(deleteAction)
        present(alert, animated: true)
    }
```

2022-02-21 08:19 UTC, yanghojoon commented on CloudNotes/CloudNotes/View/MemoListTableViewCell.swift
> +        if memo.title == nil || memo.title?.count == 0 {
말씀해주신대로 count를 0과 비교하기 보단 isEmpty를 사용했습니다.

2022-02-21 08:32 UTC, yanghojoon commented on CloudNotes/CloudNotes/View/MemoListTableViewCell.swift
>          dateLabel.text = memo.convertedDate
일단 파라미터가 존재하지 않고 반드시 return 값이 있는데 해당 리턴 값이 사용되야 할 때 연산 프로퍼티를 고려하는 것 같습니다. 특히, return 값이 프로퍼티의 성격을 가지고 사용되는 값이라면 네이밍도 프로퍼티처럼 해서 자연스럽게 사용할 수 있도록 하고 있습니다.

2022-02-21 08:37 UTC, yanghojoon commented on CloudNotes/CloudNotes/ViewController/MemoListViewController.swift
>      }
다른 것들도 프로토콜을 채택한 부분은 extension으로 분리해줘서, 이 부분도 통일성 있게 수정했습니다!

2022-02-21 08:49 UTC, yanghojoon commented on CloudNotes/Memo+CoreDataClass.swift
> +public class Memo: NSManagedObject {
단순히 데이터를 내려받을 때에는 구조체로 할 때나 클래스로 할 때나 큰 차이가 없지만, CRUD를 적용해서 엔티티를 변경할 때에는 클래스가 관리가 더 편하다는 장점이 있었습니다. 
이에 비해 클래스를 사용할 경우 다양한 곳에서 인스턴스에 접근할 때 관리를 따로 해주지 않는다면 메모리 해제 혹은 의도치 않은 변경(Side effect)이 발생할 수 있다는 단점이 존재하지만, 현재로선 그렇게 큰 단점으로 와 닿지는 않았습니다.

2022-02-21 09:28 UTC, ICS-Asan commented
리뷰 감사합니다 라이언!!
맨 처음 달아주신 코멘트에 대한 답은 여기에 적어두겠습니다!!
- < 코어데이터 모델의 Codegen의 속성 >
    ```swift
    // Category/Extension
    Class파일만 수정 가능
    Codable 채택 가능
    // Class Definition
    CoreData파일의 attribute에 존재하는 프로퍼티만 사용, 수정 불가
    // Manual/None
    두 파일(Class, Properties) 모두 수정가능
    Codable 채택 가능
    ```
    > 간단하게 위와 같이 알아봤습니다!
    > 그런데 아직 Class파일과 Properties 파일의 차이는 정확하게 알아내지 못했습니다.
    > class와 extension으로 구현되어있는데 extension에 구현 되어있는 것을 class에 옮겨 구현해도 정상 작동이 되는 것을 확인했습니다.
    > 처음 CoreData파일에서 Codegen으로 파일을 생성할 때 두 파일이 생성되는 이유와 굳이 class가 구현된 내부는 비워둔 채 Properties파일에 extension으로 내부에 자동으로 구현되는 코드가 작성되어 파일이 생성되는 이유를 찾지 못했습니다.
    > 저희가 찾은 차이점을 비교해보고자 Category/Extension으로 변경한 뒤 필요한 작업들을 Class파일 내부에서 구현을 해도 문제가 없었습니다.
    > 이것들의 차이를 둔 이유가 무엇인지 두 파일간의 차이가 무엇인지 검색을 해봐도 명확한 답을 얻을 수 없었습니다.
    > 어떻게 알아보면 좋을까요?

- < Cell 선택상태 유지 >
    > 같이 고민을 해봤는데 라이언이 말씀해주신 접근 방법으로 구현을 할 수 있을 것 같다는 생각이 들었고 좋은 방법이라는 생각이 들었습니다.
    > 하지만 어느정도 시간이 소요될 것이라 생각되고 아직 진행하지 못한 STEP들을 진행해보고 싶다는 마음이 있어 추후에 진행을 하면서 여유가 있을 때 추가로 구현해보고 싶습니다! 
    
- < lazy var VS static let >
    > 저희는 둘을 선택하는 기준을 인스턴스 프로퍼티/타입 프로퍼티의 관점에서 정했습니다.
    > 생성빈도/비용에 따라 선택하는 것이 좋을 것 같다고 판단했습니다.
    > 사용하고자 하는 프로퍼티가 자주 생성되는데 비용이 많이 든다면 메모리를 일부 차지하더라도 전역에 있는것이 더 효율적일 것이라 판단했습니다.
    > 이와 같은 이유로 자주 생성될 필요도 없고 비용이 많이 들지 않는다면 굳이 전역에 두는 것 보다는 필요한 경우에만 사용하고 메모리에서 해제시키는 것이 좋을 것 같다고 생각했습니다.
    > 그리고 현재의 경우에 전역으로 사용되는 것이 편하고 AppDelegate내부 인스턴스 프로퍼티로 존재하는 경우 사용시점마다 아래와 같이 AppDelegate을 찾아가는 과정이 필요합니다.
    ```swift
    ex)
    guard let delegate = UIApplication.shared.delegate as? AppDelegate else { return }
    ```
    > 그래서 static let으로 구현해두는 것이 적합하다고 생각했습니다!
    
- < 다른 메모를 선택하더라도 키보드가 사라지지 않는 문제 >
    > MainSplitViewController에 UITapGestureRecognizer을 추가하여 다른 부분을 터치하면 키보드가 내려가게 하고 cancelsTouchesInView = false로 두어 기존 다른 탭 이벤트도 정상적으로 수신할 수 있도록 처리했습니다!
    ```swift
    extension MainSplitViewController {

        func hideKeyboardWhenTappedBackground() {
            let tapEvent = UITapGestureRecognizer(target: self, action: #selector(dismissKeyboard))
            tapEvent.cancelsTouchesInView = false
            view.addGestureRecognizer(tapEvent)
        }

        @objc func dismissKeyboard() {
            contentViewController.view.endEditing(true)
        }

    }
    ```

2022-02-24 01:21 UTC, ryan-son commented
아샌, 호댕, 요한, 이번 스텝도 고생 많으셨습니다. 

이틀 전에 디스코드에서 이야기 나누고 의견 드린 것에서 더 첨언할 내용은 없어보여 머지합니다.

추가로 궁금한 내용 있으시면 말씀해주세요! 다음 스텝도 화이팅입니다~

2022-02-24 01:21 UTC, merged