동기화 메모장 [STEP 2] 호랭이, 제리
yagom-academy/ios-cloud-notes pull request #92
Opened 2022-02-18 03:21 UTC by horeng2

안녕하세요~ 쿠마! @leejun6694 

호랭이 @horeng2 , 제리 @llghdud921 입니다~ 

이번에 시간이 부족해서 디테일한 기능은 잘 구현되지 못한 것 같습니다..ㅠ 뷰 너무 어려워요....
이번 스텝도 잘 부탁드립니다...ㅎㅎ 항상 감사드려요~! 🙇‍♀️

---
## 구현 화면
![](https://i.imgur.com/JYYPxPV.gif)
![](https://i.imgur.com/odVNjqA.gif)
![](https://i.imgur.com/xCjGfJ5.gif)

## 고민했던 점

### CoreStack과 PersistanceManger 구성

- NSPersistentContainer가 위치한 CoreStack을 singleTon으로 구현하였습니다
- Core Data CRUD를 관리하는 `PersistanceManager` 객체는 데이터를 가지고있어 흐름을 관리하는 측면에서 싱글턴보다는 사용하는 객체에 주입시키는 방식으로 진행하였습니다.

### alert, action을 어느 위치에서 다룰지에 대한 고민

- alert과 action은 ListView와 DetailView 양쪽에 모두 관련되어있는 코드이기 때문에 어느 한쪽에서 다루게 된다면 전달과정이 복잡해지는 것에 대한 고민을 했고, SplitView에서 관리를 하자는 결론을 내렸습니다. 기존에 데이터의 전달 역할로 SplitView가 사용되고 있기 때문에 이미 중간에 연결역할을 하고 있는 상태이기도 했고, 양쪽 뷰의 정보가 모두 필요하기 때문에 이 위치가 적절하다고 생각했습니다.

### 코어데이터를 관리할 때 noteInformation 또는 Note 엔티티 모델을 사용하는 적절한 경우에 대한 고민

- `PersistantManager`의 각 메서드에서 어떤 모델을 이용해서 작업을 실행할지에 대한 고민이 있었습니다. save의 경우는 최초 데이터를 저장하는 것이기 때문에 `NoteInformation` Model을 이용해서 setValue 형태로 저장을 실행하였고, delete, fetch는 기존의 데이터를 다루는 것이기 때문에 메모장에서 선택된 부분에 해당하는 `Note` 엔티티 모델을 이용하도록 설계하였으며, update는 기존의 데이터와 새로운 데이터가 모두 필요하기 때문에 `NoteInformation`과 `Note`를 둘 다 사용하였습니다.

### 화면 회전 시에 View 위치를 재설정 기능 구현

- 공유 버튼을 눌러 `ActivityView`를 보여줄때 화면 중간에 위치하기 위해 `UIScreen.main.bounds` 를 이용하여 위치를 적용하였습니다.
- 화면 회전 시 회전 되기 전 UIScreen값으로 위치가 지정되어 `viewWillTransition` 를 이용해 회전시마다 위치를 재설정 하는 기능을 구현하였습니다.

---

## 해결이 되지 않은 점

### Textview에 text 입력 시에 TextView font를 적용하는 기능

- TextView delegate를 이용하여 `textViewDidChange` 나 `shouldChangeTextIn`시에 textView의 font를 바꾸어서 적용하려는 시도를 하였습니다.
- `textViewDidChange` 에 `delegate`를 통한 Coredata save 기능이 구현되어 있어 코드 흐름이 복잡해지고 Font가 적용되더라도 text를 작성하고나서 조금후에 font가 적용되는 현상때문에 기능을 구현하지 못하였습니다.

![스크린샷 2022-02-18 오전 11 48 31](https://user-images.githubusercontent.com/87305744/154611343-416f0e4f-e58b-407e-8567-a5b2a7328b57.png)

   
실제 메모앱과 같이 제목 부분은 Bold체, 내용부분은 일반 텍스트로 구현하고싶은데요ㅠ 혹시 저희 접근방식이 잘못된 것인지 좋은 방법이 있는지 여쭤봅니다 
    

---

## 조언을 얻고 싶은 부분

### 새 노트를 추가할 때 비어있는 노트 내용에 공백줄이 여러개 들어가는 현상

저희 코드의 구조에서는 title과 body를 코어데이터에서 불러와서 출력할 때, 개행으로 구분을 할 수 있도록 attributedString을 사용했습니다. title과 body를 연결하면서 중간에 \n을 추가하는 방식인데, 이 부분 때문에 새 노트를 추가할 때 노트 내용이 비어있음에도 불구하고 공백줄이 2개가 생겼습니다. 따라서 빈 노트에 내용을 작성하기 위해서 클릭했을 때 첫 줄의 맨 앞이 아닌 2번째 줄에 커서가 위치하는 문제가 있었습니다.

해결방법으로는 아래의 2가지를 생각해봤습니다.

1. attributedString을 할 때 비어있는 노트의 경우 예외처리를 한다.
2. 비어있는 노트의 경우 커서의 위치를 맨 앞으로 설정한다.

두가지 방법 모두 시도해보았으나 2번의 방법은 실패해서 1번의 방법으로 작동되고 있습니다.   selectedTextRange와 beginningOfDocuments (Main.async에서 진행)를 이용해서 커서를 뷰의 맨앞으로 이동하는 방식을 시도해보았지만 잘 적용이 안되었습니다ㅜㅜ 

다른 방식을 사용해야 하는 것인지, beginningOfDocuments 사용 방법에 문제가 있는 것인지 조언 부탁드립니다.🥲

```swift
noteDetailTextView.selectedTextRange = noteDetailTextView.textRange(from: noteDetailTextView.beginningOfDocument, to: noteDetailTextView.beginningOfDocument)
```

2022-02-20 17:57 UTC, leejun6694 requested changes
호랭이, 제리 step 2 구현 고생 많으셨습니다.
리뷰 남긴 내용이 있는데, 확인 부탁드립니다.
확인 후에 좀 더 구조에 대해 얘기 나눠보면 좋겠네요!

++ 해결되지 않은 점과 조언이 필요한 부분은 월요일에 디스코드로 같이 확인해보면 어떨까요?

2022-02-20 17:57 UTC, leejun6694 commented on CloudNotes/CloudNotes/Extension/String+Extension.swift
> +        return String(self[startIndex ..< endIndex])
범위 표기 내 띄어쓰기가 없는 코드를 많이 접했던 것 같네요.
확인 부탁드려요~

2022-02-20 17:57 UTC, leejun6694 commented on CloudNotes/CloudNotes/Extension/String+Extension.swift
> +    func substring(from: Int, to: Int) -> String {
재밌는 method 네요 : )

2022-02-20 17:57 UTC, leejun6694 commented on CloudNotes/CloudNotes/Extension/UIViewController+extension.swift
> +        let deleteAction = UIAlertAction(title: titles.1, style: .destructive, handler: deleteHandler)
`titles 의 0 과 1번째 값`들이 각각 `shared`, `delete` 에 쓰이고 있지만, 외부에서 `showActionSheet` method 를 호출할 땐 이와 같은 점을 확인하기 어려울 것 같습니다.
좀 더 친절한 method 로 구현해보면 어떨까요?

2022-02-20 17:57 UTC, leejun6694 commented on CloudNotes/CloudNotes/Utility/CoreDataStack.swift
> +    lazy var persistentContainer: NSPersistentContainer = {
`private` 으로 바꿔도 되지 않을까 싶네요 : )

2022-02-20 17:57 UTC, leejun6694 commented on CloudNotes/CloudNotes/Utility/PersistantManager.swift
> +        let context = CoreDataStack.shared.persistentContainer.viewContext
28번째 줄 : `let context = CoreDataStack.shared.context`

2022-02-20 17:57 UTC, leejun6694 commented on CloudNotes/CloudNotes/Utility/PersistantManager.swift
> +class PersistantManager {
`class` 로 구현한 이유가 궁금합니다~~!

2022-02-20 17:57 UTC, leejun6694 commented on CloudNotes/CloudNotes/Utility/PersistantManager.swift
> +        object.setValue(noteInformation.title, forKey: "title")
key 값들도 어딘가 정의되어 사용된다면, 여러 장점들이 있을 것 같네요!

2022-02-20 17:57 UTC, leejun6694 commented on CloudNotes/CloudNotes/Utility/PersistantManager.swift
> +        object.setValue(noteInformation.title, forKey: "title")
어디가 좋을까요??

2022-02-21 05:34 UTC, llghdud921 commented on CloudNotes/CloudNotes/Extension/String+Extension.swift
> +        return String(self[startIndex ..< endIndex])
수정완료했습니다~! 감사합니다!

2022-02-21 05:42 UTC, horeng2 commented on CloudNotes/CloudNotes/Extension/UIViewController+extension.swift
> +        let deleteAction = UIAlertAction(title: titles.1, style: .destructive, handler: deleteHandler)
호출부에서 명확하게 확인할 수 있도록 각각의 프로퍼티로 분리했습니다!

2022-02-21 05:46 UTC, horeng2 commented on CloudNotes/CloudNotes/Utility/PersistantManager.swift
> +class PersistantManager {
데이터가 필요한 위치에서 note 프로퍼티를 참조하여 동일한 데이터를 사용할 수 있도록 class로 구현했는데요, 이 부분은 같이 이야기 나누어보고 싶어요🧐

2022-02-21 05:53 UTC, horeng2 commented on CloudNotes/CloudNotes/Utility/PersistantManager.swift
> +        object.setValue(noteInformation.title, forKey: "title")
`Note` class 내부에 `static` 프로퍼티로 선언해서 `Note.titlekey` 와 같이 사용할 수 있게 했는데요, `CoreDataPropoperties` 내부에 이런 식으로 선언해서 사용해도 괜찮은 건지, 일반적인지에 대한 의문은 남았습니다.🧐 이 부분도 같이 이야기 나눌 때 질문드려도 될까요?

2022-02-21 05:54 UTC, horeng2 commented on CloudNotes/CloudNotes/Utility/CoreDataStack.swift
> +    lazy var persistentContainer: NSPersistentContainer = {
네 수정했습니다!

2022-02-21 05:54 UTC, horeng2 commented on CloudNotes/CloudNotes/Utility/PersistantManager.swift
> +        let context = CoreDataStack.shared.persistentContainer.viewContext
휴먼에러로 인한 중복코드 삭제했습니다..👀

2022-02-22 14:16 UTC, merged