동기화 메모장 [STEP 3] 고사리, 숲재
yagom-academy/ios-cloud-notes pull request #94
Opened 2022-02-22 07:33 UTC by forestjae

@kcharliek 

 찰리 안녕하세요! Step3 구현하여 PR드립니다.

## 0. 구현내용

- [X]  SwfityDropbox라이브리러리 사용을 통한 메모 업로드 및 불러오기 기능 구현(최종 백업시간 표시)
- [X]  DropBox 로그인 상태에 따른 액션시트 구현 (로그인/ 로그아웃 기능)
- [X]  타이머를 사용한 자동 업로드 (주기: 15초)
- [X]  멀티태스킹 중, 리스트의 메모를 선택시 편집 화면 제공
![Simulator Screen Recording - iPad Pro (12 9-inch) (5th generation) - 2022-02-22 at 16 00 49](https://user-images.githubusercontent.com/76479760/155083873-7ddfa833-a4bc-4d57-acf7-0dde86cb0624.gif)

---

## 1. 고민했던 점

### 1-1. 동기화 방식

- 공유 버튼 제공을 통해 사용자가 수동 백업을 진행할 수 있도록 기능을 제공하였습니다.
- Timer를 활용하여 일정 주기마다 자동으로 백업이 진행, 사용자가 원할 때 다운로드가 가능하도록 구현하였습니다.

### 1-2. DropboxManager 타입

- DropboxManager의 client변수가 SwiftyDropbox의 `DropboxClientsManager.authorizedClient` 변수를 참조하기 때문에 Class로 설계하였습니다.

---

## 2. 해결이 되지 않은 점

### 2-1. 타이머의 발동 조건

DropboxManager에 client 변수를 생성해 해당 client의 값이 변경될때 검증하고 Noti를 보내어 타이머의 트리거로 활용하려했습니다. 그러나 `DropboxClientsManager.authorizedClient` 라는 라이브리러의 타입 프로퍼티를 참조하는 client값을 추적하는 property observer가 제대로 동작하지 않는 문제가 있어 해당 구현은 포기하였습니다. 

```swift
var client = DropboxClientsManager.authorizedClient {
        willSet {
            print("감시자 잘 작동하고 있음 \(newValue)")
            NotificationCenter.default.post(
                name: NSNotification.Name("ClientStatusChanged"),
                object: newValue == nil ? false : true
            )
        }
    }
```

위 구문과 비슷하게 Playground에서 테스트 코드로 실험해 본 결과, 다른 참조타입을 참조하고 있는 변수도 프로퍼티 감시자가 제대로 작동하던데, 위 구문에서 작동하지 않는 이유를 파악하지 못했습니다.

---
감사합니다 !

2022-02-23 06:45 UTC, kcharliek commented
## 해결되지 않은 부분에 대해
1. 타이머의 발동 조건

authorizedClient 를 관찰하려는 목적으로 전달받았습니다. Discord로 말씀드린 것 처럼, 서드파티 SDK가 제공하는 기능 내에서 구현하는 것이 첫번째고요. 그래서 authorized status의 변경을 추적하는 인터페이스가 있는지 확인한번 해보시길 권해드릴게요. 그리고 나서 방법이 없다면 이를 추적하지 않고 구현할 수 있는 방법이 있는지 다시 고민해보시고, 그래도 꼭 필요하다면 KVO 로 접근해보시길 권해드릴게요.

2. 코어데이터 Export

아주 창의적인 방법이라고 생각합니다. 저는 이렇게 구현할 생각을 해보지 못했어요. 그렇지만 코어데이터 file 원본을 다루는 것은 아주 위험한 방법입니다. 지금은 Memo 단일 Entity니, 통째로 옮겨도 그렇게 동작할 수 있지만 복잡한 앱이라면 Entity가 여러개 될거에요. 그렇다면 Memo 기능 지원을 위해 다른 Entity의 변경까지 함께 일어날 수도 있는 우려가 있네요. 그리고 CoreData File을 통쨰로 저장하겠다는 것은 DropBox와 CoreData간의 의존성이 생기는 것이고요. 안드로이드앱이 있다면 CoreData File을 읽을 방법이 없겠죠. 무엇보다 CoreData File을 직접 다루는 것에 대한 데이터 안정성을 보장할 수 없어요. 애플이 그렇게 해도 괜찮다는 말이 있다면 또 모르겠지만요. 제 생각에는 구현 방법을 바꾸셔야 할 것 같아요. 그렇다면 어떻게 저장해야할까요 ? 저라면 메모의 각 Field를 ';' 로 구분해서 단일 String으로 만들고, 모든 메모를 합칠 때는 &로 구분하는 등. String으로 변환해서 다룰 것 같아요. 앱애서는 이를 다시 파싱하도록 하고요. 이 밖에도 방법은 많을테니 한번 다시 고민해봐주세요.

3. 코어데이터의 NSManagedObject

NSManagedObject를 비즈니스 로직에서 직접 사용해도 괜찮은지 여쭤보셨습니다. 이에 대한 내용은 사전 설계 때 한번 이야기 나눈 것 같은데요. 이유는 여러가지가 있습니다만, 가장 큰 목적은 비즈니스 로직과 CoreData간 의존성을 끊으려는 목적이에요.
이후에 Database를 Realm으로 변경하고싶을 수도 있고요. SQLite로 바꾸고싶을 수도 있잖아요. 그럴 때 NSManagedObject를 비즈니스로직에서 직접 가져다 썼을 경우, 모델을 다루는 모든 코드를 변경해야할거에요. 그리고 NSManagedObject를 들고 있다면 DB를 직접 변경할 수도 있거든요. 그런 점에서 사이드이펙트가 날 수도 있고요. 여러 이유가 있겠지만 의존성을 끊는다는 측면이 가장 포인트가 될 것 같아요.

2022-02-23 11:07 UTC, kcharliek commented on CloudNotes/CloudNotes/Domain/NoteList/NoteListViewController.swift
> +        let alert = UIAlertController(
Alert를 계속 들고 있을 이유가 있을까요 ? 

반복해서 노출할 케이스가 거의 없고, dismiss와 동시에 release될 것을 생각하면 저는 계속 메모리 잡고있을 필요가 없어보입니다.

2022-02-23 11:07 UTC, kcharliek commented on CloudNotes/CloudNotes/Domain/NoteList/NoteListViewController.swift
> +        let alert = UIAlertController(
uploadFailureAlert 동일합니다.

2022-02-23 11:09 UTC, kcharliek commented on CloudNotes/CloudNotes/Domain/NoteList/NoteListViewDelegate.swift
> +    func dropBoxLastUpdated() -> String
지금도 괜찮습니다만, DropBox와의 의존성을 떼보는 것도 공부가 될 것 같습니다. 
Protocol을 두어 어디든 업로드 할 수 있도록요.

2022-02-23 11:11 UTC, kcharliek requested changes
코어데이터 원본 파일을 업로드 하는 것이 아닌, 각 Model을 업로드 하는 식으로 수정하는 것을 필수 수정 내용으로 하겠습니다.

2022-02-24 06:38 UTC, forestjae commented on CloudNotes/CloudNotes/Domain/NoteList/NoteListViewController.swift
> +        let alert = UIAlertController(
메서드 내부에서 alert를 선언하는 식으로 변경하였습니다.

2022-02-24 06:39 UTC, forestjae commented on CloudNotes/CloudNotes/Domain/NoteList/NoteListViewDelegate.swift
> +    func dropBoxLastUpdated() -> String
Synchronizable 프로토콜을 만들어 객체간 결합도를 약화시켰습니다.

2022-02-25 14:38 UTC, merged