동기화 메모장 [Step2-2] 앨리, 제인, 조이
yagom-academy/ios-cloud-notes pull request #97
Opened 2022-02-23 03:15 UTC by wooyani77

안녕하세요 수박 🍉
@soo941226
앨리, 제인, 조이 입니다.

말씀드린대로 Step2의 전반적인 설계를 수정해서 다시 PR요청 드립니다!
delegate pattern활용 및 역할 분리 등 최대한 data를 한 곳에서 관리하도록 해보았습니다.
부족한 부분이 많겠지만 이번에도 리뷰 잘 부탁드립니다! 😄

감사합니다!

# STEP 2 : 코어데이터 DB 구현

## 2-1 고민했던 것

### 설계

이번 설계의 목적은 아래와 같습니다.

- 데이터를 한곳에서 관리하기
- ListViewController / DetailViewController 에서 model 관련 로직을 최대한 덜어내기
- MVC 디자인 패턴으로 구조 짜기

처음에는 SplitViewController를 이용해서 한 곳에서 data를 관리해주는 방법으로 고민을 했습니다. 하지만, SplitViewController도 ListViewController / DetailViewController와 마찬가지로 ViewController라는 점에서 그 또한 데이터를 관리해주는 역할을 맡기에 부적절하는 생각이 들었습니다. 

고민끝에, DataManager의 인스턴스를 SplitViewController가 가지고 있고, ListVC / DetailVC 에게 전달해주는 방식으로 구현하기로 결정을 했습니다. 

기존에 ListVC / DetailVC에서 Model 관련 로직이 많았던 부분은 모두 DataManager 안으로 옮겨주었습니다. (ex `if indexPath.row < dataManager.memos.count` 이런식으로 조건을 확인하는 부분)

ListVC와 DetailVC는 각각 MemoDataManagerListDelegate, MemoDataManagerDetailDelegate를 채택합니다.

DataManager는 데이터에 변화가 일어날 때 listDelegate / detailDelegate에게 일을 시킵니다.

예를들어 

유저가 셀을 삭제 → 삭제 이벤트를 받은 ListVC가 DataManager의 메모삭제 메서드를 호출 → DataManager는 조건을 확인하여 listDelegate / detailDelegate에게 적절한 일을 시킴 

결과적으로 ListVC / DetailVC은 SplitViewController으로부터 받은 DataManager를 가지고 있고, DataManager는 listDelegate / detailDelegate를 가지고 소통을 하는 구조입니다.

## indexPath를 활용하여 하나의 메서드로 ListVC와 DetailVC에서 메모 삭제

메모를 지울 때 indexPath를 활용해서 지워야 해서 Core Data에서 선택된 메모의 indexPath를 가져오는 방법에 대해 고민하였습니다.

- ListVC의 메모 목록에서 스와이프해서 삭제할때는 선택된 indexPath의 정보를 같이 전달해줄 수 있지만,
- DetailCV의 메모 상세페이지에서 더보기 버튼으로 삭제시에는 선택된 셀의 indexPath를 알 수 없어서

indexPath가 있으면 그대로 사용하고, 없으면 listVC의 selectedCellIndex에서 선택된 셀의 인덱스를 가져와서 listVC의 셀도 지우고 detailVC의 텍스트도 지워주도록 구성하였습니다. 

```swift
final class MemoListViewController: UIViewController {
		func tableView(_ tableView: UITableView,
		               trailingSwipeActionsConfigurationForRowAt indexPath: IndexPath
		) -> UISwipeActionsConfiguration? {
		    let deleteAction = UIContextualAction(style: .destructive, title: "Delete") { _, _, _ in
		        self.dataManager.deleteSelectedMemo(at: **indexPath**)
		    }
		    ...
		}
}
```

```swift
final class MemoDetailViewController: UIViewController {
		private func showDeleteAlert(_ sender: UIBarButtonItem) {
		    ...
		    let delete = UIAlertAction(title: "삭제", style: .destructive) { _ in
		        self.dataManager.deleteSelectedMemo()
		    }
		    ...
		}
}
```

```swift
final class MemoDataManager {
		...
		func deleteSelectedMemo(at indexPath: IndexPath? = nil) {
		    let selectedIndexPath: IndexPath?
		    if indexPath != nil {
		        selectedIndexPath = indexPath
		    } else {
		        selectedIndexPath = listDelegate?.selectedCellIndex
		    }
		    
		    guard let selectedIndexPath = selectedIndexPath else {
		        return
		    }
		    let deletedMemo = memos[selectedIndexPath.row]
		    deleteMemo(id: deletedMemo.id)
		    listDelegate?.deleteCell(at: selectedIndexPath)
		    
		    if selectedIndexPath.row < memos.count {
		        let memo = memos[selectedIndexPath.row]
		        detailDelegate?.showTextView(with: memo)
		        listDelegate?.selectNextCell(at: selectedIndexPath)
		    } else {
		        detailDelegate?.showIneditableTextView()
		    }
		}
		...
}
```

## 2-2 질문드리고 싶은 부분

## 앱 첫 실행 화면에서 첫번째 셀이 선택되지 않는 문제

<img src="https://i.imgur.com/fNxtYVr.png" width="50%" height="50%">

정상적으로 작동하는 모습

### 문제 상황

앱을 실행했을 때, selectFirstMemo()가 실행되면서 첫번째 셀이 선택되고 해당 셀의 내용을 detailView에 보여줘야합니다.

원래는 MemoListViewController의 viewDidLoad() 에서 selectFirstMemo()를 호출주었습니다.

그런데 List의 셀은 선택이 되지만, 선택된 셀의 상세페이지는 보이지 않는 문제가 발생했습니다. 

반대로 MemoDetailViewController에서 viewDidLoad() 에서 selectFirstMemo()를 호출하면 

선택된 셀의 상세페이지는 보이지만 List의 셀은 선택이 되지 않는 문제가 발생합니다. 

### 원인

문제의 원인은 selectFirstMemo()를 호출하는 VC의 delegate 등록만 작동해서 발생하는 것이었습니다.

- ListVC에서 호출하면 listDelegate만 등록되고 detailDelegate는 nil → 첫번째 셀이 선택되지만, 상세메모는 보이지 않음
- DetailVC에서 호출하면 detailDelegate만 등록되고 listDelegate는 nil → 첫번째 상세메모는 보이지만 셀 선택이 안됨

```swift
extension MemoDataManager {
    func selectFirstMemo() {
        if memos.isEmpty == false {
            listDelegate?.setupRowSelection()
            detailDelegate?.showTextView(with: memos[0])
        }
    }
}
```

|ListViewController의 viewDidLoad에서 호출하는 모습|detailDelegate가 nil인 모습|
|:---:|:---:|
|<img src="https://i.imgur.com/HOFGyRr.png" width="50%" height="50%">|<img src="https://i.imgur.com/LLxnl5I.png" width="50%" height="50%">|

해당 메서드를 호출하지 않으면 delegate임을 명시하더라도 무시되는 현상을 확인했습니다. 

좌측 사진은 ListViewController의 `viewDidLoad()`에서 `selectFirstMemo()`를 호출하고 있는 상태고, 

listDelegate / detailDelegate를 출력했을 때 `detailDelegate` 만 nil 이 나오는것을 확인할 수 있었습니다.

### 해결

listVC의 `viewDidAppear`에서 `dataManager.selectFirstMemo()` 호출하는 방식으로 해결했습니다. 

```swift
private let dataManager = MemoDataManager()

private lazy var listViewController = MemoListViewController(dataManager: dataManager)
private lazy var detailViewController = MemoDetailViewController(dataManager: dataManager)

override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    dataManager.selectFirstMemo()
}
```

### 궁금한 점

해결은 했지만 왜 정확히 viewDidAppear에서는 되는건지는 알아내지 못했습니다. ㅠㅠ 

dataManager.selectFirstMemo()를 viewDidLoad에서 호출하면 왜 저희가 예상한대로 작동을 하지 않는지 궁금합니다.

## 메모를 삭제할 때 viewContext를 save하기전에 memos 배열에서도 삭제하지 않으면 Crash가 나는 문제

|saveViewContext를 먼저호출|saveViewContext를 나중에 호출|
|:---:|:---:|
|<img src="https://i.imgur.com/1n9pMDt.jpg" width="50%" height="50%">|<img src="https://i.imgur.com/beG1DkD.jpg" width="50%" height="50%">|

### 문제 상황

처음에는 view context 에서 메모를 삭제하고나서 `viewContext.delete(memoToDelete)`

바로 view context를 save 한 후 `saveViewContext()`

MemoDataManager가 가지고 있는 memos 배열에서도 삭제하였습니다.

그랬더니 Crash가 나며 앱이 중지되었습니다.

### 해결

MemoDataManager가 가지고 있는 memos 배열에서도 삭제해준 후 view context를 save 하는 방법으로 

이렇게 순서를 바꿔서 해결하긴 했는데 Crash가 나는 이유가 궁금합니다.

### 궁금한 점

저희가 생각하기로는 viewContext에서는 삭제가 되었지만 MemoDataManager가 가지고 있는 memos 배열에는 데이터가 남아있어서 viewContext를 저장할때 정보가 일치하지 않아서 생기는 문제라고 이해했는데 저희 생각이 적절한지 궁금합니다!
```swift
final class MemoDataManager {
	...
  var memos = [Memo]()
	...
	func deleteMemo(id: UUID) {
      let request = Memo.fetchRequest()
      let predicate = NSPredicate(format: "id == %@", id.uuidString)
      request.predicate = predicate
      
      do {
          let memos = try viewContext.fetch(request)
          guard let memoToDelete = memos.first else {
              return
          }
          viewContext.delete(memoToDelete)
          let memoToDeleteInArray = self.memos.filter { $0.id == id }
          self.memos = self.memos.filter { memoToDeleteInArray.contains($0) == false }
          saveViewContext()
      } catch {
          print(error.localizedDescription)
      }
  }
}
```

2022-02-23 07:09 UTC, soo941226 commented
안녕하세요~~ 엘리, 제인, 조이!🙇‍♂️
 
 일단 고생 많으셨습니다! 이렇게 빨리 다시 PR을 주실 거라고는 진짜 생각 못했는데 정말 엄청나게 열심히 노력하신 것 같아요. 코드에서 많은 고민이 느껴졌고 앞서 이야기했던 부분이 많이 개선된 것으로 읽었습니다! 존경합니다 😄👍👍
 
 질문주신 내용에 대한 대답에 앞서, 제가 이전에 이야기한 것들 중 잘 전달이 되지 않은 부분도 있는 것 같아서 하나 다시 이야기를 드려보고자 합니다. **고치라는 말은 아니고, 잘못되었다는 말은 더더욱 아니지만,** 여러분이 정말 고민을 하셨는지 피드백이 없어서 확인차 이야기를 남깁니다!

 먼저 Debug view hierarchy를 통해 현재의 계층구조가 어떻게 표현이 되는지 눈으로 확인을 해보시고, 모델과 연결되어야 하는 컨트롤러가 누구일지 고민을 해보시면 좋겠습니다. 특히 현재에는 MemoListViewController, MemoDetailViewController가 DataManager를 전달받은 뒤, 직접 메시지를 주고 받는 구조로 보이는데요.
 제 생각에는 MemoListViewController와 MemoDetailViewController가 DataManager를 알아야할까 라는 생각이 듭니다🤔
 DataManager를 알아야하는 타입이 많음으로 인해서, DataManager에 발생하는 일들이 어떻게 관리가 되고 있는지 파악하기 힘들어지고 처리가 분산되어있다고 느껴져요. 처음에 이를 갖게 되는 SplitViewController가 이러한 일들을 모두 담당할 수 있을 것 같습니다. SplitViewController는 DataManager와 childViewControllers와 메시지를 주고 받고, 각각의 childViewController들은 splitViewController와만 메시지를 주고 받으면 좋지 않을까 하는 생각이 듭니다.

 또 현재의 구조가 부득이한 이유로 반드시 필요하다면, 제 생각에 뷰와 컨트롤러를 재사용하기 위해서는, 이러한 관계들이 지금처럼 DataManager라고 하는 구체타입이 아니라, 프로토콜을 통해서 언제든지 교체가 가능하면 좋을 것 같아요!

 읽어주셔서 감사합니다😅 여러분은 어떻게 생각하시는지 궁금하네요!


<br>

---

<br>

> 앱을 실행했을 때, selectFirstMemo()가 실행되면서 첫번째 셀이 선택되고 해당 셀의 내용을 detailView에 보여줘야합니다.
> 원래는 MemoListViewController의 viewDidLoad() 에서 selectFirstMemo()를 호출주었습니다.
> 그런데 List의 셀은 선택이 되지만, 선택된 셀의 상세페이지는 보이지 않는 문제가 발생했습니다.
> 반대로 MemoDetailViewController에서 viewDidLoad() 에서 selectFirstMemo()를 호출하면
> 선택된 셀의 상세페이지는 보이지만 List의 셀은 선택이 되지 않는 문제가 발생합니다.
> 해결은 했지만 왜 정확히 viewDidAppear에서는 되는건지는 알아내지 못했습니다. ㅠㅠ
> dataManager.selectFirstMemo()를 viewDidLoad에서 호출하면 왜 저희가 예상한대로 작동을 하지 않는지 궁금합니다.

 음 먼저 `DetailVC에서 호출하면 detailDelegate만 등록되고 listDelegate는 nil` 이 부분은 검증이 된 것인지 잘 모르겠네요!
 현재의 코드 구조에서는 MemoListViewController가 아니라 SplitViewController에서 문제점을 찾으셔야해요! 

 1. SplitViewController initializer가 호출
 2. SplitViewController 메모리에 적재
 3. SplitViewController viewDidLoad가 호출
 4. SplitViewController viewDidLoad 내부에서 lazy var인 listViewController와 detailViewController에 접근함으로써 각각의 initializer가 호출
 5. 코드의 순서상 listViewController initializer가 먼저 호출
 6. listViewController 메모리에 적재
 7. listViewController viewDidLoad가 호출
 8. 코드의 순서상 detailViewController initializer가 호출
 9. detailViewController 메모리에 적재
 10. detailViewController viewDidLoad가 호출

 저는 이렇게 읽히네요

> 처음에는 view context 에서 메모를 삭제하고나서 viewContext.delete(memoToDelete)
> 바로 view context를 save 한 후 saveViewContext()
> MemoDataManager가 가지고 있는 memos 배열에서도 삭제하였습니다.
> 그랬더니 Crash가 나며 앱이 중지되었습니다.
> MemoDataManager가 가지고 있는 memos 배열에서도 삭제해준 후 view context를 save 하는 방법으로
> 이렇게 순서를 바꿔서 해결하긴 했는데 Crash가 나는 이유가 궁금합니다.
> 저희가 생각하기로는 viewContext에서는 삭제가 되었지만 MemoDataManager가 가지고 있는 memos 배열에는 데이터가 남아있어서 viewContext를 저장할때 정보가 일치하지 않아서 생기는 문제라고 이해했는데 저희 생각이 적절한지 궁금합니다!

말씀하신 대로 코드를 돌려보니 크래시가 나는 걸 확인했는데요. 에러를 읽어보니 UITableView 관련 에러더라구요
<img width="881" alt="스크린샷 2022-02-23 오후 3 54 16" src="https://user-images.githubusercontent.com/83933153/155273560-7eae2e7b-0010-46da-8bf2-d2b61a621f3e.png">
delete를 하는 부분과 위 부분에서 논리적인 에러가 발생해서 그런 게 아닌가 싶네요. 앞으로는 LLDB를 찍어보시면서 어떤 함수가 호출될 때 크래시가 나는지 확인을 해보시면 잘 해결하실 수 있을 거 같습니다.

<br>

---

추가적으로 의문이 남는 부분은 코멘트를 남겼으니 확인 부탁드릴게요~

2022-02-23 07:10 UTC, soo941226 requested changes

2022-02-23 07:10 UTC, soo941226 commented on CloudNotes/CloudNotes/Extension/UIViewController+Extension.swift
> -
이러한 주석은 왜 삭제하시는지 궁금합니다. 파일을 만들면 왜 이런 주석이 생긴다고 생각하시나요?

2022-02-23 07:10 UTC, soo941226 commented on CloudNotes/CloudNotes/Controller/MemoDetailViewController.swift
>          }
안전한 처리 좋습니다!👍

2022-02-23 07:10 UTC, soo941226 commented on CloudNotes/CloudNotes/Model/MemoDataManager.swift
> +
MemoDataManager가 [[Memo]]를 가지고 있나요?
MemosArray는 오해의 소지가 있을 거 같아요.

2022-02-23 07:10 UTC, soo941226 commented on CloudNotes/CloudNotes/Model/MemoDataManager.swift
> +    var memos = [Memo]()
이건 좀 의아한 커밋이군요🤔
외부에서 접근하는 요소가 없는데 private를 뺀 건 왜일까요?

2022-02-23 07:10 UTC, soo941226 commented on CloudNotes/CloudNotes/Model/MemoDataManager.swift
> +}
DataManager가 UI 요소를 알고 이에 대한 일을 하게 되는 건 조금 과한 책임이 아닐까 싶어요. Manager는 DataManager니까 UI는 자기 담당이 아니라고 하지 않을까요?🤔

2022-02-23 07:22 UTC, soo941226 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
>          delegate?.memoDetailViewController(showTextViewWith: newMemo)
func setupRowSelection에서 dataManager.memos.isEmpty를 하는 것이
func addMemo에서 dataManager.newMemo를 하는 것처럼 처리가 되면
dataManager.memos에 대한 처리가 더욱 안전해지고, 해당 컨트롤러에서는 dataManager에 대해서 더 몰라도 될 것 같아요.
현재의 memos의 접근제어자가 internal인데, 지금처럼 memos에 대해서 실제로 insert를 하는 부분이 컨트롤러에 있는 건 비즈니스 로직이 컨트롤러에 있다는 생각이 들고, DataManager가 managing을 제대로 하고 있지 않는 것 같아요🤔 DataManager가 실제로 managing을 할 수 있도록 개선되면 좋겠습니다!

2022-02-24 06:10 UTC, wooyani77 commented on CloudNotes/CloudNotes/Extension/UIViewController+Extension.swift
> -
쓸데없는 주석들은 지워주는 것이 깔끔하다고 생각해서 삭제해주었습니다! 코멘트를 보고 생각해보니 파일 생성시 해당 주석들이 생기면서 누가, 언제 만들었는지 확인할 수 있을 것 같아요. 다만, 짝프로그래밍을 진행하면서 생성자나 생성시점이 프로젝트를 진행하기에 필요한 정보라는 생각은 들지 않습니다. 수박은 이러한 주석들을 남겨놓으시는 편인가요? 그렇다면 그 이유도 궁금합니다! 😊😊

2022-02-24 06:49 UTC, siwonkim0 commented on CloudNotes/CloudNotes/Model/MemoDataManager.swift
> +    var memos = [Memo]()
현재 listVC에서 memos에 접근해서 데이터의 개수를 알아오거나, memo를 가져오는 부분이 남아있었습니다. 이 부분도 메서드를 만들어서 memos에 직접 접근하는 부분이 없도록 수정하겠습니다!

2022-02-24 06:50 UTC, na-young-kwon commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
>          delegate?.memoDetailViewController(showTextViewWith: newMemo)
수박이 우려하시는 부분이 memos의 접근제어 레벨이 internal 이라는 점 이라고 생각이 되는데요

일단 해당 커밋은 예전의 커밋이라서 따로 개선할 순 없을 것 같고,
현재 남아있는 코드들은 추후에 리팩토링하면서 dataManager가 memos를 private하게 가지고 data만 매니징 하는 쪽으로 개선해보겠습니다

2022-02-24 08:03 UTC, soo941226 commented on CloudNotes/CloudNotes/Extension/UIViewController+Extension.swift
> -
오 납득이 되는 이유네요!👍👍
전 혼자할 때도 남겨놓는 편인데 꼭 커밋을 보지 않더라도 어떤 날짜 순으로 파일이 생성되었는지를 알 수 있어서, 이걸 근거로 코드가 어떤 순서로 작성되었는지 알 수 있을 것 같아요. 특히 누군가에게 보여줘야 할 코드라면 이러한 내용이 꽤 유용하다고 생각을 하고 있습니다.
협업을 할 때에는 특히 담당자가 누구인지 찾을 수 있는 정보라는 생각이 드네요!

2022-02-24 09:46 UTC, na-young-kwon commented on CloudNotes/CloudNotes/Model/MemoDataManager.swift
> +
생각도 못했는데, 복수형이 중복으로 들어가있네요,,ㅎㅎ
setMemos로 수정했습니다.

2022-02-24 09:47 UTC, na-young-kwon commented on CloudNotes/CloudNotes/Model/MemoDataManager.swift
> +}
이 부분도 리팩토링 하면서 UI관련들을 모두 덜어주었습니다!

2022-02-24 09:47 UTC, wooyani77 commented
### 최종 설계

1. DataManager는 UI와 관련된 역할을 하지 않는다
2. SplitVC만 DataManager를 갖는다
3. ListVC / DetailVC에서는 데이터와 관련된 작업을 하지 않는다

리뷰를 읽고 ListVC / DetailVC가 DataManager를 꼭 알아야 하는지에 대해서 많은 고민을 했습니다. 확실이 DataManager를 아는 타입이 많아지면 그 만큼 관리가 어려워질 것 같아요. 그래서 수박이 피드백 해주신대로 SplitVC만 DataManager를 알고있도록 수정해주었어요. (그마저도 Protocol을 만들어서 관계를 느슨하게 해주었어요.)

기존에 ListVC / DetailVC에서 Model 관련 로직들을 모두 없앴습니다. 두 뷰컨은 딱 View를 Controller하는 역할만 하고 있어요. 

또, MemoDataManager에 남아있던 UI관련 로직들도 모두 삭제했습니다.

그 중간에서 SplitVC가 DataManager와 자식 뷰컨들을 중개해주고 있습니다.

<img width="891" alt="image" src="https://user-images.githubusercontent.com/83864058/155499820-68185f05-65c2-4c2a-9097-273c3a0d82ce.png">

### ListVC, DetailVC의 delegate = SplitVC

listViewController와 detailViewController의 delegate를 SplitVC로 지정하여 DataManager의 데이터에 따라 SplitVC가 ListVC와 DetailVC가 할 일을 대신 해주도록 구현하였습니다. 

### SOLID - DIP 원칙 (의존관계 역전 원칙)

상위레벨 모듈은 하위레벨 모듈에 의존하면 안된다는 DIP 원칙에 따라, MemoDataManagable 프로토콜을 정의하여 SplitVC이 생성될 때 MemoDataManagable 프로토콜을 준수하는 어떤 타입이라도 주입될 수 있도록 해주었습니다!

```swift
protocol MemoDataManagable {
    ...
}

extension MemoDataManager: MemoDataManagable {
    ...
}
```

```swift
final class SplitViewController: UISplitViewController {
    private let dataManager: MemoDataManagable
	...
    init(style: UISplitViewController.Style, dataManager: MemoDataManagable) {
        self.dataManager = dataManager
        super.init(style: style)
		}
	...
}
```

덕분에 MVC패턴에 대해 감을 익힐 수 있는 좋은 기회였습니다

이전 코드보다 훨씬 더 역할 분리가 잘 되어있는 것 같아요

2022-02-24 10:37 UTC, soo941226 commented on CloudNotes/CloudNotes/Controller/MemoDetailViewController.swift
MemoDetailViewControllerDelegate가 indexPath가 필요없듯이, MemoListViewControllerDelegate도 indexPath가 필요없지 않을까요? 🤔

2022-02-24 10:37 UTC, soo941226 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
67번 줄에 느낌표가 있네요~~ 느낌표는 없도록 해주세요!

나아가서 memo를 언랩핑할 필요성이 있을까 라는 생각도 드네요.

2022-02-24 10:37 UTC, soo941226 commented on CloudNotes/CloudNotes/Controller/SplitViewController.swift
굳이 lazy할 필요는 없죠! 👍👍

2022-02-24 10:37 UTC, soo941226 commented on CloudNotes/CloudNotes/Model/MemoDataManager.swift
> +    private (set) var memos = [Memo]()
공식문서에서는 private(set)이라고 쓰긴 하네요👀 세분이 합의를 하신 부분이라면 괜찮습니다!

2022-02-24 10:37 UTC, soo941226 commented on CloudNotes/CloudNotes/Model/MemoDataManager.swift
> +}
👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏
저도 생각을 못하고 있던 요소인데 너무 좋습니다!!!!! 진짜 짱이네요😮👍👍

2022-02-24 10:46 UTC, soo941226 commented
정말 많이 고생하셨습니다 여러분!! 

제가 문제점이라고 여기던 각각의 역할에 대한 부분은 전부 개선되었습니다. 나머지는 중복이 되는 내용을 어떻게 줄일지에 대한 고민인 것 같아요.

머지를 하기 전에 마지막으로 질문을 드리고 싶은 게 하나 있습니다! 지금은 어떤 일이 누구의 책임인지를 따지고 리팩토링을 했는데요. 이렇게 각각의 타입이 점점 더 분명한 역할을 갖게 되었을 때 얻는 장점이 뭐라고 생각하시나요? 이전의 코드와 기능적으로는 달라지지 않았고, 이전의 코드도 기능적으로는 완벽했음에도 불구하고 말이죠...🤔

2022-02-24 13:06 UTC, wooyani77 commented on CloudNotes/CloudNotes/Model/MemoDataManager.swift
> +    private (set) var memos = [Memo]()
수정과정을 거치면서 (set) 키워드 자체를 삭제해주었습니다! 다음에 사용할 일이 있으면 공식문서에 따라 붙여서 작성해줘야겠네요! 😅

2022-02-24 13:19 UTC, siwonkim0 commented on CloudNotes/CloudNotes/Controller/MemoDetailViewController.swift
MemoDetailViewControllerDelegate에서는 메모 상세페이지에서 더보기 버튼을 선택하여 메모를 삭제하는 상황입니다. 따라서 메모 리스트에서 선택되어있는 셀을 가져오는 메서드로 indexPath를 알 수 있었습니다. 하지만 MemoListViewControllerDelegate에서는 셀을 스와이프해서 삭제하는 상황이라서 스와이프를 하면 셀 선택이 풀리기때문에 선택된 셀을 가져올 수 없어서 부득이하게 trailingSwipeActionsConfigurationForRowAt 메서드에서 현재의 indexPath를 전달해주도록 했습니다.

2022-02-24 13:21 UTC, wooyani77 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
당장 생각나는 방법을 시도해보았는데, 아래방법은 너무 물음표살인마 같아서,,
<img width="955" alt="image" src="https://user-images.githubusercontent.com/83864058/155531258-d4dae23e-6c8f-418e-b7be-dc63ae81bffd.png">

이 방법으로 수정해보았습니다.. 더 좋은 방법 있을까요?ㅎ
<img width="826" alt="image" src="https://user-images.githubusercontent.com/83864058/155531592-d6c3013b-7013-43b2-a113-faecb9e379de.png">

2022-02-24 13:31 UTC, na-young-kwon commented
#### 이렇게 각각의 타입이 점점 더 분명한 역할을 갖게 되었을 때 얻는 장점이 뭐라고 생각하시나요? 

각 타입의 역할이 명확하게 분리되면
1. 어떤 부분을 고쳐야 하는지 금방 파악할 수 있고
2. 따라서 유지보수가 용의해지고
3. 의존성이 없어지기 때문에 재사용성이 높아지고
4. 특정 타입에 대한 수정이 다른 타입에 영향을 주지 않는다는 점
이 장점이라고 생각합니다. : )

2022-02-24 15:41 UTC, soo941226 commented on CloudNotes/CloudNotes/Controller/MemoListViewController.swift
전 첫번째를 생각했는데 말씀을 듣고 생각해보니 오히려 가독성이 떨어지네요. 현재의 코드가 훨씬 좋은 거 같아요👍

2022-02-24 15:43 UTC, merged